"""
Products & Services Dimension Data - EXECUTION Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

products_services_data = [
    # LEVEL 1: PRODUCTS & SERVICES DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Products & Services",
        "Description": "The portfolio management, development, delivery, and lifecycle management of products and services that create customer value",
        "Business Drivers": "Customer Value & Revenue",
        "Business Drivers Description": "Products & services drive: revenue generation, customer satisfaction, competitive differentiation, market positioning, business model execution, strategic growth.",
        "Performance Factors": "Competitive Portfolio",
        "Performance Factors Description": "Strong product/service performance shows: competitive offerings, strong customer satisfaction (NPS >40), portfolio balance, quality delivery, lifecycle management, innovation pipeline.",
        "Risk Factors": "Product Failures & Portfolio Gaps",
        "Risk Factors Description": "Product/service risks include: failed launches, quality issues, customer dissatisfaction, portfolio gaps, aging portfolio, competitive displacement, commoditization.",
        "Metric": "Overall Products & Services Health Score",
        "Metric Description": "Composite index of 6 element scores: Portfolio Strategy + Product Development + Service Delivery + Quality Management + Lifecycle Management + Customer Experience. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75 (healthy portfolio)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Weight by revenue contribution or strategic importance."
    },

    # LEVEL 2: PORTFOLIO STRATEGY (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Products & Services > Portfolio Strategy",
        "Description": "The strategic planning and management of the product/service portfolio including positioning, investment allocation, and portfolio balance",
        "Business Drivers": "Strategic Alignment & Growth",
        "Business Drivers Description": "Portfolio strategy ensures: strategic alignment (portfolio serves strategy), balanced investment (growth + profit), market coverage, risk diversification, sustainable advantage.",
        "Performance Factors": "Strategic Portfolio Management",
        "Performance Factors Description": "Strong portfolio strategy: clear positioning, balanced portfolio (growth + profit), strategic investments, regular portfolio reviews, disciplined pruning.",
        "Risk Factors": "Portfolio Drift",
        "Risk Factors Description": "Weak portfolio strategy causes: strategic misalignment, imbalanced portfolio (all mature or all growth), missed opportunities, overextension, no pruning (zombie products).",
        "Metric": "Portfolio Strategy Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Portfolio Positioning + Portfolio Balance + Investment Allocation + Portfolio Governance. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining positioning assessment, balance analysis, investment data, and governance evaluation."
    },

    # LEVEL 3: Portfolio Strategy Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Portfolio Strategy > Portfolio Positioning",
        "Description": "The clarity and strength of positioning for each product/service including target customer, value proposition, and competitive differentiation",
        "Business Drivers": "Market Success",
        "Business Drivers Description": "Clear positioning drives: customer clarity (who it's for, why buy), competitive differentiation, pricing power, marketing effectiveness, sales effectiveness.",
        "Performance Factors": "Differentiated Positioning",
        "Performance Factors Description": "Strong positioning: target segment clear, value proposition compelling, differentiated vs competitors, documented positioning, consistently communicated.",
        "Risk Factors": "Positioning Confusion",
        "Risk Factors Description": "Weak positioning causes: customer confusion ('who is this for?'), commoditization (no differentiation), price pressure, weak marketing, sales struggles.",
        "Metric": "Portfolio Positioning Clarity Score",
        "Metric Description": "Assessment of top products/services: target customer defined (Y/N), value prop clear (Y/N), differentiated (Y/N), documented (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">85 (clear positioning)",
        "Instructions": "Assess top 10-20 products/services on positioning clarity: target defined?, value prop?, differentiation?, documented? Score each, average across portfolio."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Portfolio Strategy > Portfolio Balance",
        "Description": "The distribution of products/services across lifecycle stages (growth, maturity, decline) and strategic roles (star, cash cow, question mark, dog)",
        "Business Drivers": "Sustainable Growth & Profitability",
        "Business Drivers Description": "Balanced portfolio provides: growth (new products), profitability (mature cash cows), future options (bets), managed decline (harvest dogs), sustainable business.",
        "Performance Factors": "BCG Matrix Balance",
        "Performance Factors Description": "Well-balanced portfolio: mix of stars (growth + share), cash cows (profit), question marks (options), dogs (minimize). Not over-concentrated in one quadrant.",
        "Risk Factors": "Portfolio Imbalance",
        "Risk Factors Description": "Imbalance risks: all mature (no growth), all growth (no profit), all dogs (declining business), over-concentration in one lifecycle stage.",
        "Metric": "Portfolio Balance Distribution",
        "Metric Description": "% of revenue by lifecycle stage: Growth (<20% rev), Maturity (60-70% rev), Decline (<20% rev). Or BCG: Star, Cash Cow, Question Mark, Dog.",
        "Unit": "Percentage distribution",
        "Target": "Balanced: ~20% Growth, ~60% Mature, ~20% Decline/New",
        "Instructions": "Classify all products/services by lifecycle stage or BCG matrix. Calculate % revenue from each. Healthy mix: growth + mature + decline balanced."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Portfolio Strategy > Investment Allocation",
        "Description": "The strategic allocation of investment resources (R&D, marketing, sales) across the portfolio aligned with strategic priorities",
        "Business Drivers": "Resource Optimization",
        "Business Drivers Description": "Strategic investment allocation ensures: resources to priorities, growth investments (new products), profit harvesting (mature), disciplined divestment (decline).",
        "Performance Factors": "Strategy-Aligned Investment",
        "Performance Factors Description": "Strong allocation: investments align to strategy, growth products funded adequately, declining products starved, portfolio optimization (not peanut butter).",
        "Risk Factors": "Investment Misalignment",
        "Risk Factors Description": "Poor allocation causes: underfunded priorities, overfunded declining products, peanut butter spread (equal to all), strategic drift.",
        "Metric": "Strategic Investment Alignment",
        "Metric Description": "% of product investment (R&D, marketing) allocated to strategic priorities (top 20% by strategic value). Target: >60% to priorities.",
        "Unit": "Percentage (%)",
        "Target": ">60% to strategic priorities",
        "Instructions": "Rank products by strategic priority. Calculate investment (R&D, marketing, sales) to top 20% strategic priorities. Divide by total. Strong alignment: >60%."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Portfolio Strategy > Portfolio Governance",
        "Description": "The decision-making processes and governance for portfolio management including new product approval, investment decisions, and portfolio pruning",
        "Business Drivers": "Disciplined Decisions",
        "Business Drivers Description": "Portfolio governance provides: disciplined decisions (go/no-go), resource prioritization, kill decisions (prune dogs), accountability, strategic alignment.",
        "Performance Factors": "Strong Governance",
        "Performance Factors Description": "Strong governance: regular portfolio reviews (quarterly), stage-gate for new products, kill decisions made (prune portfolio), accountability clear.",
        "Risk Factors": "Governance Gaps",
        "Risk Factors Description": "Weak governance causes: undisciplined launches, no kill decisions (zombie products), resource dilution, accountability gaps, strategic drift.",
        "Metric": "Portfolio Review Frequency",
        "Metric Description": "# of formal portfolio review meetings per year with documented decisions (launches, kills, investments). Best practice: quarterly (4x/year).",
        "Unit": "Reviews per year",
        "Target": ">4 (quarterly reviews)",
        "Instructions": "Track portfolio review meetings: date, attendees, decisions documented (launches, kills, funding). Count annual frequency. Quarterly (4x) is best practice."
    },

    # LEVEL 2: PRODUCT DEVELOPMENT (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Products & Services > Product Development",
        "Description": "The processes and capabilities for developing new products and features from concept through launch including development speed and success rates",
        "Business Drivers": "Innovation & Time-to-Market",
        "Business Drivers Description": "Product development drives: innovation (new offerings), competitive advantage (first to market), revenue growth, customer satisfaction, market leadership.",
        "Performance Factors": "Fast, Successful Development",
        "Performance Factors Description": "Strong product development: fast time-to-market (<12 months), high success rates (>70%), customer validation, cross-functional teams, agile methods.",
        "Risk Factors": "Development Failures",
        "Risk Factors Description": "Poor product development causes: slow time-to-market (miss windows), low success rates (failures), cost overruns, quality issues at launch.",
        "Metric": "Product Development Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Development Speed + Launch Success Rate + Development Quality + Customer Validation. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining cycle time data, success metrics, quality indicators, and validation practices."
    },

    # LEVEL 3: Product Development Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Product Development > Development Speed",
        "Description": "The average time from product concept approval to market launch measured by development cycle time",
        "Business Drivers": "Competitive Advantage",
        "Business Drivers Description": "Fast development provides: first-mover advantage, rapid market response, more innovation cycles (learn faster), competitive positioning.",
        "Performance Factors": "Rapid Development",
        "Performance Factors Description": "Fast development: <12 months concept to launch, agile/iterative methods, MVP approach, cross-functional teams, empowered decision-making.",
        "Risk Factors": "Slow Development",
        "Risk Factors Description": "Slow development (>18 months) causes: missed market windows, competitive disadvantage, fewer innovation cycles, delayed revenue.",
        "Metric": "Average Product Development Cycle Time",
        "Metric Description": "Average months from concept approval to market launch. Benchmark: <12 months good, <9 months fast, >18 months slow.",
        "Unit": "Months",
        "Target": "<12 months average",
        "Instructions": "Track products from concept approval to launch. Calculate average cycle time. Segment by product complexity (major vs minor). Agile/lean targets <12 months."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Product Development > Launch Success Rate",
        "Description": "The percentage of launched products/services that achieve business case objectives and are considered successful",
        "Business Drivers": "ROI & Market Fit",
        "Business Drivers Description": "High success rate delivers: ROI on R&D investment, revenue growth, market fit, organizational confidence, stakeholder support for innovation.",
        "Performance Factors": "High Success Rate",
        "Performance Factors Description": "Strong success: >70% of launches achieve business case, measured at 12 months post-launch, clear success criteria, post-launch reviews.",
        "Risk Factors": "Launch Failures",
        "Risk Factors Description": "Low success rate (<50%) causes: wasted R&D investment, missed revenue, poor market fit, organizational cynicism, competitive gaps.",
        "Metric": "Product Launch Success Rate",
        "Metric Description": "% of product launches that achieved business case objectives at 12 months. Survey sponsors: objectives met? Benchmark: >70% success is strong.",
        "Unit": "Percentage (%)",
        "Target": ">70% launch success",
        "Instructions": "Track all product launches. At 12 months, assess vs business case: revenue target?, adoption target?, market share? Calculate % successful. >70% = strong product management."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Product Development > Development Quality",
        "Description": "The quality of products at launch measured by defect rates, quality issues, and need for rapid post-launch fixes",
        "Business Drivers": "Customer Satisfaction & Cost",
        "Business Drivers Description": "Launch quality prevents: customer dissatisfaction, brand damage, warranty costs, post-launch firefighting, negative reviews, returns.",
        "Performance Factors": "High Launch Quality",
        "Performance Factors Description": "Strong quality: <5% defect rate at launch, minimal critical bugs, rigorous testing, design for quality, quality gates in development.",
        "Risk Factors": "Quality Issues at Launch",
        "Risk Factors Description": "Poor launch quality causes: customer dissatisfaction, brand damage, warranty costs, post-launch fixes (expensive), negative reviews.",
        "Metric": "Launch Defect Rate",
        "Metric Description": "# of defects/quality issues per 100 units shipped in first 90 days post-launch. Or % of customers experiencing issues. Target: <5% defect/issue rate.",
        "Unit": "Percentage (%)",
        "Target": "<5% defect rate at launch",
        "Instructions": "Track quality issues reported in first 90 days post-launch. Calculate defects per unit or % customers affected. <5% = good launch quality. >10% = significant issues."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Product Development > Customer Validation",
        "Description": "The rigor of customer validation during development including discovery, prototyping, beta testing, and feedback incorporation",
        "Business Drivers": "Market Fit",
        "Business Drivers Description": "Customer validation ensures: market fit (customers want it), feature priorities (build what matters), pricing accuracy, positioning clarity, launch success.",
        "Performance Factors": "Rigorous Validation",
        "Performance Factors Description": "Strong validation: customer discovery, prototype testing, beta programs, feedback incorporated, willingness-to-pay tested, iterative refinement.",
        "Risk Factors": "Build-It-They-Won't-Come",
        "Risk Factors Description": "No validation causes: product-market fit failures (40% of failures), wrong features, pricing misses, positioning errors, launch failures.",
        "Metric": "Customer Validation Coverage",
        "Metric Description": "% of product launches with rigorous customer validation (discovery, prototype testing, beta). Target: 100% for customer-facing products.",
        "Unit": "Percentage (%)",
        "Target": "100% validated",
        "Instructions": "Track product development projects. For each, document validation: discovery interviews?, prototype testing?, beta program?, feedback incorporated? Calculate % with validation."
    },

    # LEVEL 2: SERVICE DELIVERY (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Products & Services > Service Delivery",
        "Description": "The consistency, reliability, and quality of service delivery including fulfillment, operations, and customer support",
        "Business Drivers": "Customer Satisfaction",
        "Business Drivers Description": "Service delivery quality drives: customer satisfaction, retention, referrals, brand reputation, competitive differentiation, pricing power.",
        "Performance Factors": "Reliable, High-Quality Delivery",
        "Performance Factors Description": "Strong service delivery: high reliability (>99%), consistent quality, fast response, SLA compliance (>95%), proactive service, customer satisfaction >85%.",
        "Risk Factors": "Service Failures",
        "Risk Factors Description": "Poor service delivery causes: customer dissatisfaction, churn, negative reviews, brand damage, SLA breaches, competitive disadvantage.",
        "Metric": "Service Delivery Excellence Index",
        "Metric Description": "Composite of 4 sub-elements: Service Reliability + Delivery Quality + Response Time + SLA Compliance. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">85",
        "Instructions": "Average 4 sub-element scores combining reliability data, quality metrics, response time tracking, and SLA performance."
    },

    # LEVEL 3: Service Delivery Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Service Delivery > Service Reliability",
        "Description": "The availability and uptime of services measured by the percentage of time services are available and performing as expected",
        "Business Drivers": "Customer Access",
        "Business Drivers Description": "Service reliability ensures: customer access (available when needed), business continuity, SLA compliance, customer satisfaction, revenue protection.",
        "Performance Factors": "High Availability",
        "Performance Factors Description": "Strong reliability: >99% uptime for critical services, redundancy/failover, disaster recovery tested, proactive monitoring, rapid incident response.",
        "Risk Factors": "Service Outages",
        "Risk Factors Description": "Service outages cause: customer access loss, revenue impact, SLA breaches, customer dissatisfaction, competitive disadvantage, brand damage.",
        "Metric": "Service Availability %",
        "Metric Description": "% of time services are available and performing. (Total time - downtime) / total time. Critical services target: >99% (three nines).",
        "Unit": "Percentage (%)",
        "Target": ">99% for critical services",
        "Instructions": "Track service uptime monthly: planned downtime + unplanned downtime. Calculate availability %. Critical services (revenue/customer-facing): target >99%."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Service Delivery > Delivery Quality",
        "Description": "The quality and accuracy of service delivery measured by error rates, defects, and customer-reported quality issues",
        "Business Drivers": "Customer Satisfaction",
        "Business Drivers Description": "Delivery quality drives: customer satisfaction, retention, brand reputation, reduced support costs, competitive differentiation.",
        "Performance Factors": "High-Quality Delivery",
        "Performance Factors Description": "Strong quality: <2% error rate, minimal defects, first-time right >95%, quality checks/controls, proactive quality management.",
        "Risk Factors": "Quality Issues",
        "Risk Factors Description": "Poor delivery quality causes: customer dissatisfaction, rework costs, support burden, negative reviews, churn, brand damage.",
        "Metric": "Service Quality Error Rate",
        "Metric Description": "% of service deliveries with errors or quality issues. Measured by defects, customer complaints, rework. Target: <2% error rate.",
        "Unit": "Percentage (%)",
        "Target": "<2% error rate",
        "Instructions": "Track service delivery transactions. Record quality failures: errors, defects, complaints, rework. Calculate % with issues. <2% = high quality, >5% = serious issues."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Service Delivery > Response Time",
        "Description": "The speed of service delivery and response to customer requests measured by average response and resolution times",
        "Business Drivers": "Customer Experience",
        "Business Drivers Description": "Fast response drives: customer satisfaction (timely service), competitive differentiation, operational efficiency, SLA compliance.",
        "Performance Factors": "Rapid Response",
        "Performance Factors Description": "Strong response: fast fulfillment (meet commitments), rapid issue resolution (<24 hours), proactive communication, meets/exceeds customer expectations.",
        "Risk Factors": "Slow Response",
        "Risk Factors Description": "Slow response causes: customer dissatisfaction, SLA breaches, churn, negative reviews, competitive disadvantage ('they're faster').",
        "Metric": "Average Response/Resolution Time",
        "Metric Description": "Average time from customer request to fulfillment or issue resolution. Segment by request type. Compare to SLA commitments and customer expectations.",
        "Unit": "Hours or days",
        "Target": "Meets SLA commitments",
        "Instructions": "Track all service requests/issues: request time → fulfillment/resolution time. Calculate average by type. Compare to SLA. Flag violations. Industry-specific targets."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Service Delivery > SLA Compliance",
        "Description": "The percentage of service level commitments met including uptime, response time, quality, and performance standards",
        "Business Drivers": "Contract Compliance",
        "Business Drivers Description": "SLA compliance ensures: contract obligations met, customer satisfaction, revenue protection (no credits), trust, competitive positioning.",
        "Performance Factors": "High SLA Compliance",
        "Performance Factors Description": "Strong SLA compliance: >95% of SLA metrics met, proactive management, early warning, continuous improvement, rare breaches.",
        "Risk Factors": "SLA Breaches",
        "Risk Factors Description": "SLA breaches cause: customer dissatisfaction, credits owed (revenue loss), contract risk (termination), reputation damage, renewal risk.",
        "Metric": "SLA Compliance Rate",
        "Metric Description": "% of SLA metrics met across all service contracts. Track by SLA type (availability, response, quality). Target: >95% compliance.",
        "Unit": "Percentage (%)",
        "Target": ">95% SLA compliance",
        "Instructions": "Track all SLA metrics (availability, response, quality, performance). Calculate % meeting SLA by metric and overall. <90% = SLA risk. Root cause breaches."
    },

    # LEVEL 2: QUALITY MANAGEMENT (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Products & Services > Quality Management",
        "Description": "The systems and practices for ensuring product/service quality including quality planning, assurance, control, and improvement",
        "Business Drivers": "Customer Satisfaction & Cost",
        "Business Drivers Description": "Quality management delivers: customer satisfaction (quality products), reduced costs (less rework), brand reputation, competitive advantage, regulatory compliance.",
        "Performance Factors": "Robust Quality Systems",
        "Performance Factors Description": "Strong quality management: quality planning, preventive controls, measurement, continuous improvement, low defect rates (<2%), high customer satisfaction.",
        "Risk Factors": "Quality Failures",
        "Risk Factors Description": "Poor quality causes: customer dissatisfaction, high rework costs, warranty claims, brand damage, product recalls, regulatory violations.",
        "Metric": "Quality Management Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Quality Planning + Preventive Quality + Quality Metrics + Quality Improvement. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">85",
        "Instructions": "Average 4 sub-element scores combining planning assessment, prevention practices, metrics data, and improvement tracking."
    },

    # LEVEL 3: Quality Management Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Quality Management > Quality Planning",
        "Description": "The proactive planning of quality requirements, standards, and acceptance criteria during product/service design and development",
        "Business Drivers": "Prevention",
        "Business Drivers Description": "Quality planning prevents: quality issues (design-in quality), rework (right first time), testing bottlenecks, launch delays, customer dissatisfaction.",
        "Performance Factors": "Comprehensive Quality Plans",
        "Performance Factors Description": "Strong quality planning: requirements defined, acceptance criteria clear, quality built-in (design), testing planned, quality gates defined.",
        "Risk Factors": "Quality Afterthought",
        "Risk Factors Description": "No quality planning causes: quality issues (not designed-in), late discovery (expensive fixes), testing bottlenecks, launch quality problems.",
        "Metric": "Quality Planning Coverage",
        "Metric Description": "% of new products/services with documented quality plans before development. Quality plan = requirements, acceptance criteria, testing strategy. Target: 100%.",
        "Unit": "Percentage (%)",
        "Target": "100% coverage",
        "Instructions": "Track all new product/service projects. For each, verify quality plan exists before development: requirements?, acceptance criteria?, test strategy? Calculate % with plans."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Quality Management > Preventive Quality",
        "Description": "The focus on preventing defects through design for quality, poka-yoke, FMEA, and other proactive quality techniques",
        "Business Drivers": "Cost Efficiency",
        "Business Drivers Description": "Prevention is cheapest quality approach: prevent vs detect vs fix. Saves rework costs, warranty, customer dissatisfaction, brand damage.",
        "Performance Factors": "Prevention Focus",
        "Performance Factors Description": "Strong prevention: design for manufacturability/reliability, FMEA (failure modes analysis), poka-yoke (error-proofing), root cause elimination.",
        "Risk Factors": "Detect-and-Fix Approach",
        "Risk Factors Description": "Detect-and-fix is expensive: rework costs, some defects reach customer, reactive, never eliminate root causes, high inspection costs.",
        "Metric": "Preventive Quality Technique Usage",
        "Metric Description": "% of new products using preventive quality techniques (DFM, FMEA, poka-yoke, design reviews). Target: 100% use prevention.",
        "Unit": "Percentage (%)",
        "Target": "100% use prevention techniques",
        "Instructions": "Track new products. Document preventive techniques used: DFM?, FMEA?, poka-yoke?, design reviews? Calculate % using preventive methods. Best practice: all products."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Quality Management > Quality Metrics",
        "Description": "The definition, measurement, and tracking of quality metrics including defect rates, customer satisfaction, and quality costs",
        "Business Drivers": "Visibility & Accountability",
        "Business Drivers Description": "Quality metrics provide: visibility to quality, data-driven improvement, accountability, early issue detection, customer satisfaction tracking.",
        "Performance Factors": "Comprehensive Quality Metrics",
        "Performance Factors Description": "Strong metrics: defect rates tracked, customer satisfaction measured (CSAT, NPS), quality costs (COPQ), trending, benchmarking.",
        "Risk Factors": "Quality Blind Spots",
        "Risk Factors Description": "No quality metrics cause: invisible problems, opinion-based decisions, late issue discovery, no accountability, inability to improve.",
        "Metric": "Quality Metrics Dashboard Completeness",
        "Metric Description": "Assessment: defect rates tracked (Y/N), CSAT measured (Y/N), quality costs (Y/N), trending (Y/N), benchmarked (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">90 (comprehensive metrics)",
        "Instructions": "Assess quality measurement: defect rates?, customer satisfaction?, quality costs (COPQ)?, trends analyzed?, benchmarks? Score each dimension."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Quality Management > Quality Improvement",
        "Description": "The systematic and continuous improvement of quality through root cause analysis, corrective action, and quality improvement projects",
        "Business Drivers": "Continuous Improvement",
        "Business Drivers Description": "Quality improvement drives: defect reduction, cost reduction (less rework), customer satisfaction improvement, competitive advantage.",
        "Performance Factors": "Active Quality Improvement",
        "Performance Factors Description": "Strong improvement: root cause analysis, corrective/preventive action (CAPA), quality improvement projects, measurable results, Six Sigma.",
        "Risk Factors": "Quality Stagnation",
        "Risk Factors Description": "No quality improvement causes: defect rates don't improve, repeated issues, competitive quality gap, customer dissatisfaction persists.",
        "Metric": "Quality Improvement Project Results",
        "Metric Description": "Defect rate reduction year-over-year from quality improvement projects. Target: >20% annual defect reduction through improvement.",
        "Unit": "Percentage reduction",
        "Target": ">20% annual defect reduction",
        "Instructions": "Track defect rates quarterly. Calculate year-over-year reduction. Attribute improvements to specific projects. >20% annual reduction = strong quality improvement."
    },

    # LEVEL 2: LIFECYCLE MANAGEMENT (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Products & Services > Lifecycle Management",
        "Description": "The management of products/services through all lifecycle stages from introduction through growth, maturity, decline, and retirement",
        "Business Drivers": "Portfolio Optimization",
        "Business Drivers Description": "Lifecycle management optimizes: revenue (maximize in growth/maturity), profit (harvest in decline), portfolio (retire dogs), investment (allocate strategically).",
        "Performance Factors": "Active Lifecycle Management",
        "Performance Factors Description": "Strong lifecycle management: stage tracking, stage-appropriate strategies (grow/maintain/harvest/retire), retirement discipline, portfolio optimization.",
        "Risk Factors": "Lifecycle Neglect",
        "Risk Factors Description": "Poor lifecycle management causes: overspending on declining products, under-investing in growth, zombie products (should be retired), profit erosion.",
        "Metric": "Lifecycle Management Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Lifecycle Stage Tracking + Stage-Appropriate Strategy + Retirement Discipline + Portfolio Renewal. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining tracking data, strategy alignment, retirement metrics, and renewal indicators."
    },

    # LEVEL 3: Lifecycle Management Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Lifecycle Management > Lifecycle Stage Tracking",
        "Description": "The systematic tracking and classification of all products/services by lifecycle stage (introduction, growth, maturity, decline)",
        "Business Drivers": "Portfolio Visibility",
        "Business Drivers Description": "Lifecycle tracking provides: portfolio visibility, stage-appropriate strategies, investment decisions, retirement planning, balanced portfolio.",
        "Performance Factors": "Comprehensive Tracking",
        "Performance Factors Description": "Strong tracking: all products classified by stage, stage definitions clear (growth rate, market share, profitability), regularly updated (quarterly).",
        "Risk Factors": "No Lifecycle Visibility",
        "Risk Factors Description": "No tracking causes: no lifecycle awareness, one-size-fits-all strategies, over-investing in decline, under-investing in growth.",
        "Metric": "Lifecycle Classification Coverage",
        "Metric Description": "% of products/services with current lifecycle stage classification (introduction, growth, maturity, decline). Target: 100% of portfolio classified.",
        "Unit": "Percentage (%)",
        "Target": "100% classified",
        "Instructions": "List all products/services. For each, classify lifecycle stage based on growth rate, market maturity, profitability. Calculate % classified. Update quarterly."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Lifecycle Management > Stage-Appropriate Strategy",
        "Description": "The application of differentiated strategies aligned to lifecycle stage including investment, pricing, and promotion decisions",
        "Business Drivers": "Optimized Returns",
        "Business Drivers Description": "Stage-appropriate strategies optimize: growth (invest in introduction/growth), profit (harvest maturity), cash (milk decline), returns across portfolio.",
        "Performance Factors": "Differentiated Strategies",
        "Performance Factors Description": "Strong strategy: growth products get investment, mature products optimized for profit, declining products harvested/retired, not one-size-fits-all.",
        "Risk Factors": "Mismatched Strategies",
        "Risk Factors Description": "Strategy-stage mismatch causes: over-investing in decline, under-investing in growth, missed profit in maturity, poor returns.",
        "Metric": "Strategy-Stage Alignment Score",
        "Metric Description": "Assessment of top products: strategy matches lifecycle stage? Growth gets investment?, Mature harvested for profit?, Decline retired? Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">85 (aligned strategies)",
        "Instructions": "Review top 20 products. For each, assess: strategy aligned to lifecycle stage? Investment/pricing/promotion appropriate? Score alignment. Average across portfolio."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Lifecycle Management > Retirement Discipline",
        "Description": "The willingness and capability to retire declining products/services rather than indefinitely supporting zombie products",
        "Business Drivers": "Resource Liberation",
        "Business Drivers Description": "Retirement discipline frees: resources for growth products, simplified operations, reduced support costs, focus, portfolio optimization.",
        "Performance Factors": "Active Retirement",
        "Performance Factors Description": "Strong retirement discipline: regular retirement decisions, clear retirement criteria, migration plans (customers), executed retirements, zombie product elimination.",
        "Risk Factors": "Zombie Products",
        "Risk Factors Description": "No retirement discipline creates: zombie products (drain resources), complexity costs, support burden, delayed portfolio renewal, missed opportunities.",
        "Metric": "Product Retirement Rate",
        "Metric Description": "# of products retired in past 12 months / total product count. Healthy portfolios retire 5-10% annually. 0% retirements = no discipline (zombies accumulate).",
        "Unit": "Percentage (% retired annually)",
        "Target": "5-10% retired annually",
        "Instructions": "Track products retired (end-of-life, discontinued) in past 12 months. Divide by total product count. 0% = no retirements (zombie accumulation). 5-10% healthy."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Lifecycle Management > Portfolio Renewal",
        "Description": "The rate at which new products/services are introduced to replace declining offerings and drive growth",
        "Business Drivers": "Growth & Relevance",
        "Business Drivers Description": "Portfolio renewal drives: revenue growth (new products), market relevance, competitive positioning, customer excitement, avoid commoditization.",
        "Performance Factors": "Consistent Renewal",
        "Performance Factors Description": "Strong renewal: new products contribute >20% revenue within 3 years, regular launch cadence, replacements for retired products, portfolio vitality.",
        "Risk Factors": "Aging Portfolio",
        "Risk Factors Description": "No renewal causes: aging portfolio (all mature/declining), revenue decline, commoditization, loss of relevance, competitive displacement.",
        "Metric": "Vitality Index",
        "Metric Description": "% of revenue from products introduced in past 3 years. Benchmark: <10% = aging portfolio, 10-20% = moderate renewal, >20% = strong renewal.",
        "Unit": "Percentage (% revenue)",
        "Target": ">20% revenue from products <3 years old",
        "Instructions": "Calculate revenue from products launched in past 3 years. Divide by total revenue. Industry leaders: 30-40%. <10% signals aging portfolio risk."
    },

    # LEVEL 2: CUSTOMER EXPERIENCE (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Products & Services > Customer Experience",
        "Description": "The end-to-end customer experience across all touchpoints including ease of use, support quality, problem resolution, and overall satisfaction",
        "Business Drivers": "Customer Loyalty & Growth",
        "Business Drivers Description": "Customer experience drives: satisfaction, loyalty, retention, referrals (word-of-mouth growth), pricing power, competitive differentiation.",
        "Performance Factors": "Excellent Customer Experience",
        "Performance Factors Description": "Strong customer experience: high satisfaction (CSAT >85%), high loyalty (NPS >40), easy to use, responsive support, problems resolved, customer-centric.",
        "Risk Factors": "Poor Customer Experience",
        "Risk Factors Description": "Poor experience causes: churn, negative reviews, poor referrals, price pressure (commoditization), competitive vulnerability, slow growth.",
        "Metric": "Customer Experience Excellence Index",
        "Metric Description": "Composite of 4 sub-elements: Customer Satisfaction + Net Promoter Score + Ease of Use + Support Quality. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">85",
        "Instructions": "Average 4 sub-element scores combining CSAT, NPS, usability metrics, and support performance data."
    },

    # LEVEL 3: Customer Experience Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Customer Experience > Customer Satisfaction (CSAT)",
        "Description": "The measurement of customer satisfaction with products/services through surveys and feedback mechanisms",
        "Business Drivers": "Retention",
        "Business Drivers Description": "Customer satisfaction drives: retention (satisfied customers stay), referrals, pricing power, lower acquisition costs (retain vs replace).",
        "Performance Factors": "High Satisfaction",
        "Performance Factors Description": "Strong CSAT: >85% satisfied (4-5 on 5-point scale), trending positive, issues addressed, satisfaction measured regularly (quarterly).",
        "Risk Factors": "Customer Dissatisfaction",
        "Risk Factors Description": "Low satisfaction (<70%) signals: churn risk, negative word-of-mouth, quality issues, competitive vulnerability, revenue at risk.",
        "Metric": "Customer Satisfaction Score (CSAT)",
        "Metric Description": "% of customers rating satisfaction 4-5 on 5-point scale ('satisfied' or 'very satisfied'). Survey post-purchase or quarterly. Target: >85%.",
        "Unit": "Percentage (% satisfied)",
        "Target": ">85% satisfied",
        "Instructions": "Survey customers: 'How satisfied are you with [product/service]?' 5-point scale. Calculate % rating 4-5. <70% = dissatisfaction risk. Investigate drivers."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Customer Experience > Net Promoter Score (NPS)",
        "Description": "The measurement of customer loyalty and willingness to recommend through the Net Promoter Score methodology",
        "Business Drivers": "Loyalty & Word-of-Mouth Growth",
        "Business Drivers Description": "NPS predicts: customer loyalty, referral growth (word-of-mouth), retention, revenue growth. Promoters = growth engine.",
        "Performance Factors": "Strong NPS",
        "Performance Factors Description": "Strong NPS: >40 good, >70 world-class, more promoters than detractors, improving trend, actions on feedback.",
        "Risk Factors": "Low NPS",
        "Risk Factors Description": "NPS <0 (more detractors than promoters) signals: churn risk, negative word-of-mouth, damaged brand, revenue decline risk.",
        "Metric": "Net Promoter Score (NPS)",
        "Metric Description": "% Promoters (9-10 rating) - % Detractors (0-6 rating) on 'likelihood to recommend' question. NPS range: -100 to +100.",
        "Unit": "Score (-100 to +100)",
        "Target": ">40 (good), >70 (world-class)",
        "Instructions": "Survey customers: 'How likely are you to recommend us?' 0-10 scale. Calculate: % rating 9-10 minus % rating 0-6. Industry benchmarks vary: 40+ is generally strong."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Customer Experience > Ease of Use",
        "Description": "The ease with which customers can use products/services and achieve their objectives measured by usability metrics and customer effort",
        "Business Drivers": "Adoption & Satisfaction",
        "Business Drivers Description": "Ease of use drives: adoption (easy = more usage), satisfaction, reduced support needs, competitive differentiation, pricing power.",
        "Performance Factors": "Intuitive, Easy",
        "Performance Factors Description": "Strong ease of use: intuitive interface, low learning curve, self-service capable, minimal support needed, customer effort score >4.5/5.",
        "Risk Factors": "Complex, Difficult",
        "Risk Factors Description": "Difficult to use causes: low adoption, customer frustration, high support costs, competitive disadvantage ('easier alternatives exist').",
        "Metric": "Customer Effort Score (CES)",
        "Metric Description": "Survey: 'How easy was it to [achieve goal]?' 1-5 scale. Calculate average. Or % rating 4-5 (easy/very easy). Target: >80% easy.",
        "Unit": "Score (1-5) or % easy",
        "Target": "Avg >4.5 or >80% rate easy",
        "Instructions": "Survey customers post-interaction: 'How easy was it to...?' 5-point scale. Calculate average score or % rating 4-5. Low scores = friction/complexity."
    },
    {
        "Level": 3,
        "Hierarchy": "Products & Services > Customer Experience > Support Quality",
        "Description": "The quality and effectiveness of customer support including responsiveness, knowledge, problem resolution, and support satisfaction",
        "Business Drivers": "Customer Retention",
        "Business Drivers Description": "Support quality impacts: customer satisfaction (support experience matters), retention (good support saves relationships), referrals.",
        "Performance Factors": "Excellent Support",
        "Performance Factors Description": "Strong support: first-call resolution >70%, fast response (<2 hours), knowledgeable reps, problem resolution >90%, support satisfaction >85%.",
        "Risk Factors": "Poor Support",
        "Risk Factors Description": "Poor support causes: customer frustration, escalations, churn (bad support = leave), negative reviews, competitive vulnerability.",
        "Metric": "Support Satisfaction Score",
        "Metric Description": "Customer rating of support experience. Survey post-support: 'How satisfied were you with support?' 5-point scale. % favorable (4-5). Target: >85%.",
        "Unit": "Percentage (% satisfied)",
        "Target": ">85% satisfied with support",
        "Instructions": "Survey customers after support interactions. 'How satisfied were you with support?' 5-point scale. Calculate % rating 4-5. Also track: FCR, response time, resolution rate."
    }
]
