"""
Technology Dimension Data - ENABLERS Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

technology_data = [
    # LEVEL 1: TECHNOLOGY DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Technology",
        "Description": "The IT infrastructure, applications, data capabilities, and technology practices that enable business operations and competitive advantage",
        "Business Drivers": "Operational Enablement & Innovation",
        "Business Drivers Description": "Technology enables: business operations (reliability), customer experience (digital), innovation (speed/capabilities), efficiency (automation), data-driven decisions, competitive advantage.",
        "Performance Factors": "Modern, Reliable Tech Stack",
        "Performance Factors Description": "High-performing technology shows: >99% uptime, modern architecture (cloud, APIs), strong cybersecurity posture, effective data/analytics, agile IT delivery, innovation enablement.",
        "Risk Factors": "Technology Failures & Obsolescence",
        "Risk Factors Description": "Technology risks include: system outages (revenue loss), cyber attacks (data breach), technical debt (slows innovation), skills gaps, legacy constraints, failed projects.",
        "Metric": "Overall Technology Health Score",
        "Metric Description": "Composite index of 6 element scores: IT Infrastructure + Application Portfolio + Data & Analytics + Cybersecurity + IT Operations + Technology Innovation. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70 (healthy technology)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Weight by strategic importance. Technology leaders score >80."
    },

    # LEVEL 2: IT INFRASTRUCTURE (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Technology > IT Infrastructure",
        "Description": "The underlying technology foundation including servers, networks, cloud platforms, and core infrastructure that supports all applications and services",
        "Business Drivers": "Reliability & Scalability",
        "Business Drivers Description": "Strong infrastructure enables: application reliability (uptime), performance at scale, cost efficiency (cloud optimization), disaster recovery, global reach, rapid provisioning.",
        "Performance Factors": "Modern, Resilient Infrastructure",
        "Performance Factors Description": "Strong infrastructure shows: cloud-first architecture, >99.9% availability, auto-scaling, geo-redundancy, rapid provisioning (<1 hour), infrastructure-as-code, cost-optimized.",
        "Risk Factors": "Infrastructure Failures & Constraints",
        "Risk Factors Description": "Infrastructure risks: outages (revenue loss), performance degradation (poor CX), scaling constraints (growth blockers), high costs, long lead times, disaster vulnerability.",
        "Metric": "IT Infrastructure Health Index",
        "Metric Description": "Composite of 4 sub-elements: Infrastructure Availability + Cloud Adoption + Scalability + Disaster Recovery Readiness. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining uptime data, architecture assessment, and capability maturity. Modern infrastructure scores >85."
    },

    # LEVEL 3: IT Infrastructure Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Infrastructure > Infrastructure Availability",
        "Description": "The reliability and uptime of core infrastructure services measured as percentage of time services are available and performant",
        "Business Drivers": "Business Continuity",
        "Business Drivers Description": "Infrastructure availability sustains: revenue operations (e.g., 99% uptime = 3.65 days/year down), customer access, employee productivity, SLA compliance, brand trust.",
        "Performance Factors": "High Availability Architecture",
        "Performance Factors Description": "High availability shows: >99.9% uptime (8.76 hrs/year down), redundant systems, no single points of failure, automated failover, rapid recovery (<15 min MTTR).",
        "Risk Factors": "Infrastructure Outages",
        "Risk Factors Description": "Infrastructure outages drive: revenue loss ($1M+/hour for e-commerce), customer churn, SLA breaches, brand damage, regulatory risk (especially financial services).",
        "Metric": "Infrastructure Availability %",
        "Metric Description": "Uptime % for core infrastructure (compute, storage, network) calculated as (total time - downtime) / total time. Measure monthly, report annual avg.",
        "Unit": "Percentage (%)",
        "Target": ">99.9% (three nines)",
        "Instructions": "Track all unplanned infrastructure downtime. Calculate monthly uptime %. Report annual average. Segment by service tier (critical vs standard). Target: Critical >99.9%, Standard >99.5%."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Infrastructure > Cloud Adoption Maturity",
        "Description": "The extent to which the organization has migrated from on-premises infrastructure to cloud platforms and adopted cloud-native architecture patterns",
        "Business Drivers": "Agility & Cost Efficiency",
        "Business Drivers Description": "Cloud adoption enables: rapid scaling (vs months for hardware), pay-per-use costs (vs CapEx), global reach, innovation access (AI/ML services), operational efficiency.",
        "Performance Factors": "Cloud-First Architecture",
        "Performance Factors Description": "Mature cloud adoption shows: >80% workloads in cloud, cloud-native architectures (microservices, containers), IaC standard, multi-cloud strategy, FinOps practice.",
        "Risk Factors": "Legacy On-Premises Constraints",
        "Risk Factors Description": "Low cloud adoption risks: slow provisioning (weeks vs minutes), scaling constraints, high CapEx, data center dependencies, inability to leverage cloud innovation.",
        "Metric": "Cloud Adoption Rate",
        "Metric Description": "% of IT workloads (applications, services) running on cloud platforms vs on-premises. Benchmark: <50% = lagging, 50-80% = transitioning, >80% = cloud-first.",
        "Unit": "Percentage (%)",
        "Target": ">70% workloads in cloud",
        "Instructions": "Inventory all IT workloads. Classify as cloud-based or on-premises. Calculate % cloud-based. Track migration trajectory. Also assess cloud-native patterns adoption (containers, serverless)."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Infrastructure > Infrastructure Scalability",
        "Description": "The ability of infrastructure to scale capacity up or down rapidly in response to demand changes without performance degradation or manual intervention",
        "Business Drivers": "Growth Enablement & Cost Efficiency",
        "Business Drivers Description": "Infrastructure scalability enables: growth without constraints (no capacity planning bottleneck), handling demand spikes (flash sales, seasonality), cost optimization (scale down when quiet).",
        "Performance Factors": "Auto-Scaling Capability",
        "Performance Factors Description": "Strong scalability shows: auto-scaling configured (CPU/memory triggers), sub-1-hour scale-up, elastic costs (variable with demand), load testing validates limits.",
        "Risk Factors": "Scaling Constraints",
        "Risk Factors Description": "Poor scalability risks: growth blocked by capacity, performance degradation under load, manual scaling delays (hours/days), overprovisioning waste, revenue loss from downtime.",
        "Metric": "Infrastructure Provisioning Lead Time",
        "Metric Description": "Time from capacity request to service availability. Cloud-native target: <1 hour (auto-scaling). Legacy: days to weeks. Measure for compute, storage, network.",
        "Unit": "Hours (or days)",
        "Target": "<1 hour (auto-scaling)",
        "Instructions": "Track time from capacity request to availability. For auto-scaling environments, measure time to scale-up event completion. For manual, track request-to-delivery. Report p50, p95."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Infrastructure > Disaster Recovery Readiness",
        "Description": "The organization's preparedness to recover IT systems and data following major disruptions, measured by recovery time and point objectives",
        "Business Drivers": "Business Continuity & Risk Mitigation",
        "Business Drivers Description": "DR readiness ensures: business continuity (major incident recovery), data protection (minimal loss), regulatory compliance (many industries require DR), stakeholder confidence.",
        "Performance Factors": "Tested DR Capability",
        "Performance Factors Description": "Strong DR shows: documented DR plans, RTO <4 hours, RPO <1 hour, geo-redundant backups, quarterly DR tests, automated failover, runbooks current.",
        "Risk Factors": "DR Failures",
        "Risk Factors Description": "Poor DR preparedness risks: prolonged outages (days), data loss (breach/corruption), business failure (some don't recover), regulatory violations, massive revenue loss.",
        "Metric": "Disaster Recovery Test Success Rate",
        "Metric Description": "% of DR test scenarios that meet RTO/RPO targets in annual or quarterly testing. Healthy: 100% pass. <80% indicates serious gaps.",
        "Unit": "Percentage (%)",
        "Target": "100% of DR tests pass RTO/RPO",
        "Instructions": "Conduct quarterly DR tests for critical systems. Test failover, recovery, data integrity. Document: planned RTO/RPO vs actual. Calculate % meeting targets. Remediate failures immediately."
    },

    # LEVEL 2: APPLICATION PORTFOLIO (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Technology > Application Portfolio",
        "Description": "The collection of software applications supporting business processes, including custom-built, commercial off-the-shelf (COTS), and SaaS solutions",
        "Business Drivers": "Business Process Enablement",
        "Business Drivers Description": "Application portfolio enables: core business processes (ERP, CRM), customer interactions (web, mobile), productivity (collaboration), differentiation (custom apps).",
        "Performance Factors": "Modern, Rationalized Portfolio",
        "Performance Factors Description": "Strong portfolio shows: modern tech stacks, SaaS-first for non-differentiating, custom for core differentiation, low redundancy, API-connected, technical debt managed.",
        "Risk Factors": "Legacy Applications & Technical Debt",
        "Risk Factors Description": "Portfolio risks: legacy app constraints (slow change), technical debt (70% IT budget on maintenance), redundant apps (inefficiency), integration spaghetti, security vulnerabilities.",
        "Metric": "Application Portfolio Health Index",
        "Metric Description": "Composite of 4 sub-elements: Application Modernization + Portfolio Rationalization + Technical Debt Ratio + Application Performance. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining portfolio assessments and performance data. Modern portfolios score >75."
    },

    # LEVEL 3: Application Portfolio Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Technology > Application Portfolio > Application Modernization Level",
        "Description": "The age and technology currency of the application portfolio, indicating the prevalence of modern vs legacy technology stacks",
        "Business Drivers": "Agility & Maintainability",
        "Business Drivers Description": "Modern applications enable: faster feature delivery, easier maintenance, better performance, security patches available, talent availability (modern skills), integration-friendly (APIs).",
        "Performance Factors": "Current Technology Stacks",
        "Performance Factors Description": "Modern portfolio shows: <5 years avg app age, current framework versions, microservices/APIs, cloud-native, mobile-responsive, actively maintained vendor products.",
        "Risk Factors": "Legacy Technology Debt",
        "Risk Factors Description": "Legacy apps risk: slow change (months for features), talent scarcity (COBOL devs retiring), security vulnerabilities (unsupported versions), high maintenance costs, integration challenges.",
        "Metric": "Application Age Distribution",
        "Metric Description": "% of applications by age: <3 years (modern), 3-7 years (current), 7-15 years (aging), >15 years (legacy). Healthy: >40% modern+current, <20% legacy.",
        "Unit": "Percentage distribution",
        "Target": ">40% modern/current, <20% legacy",
        "Instructions": "Inventory all applications with deployment/build dates. Classify by age. Calculate distribution. Flag legacy apps (>15 years) for modernization roadmap. Update annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Application Portfolio > Portfolio Rationalization",
        "Description": "The degree to which the application portfolio is streamlined, with minimal redundancy and clear alignment of each application to business capability",
        "Business Drivers": "Cost Efficiency & Simplicity",
        "Business Drivers Description": "Rationalized portfolio reduces: license costs (redundant apps), maintenance burden, integration complexity, training overhead, security surface. Clarity on what does what.",
        "Performance Factors": "Streamlined Portfolio",
        "Performance Factors Description": "Rationalized portfolio shows: one app per business capability (minimal overlap), regular sunset process, clear ownership, documented capability map, low app count per employee.",
        "Risk Factors": "Portfolio Sprawl",
        "Risk Factors Description": "Unrestricted portfolio grows: redundant capabilities (5 project mgmt tools), shadow IT, orphaned apps, integration mess, ballooning costs, lack of control.",
        "Metric": "Application-to-Employee Ratio",
        "Metric Description": "# of business applications / # of employees. Benchmark: Well-rationalized = 0.05-0.15 (1 app per 7-20 employees). >0.3 indicates sprawl.",
        "Unit": "Ratio (apps per employee)",
        "Target": "<0.15 (1 app per 7 employees)",
        "Instructions": "Count all business applications (exclude infrastructure/dev tools). Divide by employee count. Ratio >0.3 indicates sprawl. Conduct capability mapping to identify redundancy."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Application Portfolio > Technical Debt Ratio",
        "Description": "The percentage of IT development capacity consumed by maintaining existing systems vs building new capabilities, indicating technical debt burden",
        "Business Drivers": "Innovation Capacity",
        "Business Drivers Description": "Low technical debt frees: IT capacity for innovation (vs maintenance), faster feature delivery, ability to respond to market changes, talent engagement (new vs maintenance work).",
        "Performance Factors": "Balanced Maintenance-Innovation",
        "Performance Factors Description": "Healthy technical debt: 30-40% effort on maintenance/tech debt, 60-70% on new capabilities. Allows innovation while keeping debt manageable.",
        "Risk Factors": "Technical Debt Spiral",
        "Risk Factors Description": "High technical debt (>60% capacity on maintenance) drives: innovation starvation, slow market response, talent frustration (boring work), competitive disadvantage, death spiral.",
        "Metric": "Run-the-Bank vs Change-the-Bank Ratio",
        "Metric Description": "% of IT effort on Run (BAU, maintenance, support) vs Change (new features, capabilities). Target: 30-40% Run, 60-70% Change.",
        "Unit": "Percentage (% on Run)",
        "Target": "30-40% on Run, 60-70% on Change",
        "Instructions": "Track all IT effort (dev, ops, support). Classify as Run (maintenance, support, BAU) or Change (new features, capabilities). Calculate % on Run. Quarterly tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Application Portfolio > Application Performance",
        "Description": "The speed, responsiveness, and reliability of business applications from the end-user perspective, measured by response times and availability",
        "Business Drivers": "User Productivity & Experience",
        "Business Drivers Description": "Application performance impacts: user productivity (slow apps = wasted time), customer satisfaction (slow = churn), revenue (cart abandonment), employee frustration.",
        "Performance Factors": "Fast, Reliable Applications",
        "Performance Factors Description": "High-performance apps show: <2 sec page load times, >99.5% availability, responsive under load, proactive monitoring, rapid issue resolution (MTTR <30 min).",
        "Risk Factors": "Poor Application Performance",
        "Risk Factors Description": "Slow/unreliable apps drive: productivity loss (slow apps = $40k/year/employee), customer churn (53% abandon if >3 sec load), revenue loss, support load.",
        "Metric": "Application Performance Score",
        "Metric Description": "Composite of: avg page load time (<2 sec target), application availability (>99.5% target), error rate (<1% target). Weight by user impact.",
        "Unit": "Score (0-100)",
        "Target": ">90",
        "Instructions": "Measure key application metrics: response time (p95), availability %, error rate. Calculate composite score. Monitor via APM tools (New Relic, Datadog). Monthly reporting."
    },

    # LEVEL 2: DATA & ANALYTICS (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Technology > Data & Analytics",
        "Description": "The organization's capabilities in data collection, storage, quality, governance, analytics, and insights generation to enable data-driven decision-making",
        "Business Drivers": "Data-Driven Decisions",
        "Business Drivers Description": "Data & analytics enable: informed decisions (evidence vs intuition), customer insights, operational optimization, predictive capabilities, competitive advantage, regulatory compliance.",
        "Performance Factors": "Mature Data Capabilities",
        "Performance Factors Description": "Strong data capabilities show: single source of truth, high data quality (>95% accuracy), self-service analytics, advanced analytics (ML/AI), data governance, real-time insights.",
        "Risk Factors": "Poor Data Quality & Silos",
        "Risk Factors Description": "Data risks: poor quality (garbage in = bad decisions), data silos (no single truth), compliance violations (GDPR), missed insights, competitive disadvantage.",
        "Metric": "Data & Analytics Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Data Quality + Data Governance + Analytics Adoption + Advanced Analytics Capability. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores. Use data maturity models (e.g., Gartner). Data-driven orgs score >75."
    },

    # LEVEL 3: Data & Analytics Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Technology > Data & Analytics > Data Quality",
        "Description": "The accuracy, completeness, consistency, and timeliness of data across systems, measured by data quality metrics and user trust",
        "Business Drivers": "Decision Quality",
        "Business Drivers Description": "High data quality ensures: accurate decisions (bad data = bad decisions), regulatory compliance, customer trust, operational efficiency, analytics value (garbage in = garbage out).",
        "Performance Factors": "High Quality Data",
        "Performance Factors Description": "Strong data quality shows: >95% accuracy, completeness >98%, validated at entry, data quality rules enforced, automated quality checks, master data management.",
        "Risk Factors": "Poor Data Quality",
        "Risk Factors Description": "Low data quality drives: bad decisions ($15M avg annual cost), compliance violations, customer frustration (wrong info), operational errors, distrust of data/reports.",
        "Metric": "Data Quality Score",
        "Metric Description": "Composite of: accuracy % (correct), completeness % (not null), consistency % (matches across systems), timeliness (freshness). Measured on critical data entities.",
        "Unit": "Score (0-100)",
        "Target": ">95",
        "Instructions": "Define critical data entities (customer, product, transaction). Implement quality rules. Measure accuracy, completeness, consistency, timeliness monthly. Report composite score."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Data & Analytics > Data Governance Maturity",
        "Description": "The policies, processes, roles, and controls ensuring data is managed as a strategic asset with clear ownership, security, and compliance",
        "Business Drivers": "Compliance & Trust",
        "Business Drivers Description": "Data governance ensures: regulatory compliance (GDPR, CCPA), data security (breach prevention), data quality (accountability), ethical use, clear ownership and accountability.",
        "Performance Factors": "Mature Governance",
        "Performance Factors Description": "Strong data governance shows: data catalog maintained, clear data ownership, privacy by design, data classification (PII/sensitive), access controls, audit trails.",
        "Risk Factors": "Governance Gaps",
        "Risk Factors Description": "Weak governance risks: compliance violations (fines), data breaches (no controls), ethical issues (bias in AI), poor quality (no accountability), shadow data.",
        "Metric": "Data Governance Maturity Level",
        "Metric Description": "Maturity assessment (1-5): 1=Ad-hoc, 2=Developing, 3=Defined, 4=Managed, 5=Optimized. Assess: policies, ownership, quality, privacy, security, metadata.",
        "Unit": "Level (1-5)",
        "Target": "Level 4 (Managed)",
        "Instructions": "Use data governance maturity model (e.g., DAMA-DMBOK). Assess 6 dimensions: policy, ownership, quality, privacy, security, metadata. Rate 1-5. Conduct annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Data & Analytics > Analytics Adoption Rate",
        "Description": "The percentage of employees actively using data and analytics tools to inform decisions, indicating analytics democratization and data literacy",
        "Business Drivers": "Data-Driven Culture",
        "Business Drivers Description": "High analytics adoption drives: data-driven decisions (at all levels), faster insights (self-service), reduced analyst bottleneck, democratized data, competitive advantage.",
        "Performance Factors": "Widespread Analytics Use",
        "Performance Factors Description": "Strong analytics adoption shows: >50% employees use BI tools, self-service analytics, data literacy programs, analytics embedded in workflows, experimentation culture (A/B tests).",
        "Risk Factors": "Analytics Underutilization",
        "Risk Factors Description": "Low adoption (<20%) signals: intuition-based decisions (vs evidence), analyst bottleneck, poor tool usability, data illiteracy, wasted analytics investment.",
        "Metric": "Active Analytics Users %",
        "Metric Description": "% of employees who accessed BI/analytics tools in past 30 days. Benchmark: <20% = low, 20-50% = developing, >50% = data-driven culture.",
        "Unit": "Percentage (%)",
        "Target": ">50% active users",
        "Instructions": "Track unique users accessing BI tools (Tableau, Power BI, Looker) in trailing 30 days. Divide by total employees. Monthly tracking. Also segment by role (managers should be >80%)."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Data & Analytics > Advanced Analytics Capability",
        "Description": "The organization's ability to perform predictive analytics, machine learning, and AI applications beyond basic reporting and dashboards",
        "Business Drivers": "Predictive Insights & Automation",
        "Business Drivers Description": "Advanced analytics enables: predictive insights (anticipate vs react), personalization (ML recommendations), automation (AI decision-making), competitive advantage, new business models.",
        "Performance Factors": "Production ML/AI Models",
        "Performance Factors Description": "Strong advanced analytics shows: ML models in production (not just experiments), data science team, MLOps practices, business value delivery, diverse use cases (forecasting, recommendations, NLP).",
        "Risk Factors": "Analytics Plateau",
        "Risk Factors Description": "Lack of advanced analytics limits: competitive positioning (competitors use AI), automation opportunities, predictive capabilities, stuck in descriptive (what happened) vs prescriptive (what to do).",
        "Metric": "Production ML Models Count",
        "Metric Description": "# of machine learning / AI models deployed in production delivering business value. Excludes experiments. Benchmark: 0 = none, 1-5 = emerging, >10 = advanced.",
        "Unit": "Count",
        "Target": ">5 production models",
        "Instructions": "Inventory ML/AI models in production (serving predictions/decisions). Count only models with measurable business impact. Track new models deployed quarterly. Report by use case."
    },

    # LEVEL 2: CYBERSECURITY (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Technology > Cybersecurity",
        "Description": "The organization's capabilities and practices to protect systems, networks, data, and users from cyber threats, attacks, and breaches",
        "Business Drivers": "Risk Mitigation & Trust",
        "Business Drivers Description": "Cybersecurity protects: customer trust (breach = churn), revenue (ransomware/downtime), regulatory compliance, intellectual property, brand reputation, business continuity.",
        "Performance Factors": "Strong Security Posture",
        "Performance Factors Description": "Strong cybersecurity shows: zero successful breaches, defense-in-depth, security by design, regular testing (pentests), employee awareness, incident response plan, compliance (SOC 2, ISO 27001).",
        "Risk Factors": "Cyber Threats & Breaches",
        "Risk Factors Description": "Cybersecurity risks: data breaches ($4.45M avg cost), ransomware (business stoppage), IP theft, regulatory fines (GDPR up to 4% revenue), brand damage, customer churn.",
        "Metric": "Cybersecurity Posture Index",
        "Metric Description": "Composite of 4 sub-elements: Security Incidents + Vulnerability Management + Security Awareness + Compliance Certifications. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores. Strong security orgs score >85. Use security frameworks (NIST CSF, CIS Controls) for assessment."
    },

    # LEVEL 3: Cybersecurity Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Technology > Cybersecurity > Security Incidents",
        "Description": "The frequency and severity of cybersecurity incidents including breaches, malware infections, unauthorized access, and data loss events",
        "Business Drivers": "Breach Prevention",
        "Business Drivers Description": "Minimizing security incidents protects: customer data (trust/compliance), revenue (downtime/ransom), brand (breach = headline risk), IP (competitive advantage), shareholder value.",
        "Performance Factors": "Zero Successful Breaches",
        "Performance Factors Description": "Strong security shows: zero data breaches, zero ransomware successes, rapid detection (minutes), containment <1 hour, regular simulation exercises, lessons learned applied.",
        "Risk Factors": "Successful Attacks",
        "Risk Factors Description": "Security incidents cause: data breach costs ($4.45M avg), ransomware (business down days/weeks), customer churn (81% after breach), regulatory fines, class action lawsuits.",
        "Metric": "Security Incident Count",
        "Metric Description": "# of security incidents in past 12 months by severity: Critical (data breach, ransomware), High (unauthorized access), Medium (malware contained), Low (phishing attempts). Target: 0 critical/high.",
        "Unit": "Count by severity",
        "Target": "0 critical/high incidents",
        "Instructions": "Track all security incidents via SIEM/SOC. Classify by severity (NIST framework). Report monthly: count by severity, mean time to detect (MTTD), mean time to contain (MTTC)."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Cybersecurity > Vulnerability Management",
        "Description": "The processes and practices for identifying, assessing, prioritizing, and remediating security vulnerabilities in systems and applications",
        "Business Drivers": "Proactive Risk Reduction",
        "Business Drivers Description": "Vulnerability management prevents: exploitation of known flaws, breaches from unpatched systems, compliance violations, zero-day readiness (patch discipline).",
        "Performance Factors": "Rapid Vulnerability Remediation",
        "Performance Factors Description": "Strong vulnerability management shows: continuous scanning, critical vulns patched <7 days, high vulns <30 days, automated patching, regular pentests, bug bounty program.",
        "Risk Factors": "Unpatched Vulnerabilities",
        "Risk Factors Description": "Vulnerability backlogs risk: exploitation (most breaches exploit known vulns), compliance failures (PCI DSS requires patching), breach liability (negligence = higher fines).",
        "Metric": "Mean Time to Remediate (MTTR) Vulnerabilities",
        "Metric Description": "Average days from vulnerability discovery to remediation by severity. Target: Critical <7 days, High <30 days, Medium <90 days.",
        "Unit": "Days (by severity)",
        "Target": "Critical <7d, High <30d, Medium <90d",
        "Instructions": "Track vulnerability lifecycle: discovery → assessment → remediation. Calculate average days by severity level. Report monthly. Flag aged critical vulns (>7 days) for escalation."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Cybersecurity > Security Awareness",
        "Description": "The level of cybersecurity knowledge and vigilance among employees, measured by training completion and simulated phishing test results",
        "Business Drivers": "Human Firewall",
        "Business Drivers Description": "Security-aware employees prevent: phishing (90% of breaches start with phishing), social engineering, insider threats, credential compromise. 'Human firewall' is last line of defense.",
        "Performance Factors": "High Security Awareness",
        "Performance Factors Description": "Strong awareness shows: 100% annual training, phishing click rate <5%, proactive reporting (high report rate), security champions, culture of vigilance.",
        "Risk Factors": "Security Ignorance",
        "Risk Factors Description": "Low security awareness enables: phishing success (avg 32% click rate), social engineering, credential sharing, insider threats, breach likelihood (human error #1 cause).",
        "Metric": "Phishing Simulation Click Rate",
        "Metric Description": "% of employees who click links in simulated phishing tests. Industry avg: 32%. Best practice: <5%. Complement with training completion % and time-to-report rate.",
        "Unit": "Percentage (%)",
        "Target": "<5% click rate",
        "Instructions": "Run quarterly phishing simulations. Track: click rate, credential entry rate, report rate. Provide immediate training to clickers. Calculate trend over time. Target: declining trend to <5%."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Cybersecurity > Compliance Certifications",
        "Description": "The security and compliance certifications the organization has achieved, demonstrating adherence to recognized security standards and frameworks",
        "Business Drivers": "Trust & Market Access",
        "Business Drivers Description": "Security certifications enable: enterprise sales (SOC 2 required), regulatory compliance (HIPAA, PCI DSS), customer trust, insurance (cyber coverage), reduced audit burden.",
        "Performance Factors": "Relevant Certifications Current",
        "Performance Factors Description": "Strong compliance shows: SOC 2 Type II (SaaS), ISO 27001 (enterprise), industry-specific (HIPAA, PCI DSS), certifications current (annual audits), no findings.",
        "Risk Factors": "Certification Gaps",
        "Risk Factors Description": "Missing certifications limit: enterprise sales (blocked without SOC 2), regulatory compliance (fines), customer trust, market access, cyber insurance coverage (higher premiums).",
        "Metric": "Security Certification Coverage",
        "Metric Description": "Count of relevant security certifications held and current: SOC 2 Type II, ISO 27001, PCI DSS (if handle cards), HIPAA (if health data). Score based on relevance to business.",
        "Unit": "Count + Currency Status",
        "Target": "All relevant certs current, 0 findings",
        "Instructions": "List security certifications required for business (SOC 2, ISO 27001, industry-specific). Track status: current, expired, not pursued. Track audit findings. Report biannually."
    },

    # LEVEL 2: IT OPERATIONS (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Technology > IT Operations",
        "Description": "The processes, practices, and culture for delivering, monitoring, and supporting IT services including DevOps, ITIL, incident management, and service desk",
        "Business Drivers": "Operational Excellence",
        "Business Drivers Description": "Strong IT operations deliver: reliable services (uptime), rapid incident resolution (minimize business impact), efficient delivery (DevOps), continuous improvement, cost optimization.",
        "Performance Factors": "Mature IT Operations",
        "Performance Factors Description": "Strong IT ops show: DevOps practices (CI/CD), automated monitoring, rapid incident response (MTTR <30 min), high employee satisfaction (IT NPS >20), cost-efficient.",
        "Risk Factors": "Operational Failures & Inefficiency",
        "Risk Factors Description": "IT operations risks: prolonged outages (poor incident mgmt), slow delivery (no DevOps), high costs (manual processes), poor user experience (slow help desk).",
        "Metric": "IT Operations Excellence Index",
        "Metric Description": "Composite of 4 sub-elements: DevOps Maturity + Incident Management + Service Desk Performance + IT Operations Cost Efficiency. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores. Use ITIL/DevOps maturity models. Operational leaders score >80."
    },

    # LEVEL 3: IT Operations Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Operations > DevOps Maturity",
        "Description": "The degree to which DevOps practices are adopted including CI/CD, infrastructure as code, automated testing, and continuous monitoring",
        "Business Drivers": "Speed & Reliability",
        "Business Drivers Description": "DevOps enables: rapid delivery (weekly/daily releases vs quarterly), high quality (automated testing), operational stability (IaC, monitoring), innovation speed.",
        "Performance Factors": "Advanced DevOps Practices",
        "Performance Factors Description": "Mature DevOps shows: CI/CD pipelines, multiple deploys/day, infrastructure as code (IaC), automated testing >80% coverage, observability, blameless postmortems.",
        "Risk Factors": "Manual, Slow Delivery",
        "Risk Factors Description": "Low DevOps maturity causes: slow delivery (quarterly releases), high defect rates (no automated tests), manual toil (no automation), silos (dev vs ops conflict).",
        "Metric": "Deployment Frequency",
        "Metric Description": "# of production deployments per day/week. DORA metrics: Elite = multiple per day, High = weekly-monthly, Medium = monthly-biannually, Low = <biannually.",
        "Unit": "Deployments per time period",
        "Target": "Weekly or better (High/Elite)",
        "Instructions": "Track all production deployments. Calculate frequency (daily avg, weekly avg). DORA elite = multiple/day. Also track: lead time, MTTR, change fail rate."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Operations > Incident Management Effectiveness",
        "Description": "The speed and quality of response to IT incidents, measured by mean time to detect (MTTD) and mean time to resolve (MTTR)",
        "Business Drivers": "Business Continuity",
        "Business Drivers Description": "Fast incident resolution minimizes: business impact (revenue, productivity), customer impact (poor experience), reputational damage, SLA breaches, escalation costs.",
        "Performance Factors": "Rapid Incident Resolution",
        "Performance Factors Description": "Strong incident management shows: MTTD <15 min (automated monitoring), MTTR <30 min (critical), documented runbooks, blameless postmortems, continuous improvement.",
        "Risk Factors": "Slow Incident Response",
        "Risk Factors Description": "Poor incident management causes: prolonged outages (hours), business impact ($100k+ per hour), customer churn, SLA breaches (contractual penalties), brand damage.",
        "Metric": "Mean Time to Resolve (MTTR)",
        "Metric Description": "Average time from incident detection to resolution by severity. Target: Critical <30 min, High <2 hours, Medium <8 hours, Low <24 hours.",
        "Unit": "Minutes/Hours (by severity)",
        "Target": "Critical <30 min, High <2 hrs",
        "Instructions": "Track all incidents in ticketing system. Record: detection time, resolution time. Calculate MTTR by severity. Report monthly p50, p95. Also track MTTD (detection)."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Operations > Service Desk Performance",
        "Description": "The effectiveness of IT support services in resolving employee technology issues, measured by resolution time and employee satisfaction",
        "Business Drivers": "Employee Productivity",
        "Business Drivers Description": "Effective service desk maximizes: employee productivity (fast resolution), user satisfaction (good experience), cost efficiency (high first-call resolution), knowledge capture.",
        "Performance Factors": "High-Quality Support",
        "Performance Factors Description": "Strong service desk shows: first-call resolution >70%, average handle time <15 min, employee satisfaction >80%, self-service knowledge base, proactive outreach.",
        "Risk Factors": "Poor IT Support",
        "Risk Factors Description": "Weak service desk causes: productivity loss (long resolution times), employee frustration (poor experience), high costs (escalations), repeated issues (no knowledge capture).",
        "Metric": "First-Call Resolution Rate",
        "Metric Description": "% of IT support tickets resolved on first contact without escalation. Benchmark: <60% = poor, 60-75% = fair, >75% = good, >85% = excellent.",
        "Unit": "Percentage (%)",
        "Target": ">75%",
        "Instructions": "Track all service desk tickets. Flag tickets requiring escalation or follow-up. Calculate % resolved on first contact. Monthly reporting. Also track employee satisfaction (CSAT)."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > IT Operations > IT Operations Cost Efficiency",
        "Description": "The cost-effectiveness of IT operations relative to industry benchmarks and business value delivered, measured by IT spend as percentage of revenue",
        "Business Drivers": "Cost Optimization",
        "Business Drivers Description": "IT cost efficiency ensures: competitive cost structure (not overspending), value delivery (aligned to business priorities), investment capacity (not all spent on ops), stakeholder confidence.",
        "Performance Factors": "Efficient IT Spend",
        "Performance Factors Description": "Cost-efficient IT shows: spend 3-8% of revenue (by industry), cloud cost optimization, automation (reduce manual toil), vendor management, demand management.",
        "Risk Factors": "IT Cost Overruns",
        "Risk Factors Description": "High IT costs (>10% revenue) limit: investment capacity (all spent on operations), competitiveness (cost disadvantage), profitability, strategic flexibility.",
        "Metric": "IT Operating Spend as % of Revenue",
        "Metric Description": "Annual IT operating expenses (excluding one-time projects) / annual revenue. Benchmark varies by industry: 3-5% (manufacturing), 6-8% (services), 8-12% (tech).",
        "Unit": "Percentage (% of revenue)",
        "Target": "Within industry benchmark range",
        "Instructions": "Calculate annual IT operating expenses: salaries, infrastructure, software licenses, support, excludes one-time projects. Divide by annual revenue. Compare to industry benchmark."
    },

    # LEVEL 2: TECHNOLOGY INNOVATION (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Technology > Technology Innovation",
        "Description": "The organization's capability to evaluate, adopt, and leverage emerging technologies to create competitive advantage and enable new business models",
        "Business Drivers": "Competitive Advantage & Transformation",
        "Business Drivers Description": "Technology innovation enables: competitive differentiation, new business models (digital products), efficiency gains (automation), customer experience, market leadership.",
        "Performance Factors": "Active Innovation Pipeline",
        "Performance Factors Description": "Strong tech innovation shows: dedicated innovation budget (5-10% IT), emerging tech experiments (AI, blockchain, IoT), innovation governance, business outcomes delivered.",
        "Risk Factors": "Innovation Stagnation",
        "Risk Factors Description": "Lack of tech innovation risks: competitive disadvantage (competitors innovate), disruption vulnerability, missed opportunities, talent loss (bored by stagnation).",
        "Metric": "Technology Innovation Index",
        "Metric Description": "Composite of 4 sub-elements: Innovation Investment + Emerging Tech Adoption + Innovation Pipeline + Innovation ROI. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining investment data, adoption assessments, and business impact. Innovation leaders score >75."
    },

    # LEVEL 3: Technology Innovation Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Technology > Technology Innovation > Innovation Investment",
        "Description": "The percentage of IT budget allocated to exploring and implementing new technologies and innovative solutions vs maintaining existing systems",
        "Business Drivers": "Innovation Capacity",
        "Business Drivers Description": "Innovation investment funds: emerging tech experiments, proof-of-concepts, innovation lab, strategic bets, competitive positioning. Without investment, innovation is just talk.",
        "Performance Factors": "Meaningful Innovation Budget",
        "Performance Factors Description": "Strong innovation investment shows: 5-10% IT budget on innovation, dedicated innovation team, time allocation (20% time), VC-style portfolio approach (fail fast).",
        "Risk Factors": "Zero Innovation Investment",
        "Risk Factors Description": "No innovation budget signals: 100% spent on Run (lights-on), no capacity for new, falling behind competition, inability to explore emerging tech, stagnation.",
        "Metric": "Innovation Investment as % of IT Budget",
        "Metric Description": "Annual spending on innovation initiatives (emerging tech, experiments, POCs) / total annual IT budget. Benchmark: <2% = low, 2-5% = fair, 5-10% = strong, >10% = aggressive.",
        "Unit": "Percentage (% of IT budget)",
        "Target": "5-10%",
        "Instructions": "Track IT spending. Classify as: Run (BAU, maintenance), Grow (scaling existing), Transform (innovation, new capabilities). Calculate Transform % of total. Annual tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Technology Innovation > Emerging Technology Adoption",
        "Description": "The organization's pace of evaluating and adopting emerging technologies like AI/ML, blockchain, IoT, quantum computing, AR/VR relative to industry",
        "Business Drivers": "Competitive Positioning",
        "Business Drivers Description": "Early emerging tech adoption enables: competitive advantage (first-mover), learning curve head start, talent attraction (work on cutting edge), strategic optionality.",
        "Performance Factors": "Fast Follower or Leader",
        "Performance Factors Description": "Strong emerging tech adoption shows: active experiments with 3+ emerging technologies, production deployments (AI/ML, IoT), dedicated innovation lab, external partnerships.",
        "Risk Factors": "Late Adopter",
        "Risk Factors Description": "Slow emerging tech adoption risks: competitive disadvantage (late to AI), missed opportunities (first-mover advantages lost), talent loss (want to work with new tech).",
        "Metric": "Emerging Technology Maturity Score",
        "Metric Description": "Count and maturity of emerging tech initiatives: AI/ML, blockchain, IoT, edge computing, quantum. Score: None = 0, Exploring = 20, Piloting = 50, Production = 100. Average across 5 tech areas.",
        "Unit": "Score (0-100)",
        "Target": ">50 (multiple pilots or production)",
        "Instructions": "Assess maturity for 5 emerging tech categories: AI/ML, blockchain, IoT, edge, quantum. Rate each: Not exploring, Exploring, Piloting, Production. Weight production highest."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Technology Innovation > Innovation Pipeline Health",
        "Description": "The quantity and quality of technology innovation initiatives in the pipeline from ideation through experimentation to production deployment",
        "Business Drivers": "Future Capabilities",
        "Business Drivers Description": "Healthy innovation pipeline ensures: continuous flow of new capabilities, portfolio approach (multiple bets), stage-gate discipline, business outcomes focus, learning from failures.",
        "Performance Factors": "Active Innovation Pipeline",
        "Performance Factors Description": "Strong pipeline shows: >10 active experiments, stage-gate process, clear success criteria, business sponsor for each, 10-20% graduate to production, fast fail on rest.",
        "Risk Factors": "Empty Pipeline",
        "Risk Factors Description": "Weak pipeline signals: no experimentation, all innovation talk no action, risk aversion (no failures), stagnation, future capability gaps.",
        "Metric": "Active Innovation Projects Count",
        "Metric Description": "# of active technology innovation projects (experiments, POCs, pilots) at any time. Normalize by org size: >5 per 500 employees. Track by stage: ideation, experiment, pilot, production.",
        "Unit": "Count (normalized)",
        "Target": ">5 per 500 employees",
        "Instructions": "Inventory all innovation projects. Classify by stage: ideation, experiment, pilot, production. Count active projects (in-flight). Calculate per 500 employees. Quarterly tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "Technology > Technology Innovation > Innovation ROI",
        "Description": "The business value and return on investment delivered by technology innovation initiatives, measured by measurable business outcomes",
        "Business Drivers": "Innovation Effectiveness",
        "Business Drivers Description": "Innovation ROI ensures: resources well-spent (not innovation theater), business outcomes delivered (not just tech for tech's sake), credibility for future investment, strategic impact.",
        "Performance Factors": "Proven Business Value",
        "Performance Factors Description": "Strong innovation ROI shows: >50% of pilots deliver measurable value, documented business cases, financial metrics (revenue, cost savings, efficiency), innovation pays for itself.",
        "Risk Factors": "Innovation Theater",
        "Risk Factors Description": "Low innovation ROI signals: no business outcomes (science projects), innovation theater (PR not substance), wasted investment, credibility loss, future funding cuts.",
        "Metric": "Innovation Success Rate",
        "Metric Description": "% of innovation projects that graduate to production AND deliver measurable business value (revenue, cost savings, KPI improvement). Target: 10-20% of experiments (venture-like).",
        "Unit": "Percentage (%)",
        "Target": "10-20% of experiments succeed",
        "Instructions": "Track all innovation projects to conclusion: killed, failed, or succeeded (production + business value). Calculate % succeeded. Healthy portfolio: 10-20% succeed, 80-90% fail fast."
    }
]
