"""
Change Dimension Data - EXECUTION Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

change_data = [
    # LEVEL 1: CHANGE DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Change",
        "Description": "The organization's capability to successfully plan, lead, and execute changes including strategic initiatives, transformations, and continuous improvement",
        "Business Drivers": "Agility & Execution",
        "Business Drivers Description": "Change capability enables: strategy execution (initiatives delivered), adaptation (respond to disruption), transformation (business model evolution), competitive positioning, growth.",
        "Performance Factors": "High Change Success Rate",
        "Performance Factors Description": "Strong change capability shows: >70% change success rate, stakeholder alignment, effective communication, adoption achieved, benefits realized, change-ready culture.",
        "Risk Factors": "Change Failure & Fatigue",
        "Risk Factors Description": "Change risks include: initiative failures (70% fail per Kotter), change fatigue (too many changes), resistance, failed transformations, wasted investment, talent loss.",
        "Metric": "Overall Change Effectiveness Score",
        "Metric Description": "Composite index of 6 element scores: Change Capability + Change Leadership + Stakeholder Engagement + Communication + Adoption & Sustainment + Change Performance. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70 (effective change capability)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Change leaders score >80. Weight by strategic priority of change portfolio."
    },

    # LEVEL 2: CHANGE CAPABILITY (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Change > Change Capability",
        "Description": "The organizational maturity, methodologies, tools, and practices for managing change including change management frameworks and resources",
        "Business Drivers": "Change Readiness",
        "Business Drivers Description": "Change capability provides: consistent methodology (repeatable success), trained practitioners, tools and templates, lessons learned, portfolio management, change readiness.",
        "Performance Factors": "Mature Change Capability",
        "Performance Factors Description": "Strong change capability: standardized methodology (Prosci, Kotter, etc), trained change managers, change management office (CMO), tools/templates, portfolio visibility.",
        "Risk Factors": "Ad-Hoc Change Approach",
        "Risk Factors Description": "Weak change capability causes: inconsistent approaches (random success), no methodology, untrained practitioners, repeated mistakes, change chaos.",
        "Metric": "Change Capability Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Methodology Maturity + Change Resources + Change Tools + Portfolio Management. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining methodology assessment, resource inventory, tools evaluation, and portfolio management maturity."
    },

    # LEVEL 3: Change Capability Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Change > Change Capability > Methodology Maturity",
        "Description": "The extent to which the organization has adopted and embedded a standard change management methodology with defined phases, activities, and deliverables",
        "Business Drivers": "Repeatable Success",
        "Business Drivers Description": "Standard methodology ensures: repeatable success (not random), consistent approach, knowledge capture, practitioner guidance, stakeholder confidence, scaling capability.",
        "Performance Factors": "Embedded Methodology",
        "Performance Factors Description": "Mature methodology: standard framework adopted (Prosci ADKAR, Kotter 8-steps, etc), documented process, templates available, training provided, compliance measured.",
        "Risk Factors": "No Standard Approach",
        "Risk Factors Description": "Lack of methodology causes: ad-hoc approaches, inconsistent results, inability to scale, repeated mistakes, knowledge loss, low success rates.",
        "Metric": "Change Methodology Maturity Level",
        "Metric Description": "Maturity assessment (1-5): 1=Ad-hoc, 2=Defined, 3=Managed, 4=Integrated, 5=Optimized. Assess: methodology adoption, documentation, training, compliance, improvement.",
        "Unit": "Level (1-5)",
        "Target": "Level 4 (Integrated)",
        "Instructions": "Assess change management maturity: methodology documented?, training provided?, consistently applied?, integrated to project management?, continuous improvement? Score 1-5."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Capability > Change Resources",
        "Description": "The availability of dedicated change management professionals including change managers, change network, and organizational change management (OCM) office",
        "Business Drivers": "Capacity & Expertise",
        "Business Drivers Description": "Dedicated change resources provide: expert guidance, capacity for portfolio, consistent application, knowledge building, coaching, change network activation.",
        "Performance Factors": "Adequate Change Staffing",
        "Performance Factors Description": "Strong resourcing: dedicated change managers (1 per 3-5 major initiatives), change management office (CMO), change agent network, external expertise when needed.",
        "Risk Factors": "No Change Resources",
        "Risk Factors Description": "Lack of resources causes: changes under-resourced, project managers do change (untrained), inconsistent application, overwhelmed capacity, failed changes.",
        "Metric": "Change Manager to Initiative Ratio",
        "Metric Description": "# of dedicated change management FTEs / # of active major change initiatives. Benchmark: 1 change manager per 3-5 major initiatives. <1 per 10 = under-resourced.",
        "Unit": "Ratio",
        "Target": "1 change manager per 3-5 initiatives",
        "Instructions": "Count dedicated change management FTEs (full-time equivalent). Count active major change initiatives (>$500k, strategic). Calculate ratio. <1 per 10 indicates under-resourcing."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Capability > Change Tools",
        "Description": "The availability and utilization of change management tools including impact assessment, readiness assessment, stakeholder analysis, and adoption tracking",
        "Business Drivers": "Effectiveness & Efficiency",
        "Business Drivers Description": "Change tools enable: structured analysis (impact, readiness, stakeholders), consistent quality, data-driven decisions, tracking progress, efficiency (templates), lessons capture.",
        "Performance Factors": "Comprehensive Tool Set",
        "Performance Factors Description": "Strong tools: impact assessment, readiness assessment, stakeholder analysis, resistance management, adoption tracking, communications planning, training effectiveness.",
        "Risk Factors": "No Change Tools",
        "Risk Factors Description": "Lack of tools causes: subjective assessments, missed impacts, stakeholder surprises, no adoption tracking, inability to demonstrate value, reinventing wheel.",
        "Metric": "Change Tools Availability & Usage",
        "Metric Description": "# of standard change tools available (impact, readiness, stakeholder, resistance, adoption, comms) and % of changes using tools. Target: 6+ tools available, >80% usage.",
        "Unit": "Count + Percentage",
        "Target": "6+ tools, >80% usage rate",
        "Instructions": "Inventory change management tools/templates. Count available tools. Survey change practitioners on tool usage. Calculate % of initiatives using standard tools."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Capability > Portfolio Management",
        "Description": "The visibility and active management of the portfolio of change initiatives including prioritization, sequencing, and capacity management",
        "Business Drivers": "Change Overload Prevention",
        "Business Drivers Description": "Portfolio management prevents: change overload (too many changes), conflicting changes, capacity constraints, change fatigue, initiative failures due to resource conflicts.",
        "Performance Factors": "Active Portfolio Management",
        "Performance Factors Description": "Strong portfolio mgmt: portfolio visibility (dashboard), prioritization process, sequencing logic, capacity analysis, change saturation monitoring, governance.",
        "Risk Factors": "Change Portfolio Chaos",
        "Risk Factors Description": "No portfolio management causes: change overload, initiative conflicts, resource battles, change fatigue, widespread failures, no prioritization (everything priority 1).",
        "Metric": "Change Portfolio Visibility Score",
        "Metric Description": "Assessment of portfolio management maturity: portfolio tracked (Y/N), prioritization process (Y/N), capacity management (Y/N), dashboard (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (strong portfolio management)",
        "Instructions": "Assess change portfolio management: Is portfolio tracked? Prioritization process exists? Capacity analyzed? Dashboard/reporting? Score each dimension, weight, composite."
    },

    # LEVEL 2: CHANGE LEADERSHIP (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Change > Change Leadership",
        "Description": "The visible sponsorship, commitment, and leadership behaviors demonstrated by executives and managers in driving and modeling change",
        "Business Drivers": "Change Success",
        "Business Drivers Description": "Change leadership is #1 success factor (Prosci research): visible sponsorship, commitment, resources, decision-making, barrier removal, role modeling, accountability.",
        "Performance Factors": "Active, Visible Leadership",
        "Performance Factors Description": "Strong change leadership: active executive sponsors, visible participation, resources committed, barriers removed, role modeling new behaviors, holding teams accountable.",
        "Risk Factors": "Absent Leadership",
        "Risk Factors Description": "Weak leadership is #1 failure factor: absent sponsors, no commitment, under-resourced, indecision, barriers not removed, 'do as I say not as I do'.",
        "Metric": "Change Leadership Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Sponsor Engagement + Leadership Commitment + Change Capability Building + Resistance Management. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining sponsor assessments, commitment indicators, capability data, and resistance handling effectiveness."
    },

    # LEVEL 3: Change Leadership Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Change > Change Leadership > Sponsor Engagement",
        "Description": "The level of active engagement and visible participation of executive sponsors throughout the change journey",
        "Business Drivers": "Credibility & Priority",
        "Business Drivers Description": "Active sponsors signal: change is priority, commitment is real, resources will come, barriers will be removed, organization is serious. Prosci: #1 success factor.",
        "Performance Factors": "Highly Engaged Sponsors",
        "Performance Factors Description": "Strong sponsor engagement: regular participation (weekly updates), visible communications, town halls, barrier removal, decision-making, hold leaders accountable.",
        "Risk Factors": "Absent Sponsors",
        "Risk Factors Description": "Absent sponsors cause: change deprioritized, 'flavor of the month', resource starvation, barriers persist, middle management resistance, initiative failure.",
        "Metric": "Sponsor Engagement Score",
        "Metric Description": "Assessment of sponsor activities: regular meetings (Y/N), communications (Y/N), visible participation (Y/N), barrier removal (Y/N), accountability (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly engaged)",
        "Instructions": "For each major change, assess sponsor engagement across 5 dimensions: meetings, communications, visible participation, barriers removed, accountability held. Score each, average."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Leadership > Leadership Commitment",
        "Description": "The demonstrated commitment of leadership team through resource allocation, prioritization, and sustained focus despite competing demands",
        "Business Drivers": "Resource Enablement",
        "Business Drivers Description": "Leadership commitment provides: adequate resources (people, budget, time), protection from competing priorities, sustained focus (not flavor of month), credibility.",
        "Performance Factors": "Visible Commitment",
        "Performance Factors Description": "Strong commitment: resources allocated, protected time, priority status maintained, competing priorities managed, long-term focus, walk the talk.",
        "Risk Factors": "Lip Service",
        "Risk Factors Description": "Lack of commitment shows: under-resourced, cut first when pressure, conflicting priorities, 'initiative of the month', actions contradict words, cynicism.",
        "Metric": "Leadership Commitment Score",
        "Metric Description": "Survey middle managers and change practitioners: 'Senior leadership demonstrates sustained commitment to this change.' 5-point Likert. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in change pulse surveys. Ask middle managers and change team about leadership commitment perception. Calculate % favorable. <60% signals commitment gap."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Leadership > Change Capability Building",
        "Description": "The investment leaders make in building organization-wide change capability through training, coaching, and capability development",
        "Business Drivers": "Sustainable Change Capacity",
        "Business Drivers Description": "Capability building enables: sustainable change capacity (not consultant-dependent), embedded skills, change-ready organization, continuous improvement, competitive advantage.",
        "Performance Factors": "Systematic Capability Building",
        "Performance Factors Description": "Strong capability building: manager change training, change agent network, coaching provided, communities of practice, lessons learned, knowledge management.",
        "Risk Factors": "No Capability Investment",
        "Risk Factors Description": "No capability building causes: consultant dependence, repeated mistakes, low change maturity, resistance, inability to scale change, competitive disadvantage.",
        "Metric": "Manager Change Training Coverage",
        "Metric Description": "% of people managers who have completed change management training (fundamentals, leading change through transition). Target: >70% of managers trained.",
        "Unit": "Percentage (%)",
        "Target": ">70% of managers trained",
        "Instructions": "Track manager completion of change management training. Calculate % of total managers trained. Leaders invest in capability: >70% coverage."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Leadership > Resistance Management",
        "Description": "The proactive identification, understanding, and management of resistance including addressing root causes and supporting resisters through transition",
        "Business Drivers": "Change Acceleration",
        "Business Drivers Description": "Resistance management accelerates: change adoption (address blockers), reduces failure risk, maintains momentum, preserves relationships, identifies valid concerns.",
        "Performance Factors": "Proactive Resistance Management",
        "Performance Factors Description": "Strong resistance management: early identification, root cause analysis, tailored strategies, influential resisters addressed, concerns validated, support provided.",
        "Risk Factors": "Ignoring Resistance",
        "Risk Factors Description": "Ignoring resistance causes: change failure (resistance wins), momentum loss, talent loss (resisters leave), valid concerns missed, passive-aggressive behavior.",
        "Metric": "Resistance Management Effectiveness",
        "Metric Description": "% of identified resistance concerns that were addressed with documented response/action. Target: >80% of resistance concerns addressed.",
        "Unit": "Percentage (%)",
        "Target": ">80% concerns addressed",
        "Instructions": "Track resistance concerns identified (surveys, feedback, stakeholder analysis). Document actions taken to address. Calculate % with documented response. Proactive management >80%."
    },

    # LEVEL 2: STAKEHOLDER ENGAGEMENT (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Change > Stakeholder Engagement",
        "Description": "The systematic identification, analysis, and engagement of stakeholders affected by change to build support and manage resistance",
        "Business Drivers": "Alignment & Support",
        "Business Drivers Description": "Stakeholder engagement builds: alignment (shared understanding), support (advocates), feedback (course correction), trust (involvement), adoption (buy-in).",
        "Performance Factors": "Comprehensive Engagement",
        "Performance Factors Description": "Strong stakeholder engagement: systematic analysis (impact, influence, attitude), tailored strategies, two-way dialogue, feedback incorporated, coalition building.",
        "Risk Factors": "Stakeholder Neglect",
        "Risk Factors Description": "Poor stakeholder engagement causes: surprises, resistance, misalignment, lack of support, change failure, relationship damage, adoption failure.",
        "Metric": "Stakeholder Engagement Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Stakeholder Analysis + Engagement Planning + Feedback Incorporation + Coalition Building. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining analysis completeness, planning rigor, feedback data, and coalition metrics."
    },

    # LEVEL 3: Stakeholder Engagement Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Change > Stakeholder Engagement > Stakeholder Analysis",
        "Description": "The rigor and completeness of stakeholder identification and analysis including impact assessment, influence mapping, and attitude evaluation",
        "Business Drivers": "Targeted Engagement",
        "Business Drivers Description": "Stakeholder analysis enables: complete identification (no surprises), impact understanding, influence mapping (key players), attitude baseline (support/neutral/resist), tailored strategies.",
        "Performance Factors": "Comprehensive Analysis",
        "Performance Factors Description": "Strong analysis: all stakeholders identified, impact assessed (high/medium/low), influence mapped, attitudes evaluated, segmentation for tailored approach.",
        "Risk Factors": "Incomplete Analysis",
        "Risk Factors Description": "Poor analysis causes: stakeholder surprises (missed key players), wrong strategies (one-size-fits-all), resistance not anticipated, influencer misses.",
        "Metric": "Stakeholder Analysis Completeness",
        "Metric Description": "% of major changes with documented stakeholder analysis covering: identification, impact, influence, attitude. Target: 100% of major changes.",
        "Unit": "Percentage (%)",
        "Target": "100% of major changes",
        "Instructions": "For each major change, check for stakeholder analysis documentation: stakeholders identified?, impact assessed?, influence mapped?, attitudes evaluated? Calculate % with complete analysis."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Stakeholder Engagement > Engagement Planning",
        "Description": "The quality and detail of stakeholder engagement plans including tailored strategies, touchpoints, and feedback mechanisms for each stakeholder group",
        "Business Drivers": "Engagement Effectiveness",
        "Business Drivers Description": "Engagement planning ensures: tailored approaches (not one-size-fits-all), sufficient touchpoints, feedback loops, resource efficiency, measurable progress.",
        "Performance Factors": "Tailored Engagement Plans",
        "Performance Factors Description": "Strong planning: segmented strategies (by impact/influence/attitude), planned touchpoints, feedback mechanisms, responsibility assigned, progress tracking.",
        "Risk Factors": "Generic Engagement",
        "Risk Factors Description": "Weak planning causes: one-size-fits-all (ineffective), insufficient touchpoints, no feedback loops, ad-hoc engagement, missed opportunities.",
        "Metric": "Engagement Plan Quality Score",
        "Metric Description": "Assessment of engagement plans: segmented strategies (Y/N), touchpoints planned (Y/N), feedback mechanisms (Y/N), tracked (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (quality plans)",
        "Instructions": "Review stakeholder engagement plans for major changes. Score on: segmentation, touchpoint planning, feedback mechanisms, tracking. Average across changes."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Stakeholder Engagement > Feedback Incorporation",
        "Description": "The extent to which stakeholder feedback is actively solicited, captured, considered, and incorporated into change design and execution",
        "Business Drivers": "Change Quality & Acceptance",
        "Business Drivers Description": "Incorporating feedback improves: change quality (stakeholder insights), acceptance (voice heard), course correction (early issues), trust (responsive), adoption.",
        "Performance Factors": "Active Feedback Loop",
        "Performance Factors Description": "Strong feedback incorporation: regularly solicited (surveys, forums), systematically captured, visibly considered, changes made (when valid), close-the-loop communication.",
        "Risk Factors": "Feedback Ignored",
        "Risk Factors Description": "Ignoring feedback causes: missed insights, resistance ('they don't listen'), sub-optimal solutions, trust erosion, low engagement in future.",
        "Metric": "Feedback Incorporation Rate",
        "Metric Description": "% of stakeholder feedback themes that resulted in documented consideration and response (change made or explanation provided). Target: >70% themes addressed.",
        "Unit": "Percentage (%)",
        "Target": ">70% feedback themes addressed",
        "Instructions": "Track stakeholder feedback by theme. Document response: change made, explanation provided, or rationale for no change. Calculate % themes with documented response."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Stakeholder Engagement > Coalition Building",
        "Description": "The systematic development of a coalition of supporters and change agents across the organization to advocate for and accelerate change",
        "Business Drivers": "Change Momentum",
        "Business Drivers Description": "Coalition building creates: peer influence (more powerful than top-down), distributed advocacy, grassroots momentum, social proof, resistance management (peer pressure).",
        "Performance Factors": "Active Change Network",
        "Performance Factors Description": "Strong coalition: change agent network established, influencers recruited, peer advocates active, grassroots momentum, stories shared, social proof visible.",
        "Risk Factors": "Top-Down Only",
        "Risk Factors Description": "No coalition causes: top-down only (less effective), lack of peer influence, slow adoption, resistance unchallenged, 'management fad' perception.",
        "Metric": "Change Agent Network Size",
        "Metric Description": "# of active change agents / 100 employees. Active = trained, engaged, advocating. Benchmark: 2-5 change agents per 100 employees is strong.",
        "Unit": "Count per 100 employees",
        "Target": ">2 per 100 employees",
        "Instructions": "Count change agents (trained, active, advocating). Normalize by employee count (per 100). Strong coalition: >2 per 100. Track activation rate and engagement."
    },

    # LEVEL 2: COMMUNICATION (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Change > Communication",
        "Description": "The quality, frequency, and effectiveness of change communications across channels to inform, engage, and motivate stakeholders",
        "Business Drivers": "Awareness & Understanding",
        "Business Drivers Description": "Change communication drives: awareness (what's changing), understanding (why, what's in it for me), engagement (two-way dialogue), commitment, adoption preparation.",
        "Performance Factors": "Effective Communication",
        "Performance Factors Description": "Strong communication: clear messaging (why, what, when, how), multi-channel, frequent updates, two-way dialogue, tailored by audience, leaders deliver key messages.",
        "Risk Factors": "Communication Gaps",
        "Risk Factors Description": "Poor communication causes: rumors fill vacuum, misunderstanding, resistance, low awareness, confusion, anxiety, 'mushroom management' (kept in dark).",
        "Metric": "Communication Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Message Clarity + Communication Frequency + Channel Effectiveness + Two-Way Dialogue. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining message assessment, frequency tracking, channel analysis, and dialogue metrics."
    },

    # LEVEL 3: Communication Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Change > Communication > Message Clarity",
        "Description": "The clarity, consistency, and completeness of change messages addressing why change is happening, what's changing, and what it means for stakeholders",
        "Business Drivers": "Understanding",
        "Business Drivers Description": "Clear messages ensure: shared understanding, reduced confusion, ability to explain to others, credibility, reduced rumors, readiness preparation.",
        "Performance Factors": "Clear, Consistent Messages",
        "Performance Factors Description": "Strong message clarity: why (burning platform), what (specifics), when (timeline), how (process), WIIFM (what's in it for me), consistent across messengers.",
        "Risk Factors": "Message Confusion",
        "Risk Factors Description": "Unclear messages cause: confusion ('what are they talking about?'), inconsistency (mixed messages), inability to prepare, rumors, resistance.",
        "Metric": "Message Clarity Score",
        "Metric Description": "Survey stakeholders: 'I clearly understand why this change is happening and what it means for me.' 5-point Likert. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in change pulse surveys. Measure understanding of: why changing, what's changing, impact on me, timing. Calculate % favorable. <70% = clarity gap."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Communication > Communication Frequency",
        "Description": "The regularity and timeliness of change communications ensuring stakeholders receive updates frequently enough to stay informed and engaged",
        "Business Drivers": "Engagement & Momentum",
        "Business Drivers Description": "Frequent communication maintains: awareness (top of mind), engagement (not forgotten), momentum (progress visible), trust (transparency), anxiety reduction.",
        "Performance Factors": "Regular, Timely Updates",
        "Performance Factors Description": "Strong frequency: weekly updates during active change, milestone communications, no long silences, proactive (not reactive), predictable cadence.",
        "Risk Factors": "Communication Gaps",
        "Risk Factors Description": "Infrequent communication causes: momentum loss, 'what happened to that?', rumors fill vacuum, disengagement, anxiety, surprise resistance.",
        "Metric": "Communication Cadence",
        "Metric Description": "Average # of change communications per month during active change phase. Benchmark: Weekly (4/month) during active change, monthly in sustainment.",
        "Unit": "Communications per month",
        "Target": ">4 per month during active change",
        "Instructions": "Track all change communications (emails, town halls, newsletters, updates). Count per month. During active change: target weekly (4/month). Long gaps (>4 weeks) = problem."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Communication > Channel Effectiveness",
        "Description": "The appropriateness and reach of communication channels used to ensure messages reach all stakeholders through preferred and accessible channels",
        "Business Drivers": "Reach & Impact",
        "Business Drivers Description": "Effective channels ensure: message reaches everyone, multiple touchpoints (repetition), channel preferences honored, accessible (frontline workers), credible messengers.",
        "Performance Factors": "Multi-Channel Approach",
        "Performance Factors Description": "Strong channels: multiple channels (email, town halls, team meetings, video, intranet), managers cascade, executive communications, informal channels, accessible formats.",
        "Risk Factors": "Single-Channel or Wrong Channels",
        "Risk Factors Description": "Poor channels cause: missed stakeholders (email-only misses frontline), low reach, wrong messengers, inaccessible formats, 'I never heard about it'.",
        "Metric": "Communication Reach Rate",
        "Metric Description": "% of target stakeholders who received and viewed key change communications. Track via email open rates, meeting attendance, intranet views. Target: >85% reach.",
        "Unit": "Percentage (%)",
        "Target": ">85% reach",
        "Instructions": "Track communication metrics: email open rates, meeting attendance, intranet views, survey awareness. Calculate composite reach across channels. Multi-channel increases reach."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Communication > Two-Way Dialogue",
        "Description": "The extent to which communication is two-way with opportunities for stakeholders to ask questions, provide feedback, and engage in dialogue",
        "Business Drivers": "Engagement & Trust",
        "Business Drivers Description": "Two-way dialogue enables: questions answered (reduce confusion), concerns heard (feel valued), feedback incorporated, trust built, resistance surfaced early.",
        "Performance Factors": "Active Dialogue",
        "Performance Factors Description": "Strong two-way dialogue: Q&A sessions, feedback mechanisms (surveys, forums), town halls with open mic, listening tours, manager cascades with discussion.",
        "Risk Factors": "One-Way Broadcasting",
        "Risk Factors Description": "One-way only causes: unanswered questions, no feedback, 'they don't listen', passive recipients, resistance goes underground, trust erosion.",
        "Metric": "Two-Way Dialogue Engagement",
        "Metric Description": "% of stakeholders who participated in two-way dialogue activities (Q&A, feedback, forums, discussions) in past month. Target: >40% participation.",
        "Unit": "Percentage (%)",
        "Target": ">40% stakeholder participation",
        "Instructions": "Track participation in dialogue activities: Q&A attendance, survey completion, forum posts, discussion participation. Calculate % of stakeholders engaged. Strong: >40%."
    },

    # LEVEL 2: ADOPTION & SUSTAINMENT (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Change > Adoption & Sustainment",
        "Description": "The practices and mechanisms for driving adoption of new behaviors, processes, or systems and sustaining changes to prevent reversion",
        "Business Drivers": "Value Realization",
        "Business Drivers Description": "Adoption & sustainment deliver: value realization (benefits captured), return on investment, capability building, competitive advantage, permanent improvement.",
        "Performance Factors": "High Adoption & Sustained",
        "Performance Factors Description": "Strong adoption: >80% utilization of new ways, proficiency achieved, sustainment mechanisms in place (reinforcement, measurement, accountability), no reversion.",
        "Risk Factors": "Low Adoption or Reversion",
        "Risk Factors Description": "Adoption failures cause: value not realized, ROI missed, reversion to old ways (change didn't stick), wasted investment, cynicism about future changes.",
        "Metric": "Adoption & Sustainment Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Training Effectiveness + Utilization Rate + Proficiency Achievement + Reinforcement Mechanisms. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining training data, usage metrics, proficiency assessments, and sustainment mechanism evaluation."
    },

    # LEVEL 3: Adoption & Sustainment Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Change > Adoption & Sustainment > Training Effectiveness",
        "Description": "The quality and impact of training programs designed to build skills and knowledge required for successful adoption of change",
        "Business Drivers": "Capability Building",
        "Business Drivers Description": "Effective training provides: skills to adopt change (capability), confidence (self-efficacy), readiness, reduced errors, faster proficiency, positive experience.",
        "Performance Factors": "High-Quality Training",
        "Performance Factors Description": "Strong training: needs-based (job-specific), hands-on practice, just-in-time, support available, effectiveness measured (knowledge + application), high satisfaction.",
        "Risk Factors": "Training Gaps",
        "Risk Factors Description": "Poor training causes: inability to adopt (lack skills), errors, frustration, low confidence, resistance, workarounds (don't know proper way), adoption failure.",
        "Metric": "Training Effectiveness Score",
        "Metric Description": "Composite of training completion rate (>90%) + knowledge assessment pass rate (>85%) + training satisfaction (>4.0/5). Weight and average.",
        "Unit": "Score (0-100)",
        "Target": ">85",
        "Instructions": "Track training metrics: completion % (target >90%), assessment pass % (target >85%), satisfaction score (target >4.0/5). Calculate weighted composite."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Adoption & Sustainment > Utilization Rate",
        "Description": "The extent to which target users are actively using new processes, systems, or behaviors as intended versus workarounds or old ways",
        "Business Drivers": "Value Realization",
        "Business Drivers Description": "High utilization ensures: value realized (used as intended), ROI achieved, compliance maintained, efficiency gains captured, benefits flow.",
        "Performance Factors": "High Utilization",
        "Performance Factors Description": "Strong utilization: >80% of target users actively using, compliance to new process high, workarounds minimal, system usage data confirms, observational validation.",
        "Risk Factors": "Low Utilization",
        "Risk Factors Description": "Low utilization causes: value not realized, wasted investment, workarounds persist, compliance issues, ROI missed, reversion signals.",
        "Metric": "New Process/System Utilization Rate",
        "Metric Description": "% of target users actively using new process/system/behavior as measured by system data, compliance audits, or observational assessment. Target: >80%.",
        "Unit": "Percentage (%)",
        "Target": ">80% utilization",
        "Instructions": "Measure utilization via: system usage logs (logins, transactions), process compliance audits, observational assessments. Calculate % of target users actively using. >80% = strong adoption."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Adoption & Sustainment > Proficiency Achievement",
        "Description": "The speed and extent to which users achieve proficient performance levels with new processes, systems, or behaviors",
        "Business Drivers": "Performance Delivery",
        "Business Drivers Description": "Proficiency achievement delivers: full performance (productivity), quality outputs, confidence, reduced support needs, value realization, competitive performance.",
        "Performance Factors": "Rapid Proficiency",
        "Performance Factors Description": "Strong proficiency: users reach proficiency <90 days, performance metrics meet targets, error rates low, support needs decline, self-sufficient.",
        "Risk Factors": "Prolonged Learning Curve",
        "Risk Factors Description": "Slow proficiency causes: productivity drag (learning curve), quality issues (errors), frustration, high support costs, delayed value realization.",
        "Metric": "Time to Proficiency",
        "Metric Description": "Average days from go-live to achieving proficient performance (meets performance standards, minimal support). Benchmark: <90 days to proficiency.",
        "Unit": "Days",
        "Target": "<90 days to proficiency",
        "Instructions": "Track users from go-live to proficiency milestone (defined as: meets performance standards, minimal support, self-sufficient). Calculate average days. >120 days = slow adoption."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Adoption & Sustainment > Reinforcement Mechanisms",
        "Description": "The systems and practices put in place to reinforce new behaviors and prevent reversion including measurement, accountability, and recognition",
        "Business Drivers": "Sustained Change",
        "Business Drivers Description": "Reinforcement mechanisms prevent: reversion to old ways (backsliding), drift over time, inconsistent application, loss of gains, need for re-change.",
        "Performance Factors": "Strong Reinforcement",
        "Performance Factors Description": "Strong reinforcement: new behaviors in performance reviews, measurement/reporting continues, leadership accountability, recognition of adoption, coaching available.",
        "Risk Factors": "No Reinforcement",
        "Risk Factors Description": "Lack of reinforcement causes: reversion (change doesn't stick), drift from standard, inconsistent application, value erosion, need to re-change (waste).",
        "Metric": "Sustainment Mechanisms in Place",
        "Metric Description": "# of sustainment mechanisms deployed (performance mgmt, metrics, accountability, recognition, coaching). Target: 4+ mechanisms for major changes.",
        "Unit": "Count",
        "Target": ">4 mechanisms deployed",
        "Instructions": "List sustainment mechanisms: included in performance reviews?, ongoing measurement?, leadership accountability?, recognition program?, coaching available? Count active mechanisms. Major changes need 4+."
    },

    # LEVEL 2: CHANGE PERFORMANCE (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Change > Change Performance",
        "Description": "The outcomes and results of change initiatives measured by success rates, benefit realization, timeline adherence, and continuous improvement",
        "Business Drivers": "ROI & Capability Building",
        "Business Drivers Description": "Change performance determines: ROI on change investment, benefit realization, organizational confidence in change, continuous improvement, competitive advantage.",
        "Performance Factors": "High Success Rates",
        "Performance Factors Description": "Strong change performance: >70% success rate, benefits realized on time, timelines met, budget adherence, lessons learned applied, continuous improvement.",
        "Risk Factors": "Change Failure Pattern",
        "Risk Factors Description": "Poor change performance shows: <50% success rate, benefits not realized, chronic delays, budget overruns, repeated mistakes, change cynicism.",
        "Metric": "Change Performance Index",
        "Metric Description": "Composite of 4 sub-elements: Success Rate + Benefit Realization + Timeline Performance + Continuous Improvement. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining success data, benefit tracking, schedule performance, and improvement metrics."
    },

    # LEVEL 3: Change Performance Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Change > Change Performance > Success Rate",
        "Description": "The percentage of change initiatives that achieve stated objectives and are considered successful versus those that fail or are abandoned",
        "Business Drivers": "Organizational Confidence",
        "Business Drivers Description": "High success rates build: organizational confidence in change, willingness to change, change capability, competitive advantage, stakeholder trust.",
        "Performance Factors": "Majority Succeed",
        "Performance Factors Description": "Strong success rate: >70% of initiatives achieve objectives (Prosci benchmark), clear success criteria defined, measured, lessons from failures applied.",
        "Risk Factors": "Change Failure Pattern",
        "Risk Factors Description": "Low success rate (<50%) causes: change cynicism ('here we go again'), resistance to future change, wasted investment, competitive disadvantage, talent loss.",
        "Metric": "Change Initiative Success Rate",
        "Metric Description": "% of completed change initiatives that achieved stated objectives and are rated 'successful' by sponsors. Benchmark: >70% success (Prosci).",
        "Unit": "Percentage (%)",
        "Target": ">70% success rate",
        "Instructions": "Track all change initiatives to completion. Survey sponsor and stakeholders: objectives achieved?, successful? Calculate % successful. Industry research: 70% success is strong."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Performance > Benefit Realization",
        "Description": "The extent to which projected benefits from change initiatives are actually realized and sustained in the defined timeframe",
        "Business Drivers": "ROI Validation",
        "Business Drivers Description": "Benefit realization validates: business case (ROI achieved), change investment justified, value delivered, stakeholder confidence, future change support.",
        "Performance Factors": "Benefits Delivered",
        "Performance Factors Description": "Strong benefit realization: >80% of projected benefits achieved, benefits sustained post-change, measured systematically, benefit realization plans executed.",
        "Risk Factors": "Benefit Shortfalls",
        "Risk Factors Description": "Benefits not realized cause: ROI missed, business case invalid, value not delivered, change investment questioned, future change support erodes.",
        "Metric": "Benefit Realization Rate",
        "Metric Description": "% of projected benefits (from business cases) actually realized within expected timeframe. Measure at 6 and 12 months post-implementation. Target: >80%.",
        "Unit": "Percentage (% of projected)",
        "Target": ">80% benefits realized",
        "Instructions": "Track benefits by initiative: projected (from business case) vs actual (measured post-implementation). Calculate realization % at 6 mo and 12 mo. >80% = strong delivery."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Performance > Timeline Performance",
        "Description": "The degree to which change initiatives are completed on schedule versus experiencing delays or timeline extensions",
        "Business Drivers": "Speed to Value",
        "Business Drivers Description": "On-time delivery provides: speed to value (benefits realized faster), credibility (reliable execution), stakeholder confidence, competitive advantage, momentum.",
        "Performance Factors": "On-Time Delivery",
        "Performance Factors Description": "Strong timeline performance: >80% of initiatives on-time (within 10% of plan), delays managed proactively, realistic planning, schedule adherence culture.",
        "Risk Factors": "Chronic Delays",
        "Risk Factors Description": "Chronic delays cause: delayed benefits, credibility loss, stakeholder frustration, increased costs, momentum loss, 'they never deliver on time' cynicism.",
        "Metric": "Schedule Performance Index (SPI)",
        "Metric Description": "Average schedule performance for change portfolio: actual delivery date vs planned. SPI = planned duration / actual duration. SPI >0.9 (within 10%) is good.",
        "Unit": "Index",
        "Target": "SPI >0.9 (within 10% of plan)",
        "Instructions": "Track change initiatives: planned completion date vs actual. Calculate schedule variance. SPI = planned / actual. Average across portfolio. >0.9 (within 10%) = strong performance."
    },
    {
        "Level": 3,
        "Hierarchy": "Change > Change Performance > Continuous Improvement",
        "Description": "The systematic capture, analysis, and application of lessons learned from change initiatives to improve future change effectiveness",
        "Business Drivers": "Capability Enhancement",
        "Business Drivers Description": "Continuous improvement enables: rising success rates, faster delivery, lower costs, capability building, institutional knowledge, competitive advantage.",
        "Performance Factors": "Active Learning Culture",
        "Performance Factors Description": "Strong continuous improvement: lessons learned captured (100% of initiatives), analyzed for patterns, applied to next initiatives, measurable improvement over time.",
        "Risk Factors": "Repeated Mistakes",
        "Risk Factors Description": "Not learning causes: repeated mistakes, no improvement, stagnant success rates, wasted investment, frustration ('why don't we get better at this?').",
        "Metric": "Lessons Learned Capture Rate",
        "Metric Description": "% of completed change initiatives with documented lessons learned (successes + failures) captured and shared. Target: 100% of major initiatives.",
        "Unit": "Percentage (%)",
        "Target": "100% lessons captured",
        "Instructions": "Track lessons learned completion for all change initiatives (success or failure). Require documentation: what worked, what didn't, recommendations. Calculate % with lessons captured. Target 100%."
    }
]
