"""
Reputation Dimension Data
Expert Senior Business Analyst - 20+ years experience

This dimension measures organizational reputation including corporate reputation,
media perception, stakeholder trust, crisis management capability,
transparency & disclosure quality, and ESG performance.
"""

reputation_data = [
    # Level 1: Dimension
    {
        "Level": 1,
        "Hierarchy": "Reputation",
        "Description": "Overall organizational reputation including corporate reputation, media perception, stakeholder trust, crisis management capability, transparency & disclosure, and ESG performance",
        "Business Drivers": "License to Operate",
        "Business Drivers Description": "Strong reputation provides license to operate, attracts customers and talent, enables premium pricing, facilitates partnerships, reduces regulatory scrutiny, and creates resilience during challenging times",
        "Performance Factors": "Excellent Reputation",
        "Performance Factors Description": "Excellent reputation: Top quartile reputation scores, positive media coverage >80%, high stakeholder trust >75%, strong crisis response, transparent disclosure, leading ESG ratings",
        "Risk Factors": "Damaged Reputation",
        "Risk Factors Description": "Damaged reputation: Bottom quartile scores, negative media coverage >40%, low stakeholder trust <50%, poor crisis response, opacity, poor ESG ratings",
        "Metric": "Overall Reputation Index",
        "Metric Description": "Composite index combining corporate reputation scores, media sentiment, stakeholder trust, crisis readiness, disclosure quality, and ESG ratings",
        "Unit": "Index score (0-100)",
        "Target": ">75 (excellent reputation)",
        "Instructions": "Calculate weighted average across 6 reputation elements with equal weighting (16.67% each), normalized to 0-100 scale"
    },

    # Level 2: Corporate Reputation (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Reputation > Corporate Reputation",
        "Description": "Overall corporate reputation as measured by reputation indices, surveys, and stakeholder perceptions including reputation rank, score trends, and competitive benchmarking",
        "Business Drivers": "Brand Value",
        "Business Drivers Description": "Strong corporate reputation builds brand value, customer preference, talent attraction, investor confidence, and creates business resilience",
        "Performance Factors": "Strong Reputation",
        "Performance Factors Description": "Strong: Top quartile in reputation indices (e.g., RepTrak >70), improving trend, stronger than competitors, positive stakeholder perceptions",
        "Risk Factors": "Weak Reputation",
        "Risk Factors Description": "Weak: Bottom quartile scores (<50), declining trend, weaker than competitors, negative stakeholder perceptions, reputational crises",
        "Metric": "Corporate Reputation Score",
        "Metric Description": "Standardized reputation measurement from recognized indices (e.g., RepTrak, Fortune's Most Admired) tracking reputation strength and trend",
        "Unit": "Score (0-100)",
        "Target": ">70 (strong reputation)",
        "Instructions": "Participate in major reputation studies (RepTrak, Fortune, etc.), track scores over time, benchmark competitors, analyze dimension drivers"
    },

    # Level 3: Corporate Reputation Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Reputation > Corporate Reputation > Reputation Index Scores",
        "Description": "Scores from major corporate reputation indices including RepTrak, Fortune's Most Admired Companies, Glassdoor, and industry-specific reputation rankings",
        "Business Drivers": "External Validation",
        "Business Drivers Description": "Reputation index scores provide third-party validation, benchmarking capability, stakeholder confidence, and competitive intelligence",
        "Performance Factors": "Top Quartile Scores",
        "Performance Factors Description": "Top quartile: RepTrak >70, Fortune Most Admired recognition, Glassdoor >4.0, industry rankings in top 25%",
        "Risk Factors": "Bottom Quartile Scores",
        "Risk Factors Description": "Bottom quartile: RepTrak <50, no Most Admired recognition, Glassdoor <3.0, industry rankings in bottom 25%",
        "Metric": "Composite Reputation Index",
        "Metric Description": "Weighted average of major reputation index scores normalized to common scale (0-100)",
        "Unit": "Score (0-100)",
        "Target": ">70 (top quartile)",
        "Instructions": "Collect scores from RepTrak, Fortune, Glassdoor, and industry indices, normalize to 0-100 scale, calculate weighted average"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Corporate Reputation > Reputation Trend Direction",
        "Description": "The direction and velocity of reputation change over time including improving/stable/declining trends, volatility, and momentum indicators",
        "Business Drivers": "Reputation Trajectory",
        "Business Drivers Description": "Reputation trend indicates whether organizational actions are building or eroding reputation, signaling effectiveness of reputation management",
        "Performance Factors": "Improving Trend",
        "Performance Factors Description": "Improving: consistent score increases over 2-3 years, positive momentum, low volatility, narrowing gaps vs best-in-class",
        "Risk Factors": "Declining Trend",
        "Risk Factors Description": "Declining: consistent score decreases, negative momentum, high volatility, widening gaps vs competitors, approaching crisis threshold",
        "Metric": "Reputation Score Change",
        "Metric Description": "Year-over-year change in composite reputation score, tracking direction, velocity, and volatility of reputation",
        "Unit": "Point change per year",
        "Target": "+2 to +5 points per year (improving)",
        "Instructions": "Calculate year-over-year change in reputation scores, assess 3-year trend, measure volatility, benchmark trend vs competitors"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Corporate Reputation > Reputation Dimension Strengths",
        "Description": "The specific reputation dimensions where the organization is strongest including products/services, innovation, workplace, citizenship, governance, leadership, and performance",
        "Business Drivers": "Reputation Differentiation",
        "Business Drivers Description": "Strong reputation dimensions create differentiation, attract specific stakeholder groups, and indicate organizational strengths to leverage",
        "Performance Factors": "Multiple Strengths",
        "Performance Factors Description": "Multiple strengths: 4+ dimensions with top quartile scores, clear differentiation areas, aligned to strategy, leveraged in positioning",
        "Risk Factors": "Few Strengths",
        "Risk Factors Description": "Few strengths: <2 dimensions in top quartile, no clear differentiation, strengths misaligned to strategy, underutilized in market",
        "Metric": "Top Quartile Reputation Dimension Count",
        "Metric Description": "Number of reputation dimensions (typically 7-9 depending on framework) scoring in top quartile vs benchmark",
        "Unit": "Count (of dimensions)",
        "Target": ">4 dimensions (strong differentiation)",
        "Instructions": "Break reputation score into dimensions (products, innovation, workplace, citizenship, etc.), benchmark each, count top quartile"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Corporate Reputation > Reputation Gaps & Vulnerabilities",
        "Description": "Reputation weaknesses, gaps vs competitors, and vulnerabilities that could trigger reputation crises including specific dimension weaknesses and stakeholder concerns",
        "Business Drivers": "Risk Mitigation",
        "Business Drivers Description": "Identifying reputation vulnerabilities enables proactive mitigation, prevents reputation crises, and guides improvement priorities",
        "Performance Factors": "Minimal Vulnerabilities",
        "Performance Factors Description": "Minimal: No dimensions in bottom quartile, gaps <10 points vs competitors, proactive vulnerability management, no crisis risks",
        "Risk Factors": "Significant Vulnerabilities",
        "Risk Factors Description": "Significant: 2+ dimensions in bottom quartile, gaps >20 points vs competitors, unaddressed vulnerabilities, high crisis risk",
        "Metric": "Critical Reputation Gap Count",
        "Metric Description": "Number of reputation dimensions with bottom quartile scores or gaps >15 points vs key competitors",
        "Unit": "Count (of critical gaps)",
        "Target": "0-1 (minimal vulnerabilities)",
        "Instructions": "Identify bottom quartile dimensions, measure gaps vs competitors, assess vulnerability to reputation crises, prioritize by risk"
    },

    # Level 2: Media Perception (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Reputation > Media Perception",
        "Description": "Media coverage and perception including volume of coverage, sentiment balance, share of voice vs competitors, and media relationship quality",
        "Business Drivers": "Public Perception",
        "Business Drivers Description": "Media coverage shapes public perception, influences stakeholder opinions, impacts reputation scores, and creates narrative momentum",
        "Performance Factors": "Positive Media Coverage",
        "Performance Factors Description": "Positive: High volume of coverage, >70% positive sentiment, strong share of voice, tier-1 media relationships, narrative control",
        "Risk Factors": "Negative Media Coverage",
        "Risk Factors Description": "Negative: Low volume or >30% negative sentiment, weak share of voice, poor media relationships, lost narrative control",
        "Metric": "Media Sentiment Score",
        "Metric Description": "Percentage of positive media coverage minus percentage of negative coverage, measuring overall media tone and perception",
        "Unit": "Net percentage (%)",
        "Target": ">60% net positive",
        "Instructions": "Monitor all media coverage, classify sentiment (positive/neutral/negative), calculate net positive percentage, trend over time"
    },

    # Level 3: Media Perception Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Reputation > Media Perception > Media Coverage Volume",
        "Description": "The volume and reach of media coverage including number of stories, media tier mix, reach/impressions, and coverage trend over time",
        "Business Drivers": "Visibility",
        "Business Drivers Description": "Coverage volume drives awareness, influences perception, creates opportunities for positive positioning, and signals market relevance",
        "Performance Factors": "High Visibility",
        "Performance Factors Description": "High visibility: >100 tier-1 stories/year, >50% tier-1 coverage, >100M impressions/quarter, increasing trend",
        "Risk Factors": "Low Visibility",
        "Risk Factors Description": "Low visibility: <50 total stories/year, <20% tier-1 coverage, <10M impressions/quarter, declining trend, invisibility",
        "Metric": "Media Coverage Count & Reach",
        "Metric Description": "Number of media stories per period and cumulative reach/impressions, segmented by media tier (1/2/3)",
        "Unit": "Count and impressions",
        "Target": ">100 tier-1 stories/year, >100M impressions/quarter",
        "Instructions": "Monitor media coverage using media monitoring service, classify by tier, track count and reach, trend over time"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Media Perception > Media Sentiment Balance",
        "Description": "The balance of positive, neutral, and negative media coverage including sentiment distribution, sentiment drivers, and sentiment trend",
        "Business Drivers": "Favorable Perception",
        "Business Drivers Description": "Positive sentiment balance builds reputation, attracts stakeholders, creates favorable public opinion, and provides crisis resilience",
        "Performance Factors": "Highly Positive",
        "Performance Factors Description": "Highly positive: >70% positive coverage, <10% negative, improving sentiment trend, positive sentiment on key topics",
        "Risk Factors": "Highly Negative",
        "Risk Factors Description": "Highly negative: <40% positive, >30% negative, deteriorating sentiment, negative sentiment on key topics, crisis coverage",
        "Metric": "Positive Coverage Percentage",
        "Metric Description": "Percentage of media stories with positive sentiment tone out of total coverage",
        "Unit": "Percentage (%)",
        "Target": ">70% positive",
        "Instructions": "Use media monitoring sentiment analysis, classify each story as positive/neutral/negative, calculate percentages, identify drivers"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Media Perception > Share of Voice vs Competitors",
        "Description": "The organization's media coverage volume relative to key competitors, indicating relative visibility and market mindshare",
        "Business Drivers": "Competitive Visibility",
        "Business Drivers Description": "Strong share of voice demonstrates market relevance, competitive standing, and ability to influence market narrative",
        "Performance Factors": "Leading Share",
        "Performance Factors Description": "Leading share: #1 or #2 share of voice in category, >30% share, growing relative to competitors, dominating key topics",
        "Risk Factors": "Weak Share",
        "Risk Factors Description": "Weak share: Outside top 3, <15% share, declining relative to competitors, absent from key topic discussions",
        "Metric": "Media Share of Voice",
        "Metric Description": "Organization's media coverage volume as percentage of total coverage for the organization plus key competitors",
        "Unit": "Percentage (%)",
        "Target": ">30% (leading position)",
        "Instructions": "Monitor media coverage for organization and 3-5 key competitors, calculate organization's percentage of total coverage volume"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Media Perception > Media Relationship Quality",
        "Description": "The quality of relationships with key media outlets and journalists including spokesperson access, response timeliness, story accuracy, and media satisfaction",
        "Business Drivers": "Media Partnership",
        "Business Drivers Description": "Strong media relationships enable proactive storytelling, accurate coverage, crisis support, and positive narrative framing",
        "Performance Factors": "Excellent Relationships",
        "Performance Factors Description": "Excellent: Regular tier-1 journalist engagement, <4 hour media response, >95% quote accuracy, positive media feedback",
        "Risk Factors": "Poor Relationships",
        "Risk Factors Description": "Poor: Limited journalist relationships, >24 hour response, <80% quote accuracy, negative media feedback, access challenges",
        "Metric": "Media Relationship Score",
        "Metric Description": "Assessment of media relationship quality based on engagement frequency, response time, accuracy, and journalist satisfaction",
        "Unit": "Score (0-100)",
        "Target": ">80 (excellent relationships)",
        "Instructions": "Survey key journalists, track response times, measure quote accuracy, assess engagement frequency, calculate composite score"
    },

    # Level 2: Stakeholder Trust (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Reputation > Stakeholder Trust",
        "Description": "Trust levels across key stakeholder groups including customers, employees, investors, partners, regulators, and communities",
        "Business Drivers": "Relationship Capital",
        "Business Drivers Description": "Stakeholder trust reduces transaction costs, enables difficult conversations, creates resilience during challenges, and facilitates collaboration",
        "Performance Factors": "High Trust",
        "Performance Factors Description": "High trust: >75% trust levels across all key stakeholder groups, improving trend, trust advantage vs competitors",
        "Risk Factors": "Low Trust",
        "Risk Factors Description": "Low trust: <50% trust levels in any key stakeholder group, declining trend, trust deficit vs competitors, trust crisis risk",
        "Metric": "Stakeholder Trust Index",
        "Metric Description": "Composite index measuring trust levels across key stakeholder groups (customers, employees, investors, partners, regulators, communities)",
        "Unit": "Index score (0-100)",
        "Target": ">75 (high trust)",
        "Instructions": "Survey each stakeholder group on trust dimensions, calculate group scores, create weighted composite index"
    },

    # Level 3: Stakeholder Trust Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Reputation > Stakeholder Trust > Customer Trust",
        "Description": "Customer trust in the organization including trust to deliver promises, handle data responsibly, act ethically, and operate in customers' best interests",
        "Business Drivers": "Customer Loyalty",
        "Business Drivers Description": "Customer trust drives loyalty, reduces price sensitivity, enables upsell/cross-sell, generates referrals, and creates competitive advantage",
        "Performance Factors": "High Customer Trust",
        "Performance Factors Description": "High trust: >80% customers trust organization, trust advantage vs competitors, trust-based differentiation, premium pricing supported",
        "Risk Factors": "Low Customer Trust",
        "Risk Factors Description": "Low trust: <60% customer trust, trust deficit vs competitors, trust-damaging incidents, churn risk, referral decline",
        "Metric": "Customer Trust Score",
        "Metric Description": "Percentage of customers expressing trust in organization across multiple trust dimensions (competence, integrity, benevolence)",
        "Unit": "Percentage (%)",
        "Target": ">80% (high trust)",
        "Instructions": "Survey customers on trust dimensions (will deliver, handle data properly, act ethically, act in customer interest), calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Stakeholder Trust > Employee Trust",
        "Description": "Employee trust in organizational leadership, direction, values, and commitment to employees including trust in senior leadership and immediate managers",
        "Business Drivers": "Engagement & Retention",
        "Business Drivers Description": "Employee trust drives engagement, reduces turnover, enables change adoption, increases productivity, and creates advocacy",
        "Performance Factors": "High Employee Trust",
        "Performance Factors Description": "High trust: >75% trust in leadership, >80% trust in immediate manager, trust improving, aligned to values, confident in direction",
        "Risk Factors": "Low Employee Trust",
        "Risk Factors Description": "Low trust: <50% trust in leadership, <60% trust in manager, trust declining, values misalignment, direction uncertainty",
        "Metric": "Employee Trust in Leadership",
        "Metric Description": "Percentage of employees expressing trust in senior leadership and immediate managers to make good decisions and act in employees' best interests",
        "Unit": "Percentage (%)",
        "Target": ">75% (high trust)",
        "Instructions": "Include trust questions in employee engagement surveys (trust leadership, trust manager, trust direction), calculate percentages"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Stakeholder Trust > Investor Trust & Confidence",
        "Description": "Investor trust in management capability, strategic direction, financial reporting, and ability to deliver long-term value creation",
        "Business Drivers": "Capital Access",
        "Business Drivers Description": "Investor trust reduces cost of capital, enables capital raising, supports valuation multiples, and provides strategic flexibility",
        "Performance Factors": "High Investor Confidence",
        "Performance Factors Description": "High confidence: analyst recommendation consensus Buy/Outperform, low earnings skepticism, premium valuation multiple, capital raising ease",
        "Risk Factors": "Low Investor Confidence",
        "Risk Factors Description": "Low confidence: analyst consensus Hold/Underperform, high earnings skepticism, discount valuation, capital raising difficulty, activist pressure",
        "Metric": "Analyst Recommendation Consensus",
        "Metric Description": "Weighted average of analyst recommendations normalized to 5-point scale (1=Strong Sell to 5=Strong Buy) indicating investor confidence",
        "Unit": "Score (1-5)",
        "Target": ">4.0 (Buy consensus)",
        "Instructions": "Collect analyst recommendations, weight by analyst importance, calculate consensus score on 1-5 scale, track trend"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Stakeholder Trust > Partner & Supplier Trust",
        "Description": "Trust of business partners and suppliers in the organization's reliability, fair dealing, collaboration, and mutual value creation",
        "Business Drivers": "Ecosystem Strength",
        "Business Drivers Description": "Partner trust enables deeper collaboration, preferential treatment, innovation partnerships, and resilient supply chains",
        "Performance Factors": "High Partner Trust",
        "Performance Factors Description": "High trust: >80% partners rate trust highly, preferred partner status, strategic partnership opportunities, low partner churn",
        "Risk Factors": "Low Partner Trust",
        "Risk Factors Description": "Low trust: <60% partners rate trust highly, transactional relationships, partnership opportunities lost, high partner churn",
        "Metric": "Partner Trust & Satisfaction Score",
        "Metric Description": "Composite score from partner surveys measuring trust, satisfaction, likelihood to continue relationship, and likelihood to expand",
        "Unit": "Score (0-100)",
        "Target": ">80 (high trust)",
        "Instructions": "Survey strategic partners and key suppliers on trust dimensions and satisfaction, calculate composite NPS-style score"
    },

    # Level 2: Crisis Management (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Reputation > Crisis Management",
        "Description": "Capability to prevent, prepare for, respond to, and recover from reputation crises including crisis readiness, response effectiveness, and reputation recovery",
        "Business Drivers": "Reputation Protection",
        "Business Drivers Description": "Strong crisis management prevents reputation damage, enables rapid response, minimizes crisis impact, and accelerates reputation recovery",
        "Performance Factors": "Crisis Ready",
        "Performance Factors Description": "Crisis ready: Comprehensive crisis plans, trained teams, monitoring systems, <24 hour response, effective recovery, minimal reputation impact",
        "Risk Factors": "Crisis Vulnerable",
        "Risk Factors Description": "Crisis vulnerable: No crisis plans, untrained teams, no monitoring, slow response, poor recovery, major reputation damage risk",
        "Metric": "Crisis Management Readiness Score",
        "Metric Description": "Assessment of crisis preparation, monitoring capability, response plans, team training, and historical crisis recovery effectiveness",
        "Unit": "Score (0-100)",
        "Target": ">80 (crisis ready)",
        "Instructions": "Assess crisis management across 4 dimensions (readiness, monitoring, response, recovery), calculate weighted composite score"
    },

    # Level 3: Crisis Management Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Reputation > Crisis Management > Crisis Preparedness",
        "Description": "Preparation for potential reputation crises including crisis plan existence, scenario planning, crisis team establishment, training frequency, and simulation exercises",
        "Business Drivers": "Proactive Readiness",
        "Business Drivers Description": "Crisis preparedness reduces response time, improves response quality, minimizes damage, and demonstrates governance maturity",
        "Performance Factors": "Highly Prepared",
        "Performance Factors Description": "Highly prepared: Current crisis plans for top 10 scenarios, trained crisis team, quarterly simulations, clear protocols, instant activation",
        "Risk Factors": "Unprepared",
        "Risk Factors Description": "Unprepared: No crisis plans, no crisis team, no training, no simulations, ad-hoc protocols, delayed activation",
        "Metric": "Crisis Preparedness Index",
        "Metric Description": "Assessment of crisis plan quality, team readiness, training frequency, simulation exercises, and protocol clarity",
        "Unit": "Score (0-100)",
        "Target": ">85 (highly prepared)",
        "Instructions": "Review crisis plan currency, assess crisis team training, count simulation exercises, evaluate protocols, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Crisis Management > Crisis Monitoring & Early Warning",
        "Description": "Capability to detect emerging reputation risks and crises early including social listening, media monitoring, stakeholder feedback, and risk indicator tracking",
        "Business Drivers": "Early Detection",
        "Business Drivers Description": "Early crisis detection enables proactive response, reduces damage, increases response options, and demonstrates vigilance",
        "Performance Factors": "Comprehensive Monitoring",
        "Performance Factors Description": "Comprehensive: 24/7 social listening, real-time media monitoring, stakeholder feedback systems, risk dashboards, <1 hour detection",
        "Risk Factors": "Limited Monitoring",
        "Risk Factors Description": "Limited: No social listening, delayed media monitoring, no feedback systems, no risk tracking, >24 hour detection",
        "Metric": "Crisis Detection Speed",
        "Metric Description": "Average time from crisis emergence in public domain to internal detection and alert, measuring monitoring effectiveness",
        "Unit": "Hours",
        "Target": "<1 hour (real-time detection)",
        "Instructions": "Implement monitoring systems, track crisis detection events, measure time from public emergence to internal detection"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Crisis Management > Crisis Response Effectiveness",
        "Description": "Quality and speed of crisis response including response timeliness, message quality, stakeholder communication, action decisiveness, and response coordination",
        "Business Drivers": "Damage Minimization",
        "Business Drivers Description": "Effective crisis response limits reputation damage, maintains stakeholder trust, demonstrates accountability, and enables faster recovery",
        "Performance Factors": "Highly Effective Response",
        "Performance Factors Description": "Highly effective: <24 hour public response, clear messaging, proactive stakeholder communication, decisive action, coordinated execution",
        "Risk Factors": "Ineffective Response",
        "Risk Factors Description": "Ineffective: >3 day response delay, poor messaging, reactive communication, indecisive action, uncoordinated execution",
        "Metric": "Crisis Response Time & Quality Score",
        "Metric Description": "Composite score measuring response speed (hours to first response), message quality, stakeholder communication, and action effectiveness",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly effective)",
        "Instructions": "Track crisis response time, assess message quality, evaluate stakeholder communication, rate action decisiveness, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Crisis Management > Reputation Recovery Speed",
        "Description": "The speed and completeness of reputation recovery following crises including reputation score recovery rate, stakeholder trust restoration, and return to normal operations",
        "Business Drivers": "Resilience",
        "Business Drivers Description": "Fast reputation recovery minimizes business impact, restores stakeholder confidence, validates crisis management, and demonstrates resilience",
        "Performance Factors": "Rapid Recovery",
        "Performance Factors Description": "Rapid recovery: Reputation score returns to pre-crisis level within 3-6 months, stakeholder trust restored, lessons learned implemented",
        "Risk Factors": "Slow Recovery",
        "Risk Factors Description": "Slow recovery: >12 months to pre-crisis level, persistent stakeholder distrust, incomplete recovery, no lessons learned",
        "Metric": "Reputation Recovery Half-Life",
        "Metric Description": "Time required for reputation score to recover halfway from post-crisis nadir to pre-crisis baseline, measuring recovery speed",
        "Unit": "Months",
        "Target": "<3 months (rapid recovery)",
        "Instructions": "Measure reputation score drop during crisis, track recovery trajectory, calculate time to 50% recovery, benchmark vs industry"
    },

    # Level 2: Transparency & Disclosure (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Reputation > Transparency & Disclosure",
        "Description": "Quality and comprehensiveness of corporate transparency and disclosure including reporting quality, disclosure completeness, accessibility, and stakeholder communication",
        "Business Drivers": "Stakeholder Confidence",
        "Business Drivers Description": "Transparent disclosure builds stakeholder trust, reduces information asymmetry, demonstrates governance quality, and prevents reputation crises",
        "Performance Factors": "Highly Transparent",
        "Performance Factors Description": "Highly transparent: Leading disclosure practices, exceeds requirements, accessible reporting, proactive communication, recognized for transparency",
        "Risk Factors": "Opaque",
        "Risk Factors Description": "Opaque: Minimal disclosure, meets only requirements, difficult access, reactive communication, transparency criticism, disclosure gaps",
        "Metric": "Transparency & Disclosure Score",
        "Metric Description": "Assessment of disclosure quality, completeness, accessibility, timeliness, and stakeholder communication effectiveness",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly transparent)",
        "Instructions": "Evaluate reporting quality, assess disclosure completeness, measure accessibility, track communication, calculate composite score"
    },

    # Level 3: Transparency & Disclosure Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Reputation > Transparency & Disclosure > Financial Reporting Quality",
        "Description": "Quality of financial reporting including clarity, completeness, timeliness, materiality assessment, and absence of restatements or qualifications",
        "Business Drivers": "Investor Confidence",
        "Business Drivers Description": "High-quality financial reporting builds investor confidence, reduces cost of capital, enables accurate valuation, and prevents crises",
        "Performance Factors": "Excellent Reporting",
        "Performance Factors Description": "Excellent: Clear presentation, comprehensive disclosure, early filing, strong materiality process, clean audit, no restatements (5+ years)",
        "Risk Factors": "Poor Reporting",
        "Risk Factors Description": "Poor: Unclear presentation, disclosure gaps, late filings, weak materiality process, qualified audit, restatements (<3 years)",
        "Metric": "Financial Reporting Quality Index",
        "Metric Description": "Composite assessment of reporting clarity, disclosure completeness, filing timeliness, audit opinion, and restatement history",
        "Unit": "Score (0-100)",
        "Target": ">85 (excellent reporting)",
        "Instructions": "Assess financial report clarity, evaluate disclosure vs peers, track filing timeline, review audit opinions, check restatement history"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Transparency & Disclosure > Non-Financial Disclosure Completeness",
        "Description": "Comprehensiveness of non-financial disclosure including sustainability reporting, risk disclosure, strategy disclosure, and governance disclosure",
        "Business Drivers": "Holistic Transparency",
        "Business Drivers Description": "Comprehensive non-financial disclosure demonstrates responsible business practices, addresses stakeholder needs, and prevents reputation risks",
        "Performance Factors": "Comprehensive Disclosure",
        "Performance Factors Description": "Comprehensive: Integrated reporting, sustainability reporting (GRI/SASB), full risk disclosure, strategy transparency, governance detail",
        "Risk Factors": "Limited Disclosure",
        "Risk Factors Description": "Limited: Financial-only reporting, no sustainability report, minimal risk disclosure, strategy opacity, governance gaps",
        "Metric": "Non-Financial Disclosure Completeness Score",
        "Metric Description": "Assessment of sustainability reporting quality, risk disclosure depth, strategy transparency, and governance disclosure completeness",
        "Unit": "Score (0-100)",
        "Target": ">80 (comprehensive disclosure)",
        "Instructions": "Evaluate sustainability report (vs GRI/SASB), assess risk disclosure, review strategy communication, check governance disclosure"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Transparency & Disclosure > Information Accessibility",
        "Description": "Ease of accessing corporate information including website usability, document availability, IR responsiveness, and stakeholder communication channels",
        "Business Drivers": "Stakeholder Service",
        "Business Drivers Description": "Easy information access reduces stakeholder effort, demonstrates openness, prevents misinformation, and builds trust",
        "Performance Factors": "Highly Accessible",
        "Performance Factors Description": "Highly accessible: Excellent website UX, all documents searchable/downloadable, <24 hour IR response, multiple communication channels",
        "Risk Factors": "Poor Accessibility",
        "Risk Factors Description": "Poor accessibility: Difficult website navigation, limited document access, >3 day IR response, few communication channels",
        "Metric": "Information Accessibility Score",
        "Metric Description": "Assessment of website usability, document availability, IR response time, and communication channel diversity",
        "Unit": "Score (0-100)",
        "Target": ">85 (highly accessible)",
        "Instructions": "Test website usability, audit document availability, track IR response times, assess communication channels, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > Transparency & Disclosure > Proactive Stakeholder Communication",
        "Description": "Quality of proactive communication to stakeholders including communication frequency, channel diversity, two-way dialogue, and responsiveness to concerns",
        "Business Drivers": "Relationship Building",
        "Business Drivers Description": "Proactive communication builds relationships, addresses concerns early, demonstrates engagement, and creates transparency perception",
        "Performance Factors": "Highly Proactive",
        "Performance Factors Description": "Highly proactive: Regular stakeholder updates, diverse channels, active dialogue, rapid concern response, solicited feedback",
        "Risk Factors": "Reactive Only",
        "Risk Factors Description": "Reactive only: Minimal stakeholder updates, single channel, one-way communication, slow concern response, unsolicited feedback ignored",
        "Metric": "Stakeholder Communication Index",
        "Metric Description": "Composite score measuring communication frequency, channel diversity, dialogue quality, concern responsiveness, and feedback integration",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly proactive)",
        "Instructions": "Track communication frequency by stakeholder group, assess channel usage, evaluate dialogue quality, measure response times"
    },

    # Level 2: ESG Performance (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Reputation > ESG Performance",
        "Description": "Environmental, Social, and Governance performance including ESG ratings, sustainability metrics, social impact, and governance quality",
        "Business Drivers": "Sustainable Value Creation",
        "Business Drivers Description": "Strong ESG performance attracts investors, customers, and talent; reduces risks; lowers cost of capital; and creates long-term sustainable value",
        "Performance Factors": "Leading ESG Performance",
        "Performance Factors Description": "Leading: Top quartile ESG ratings (AA/AAA or equivalent), strong E/S/G scores, improving trend, ESG-linked incentives, recognized leadership",
        "Risk Factors": "Weak ESG Performance",
        "Risk Factors Description": "Weak: Bottom quartile ESG ratings (B/CCC or lower), weak E/S/G scores, declining trend, no ESG incentives, ESG controversies",
        "Metric": "Composite ESG Rating",
        "Metric Description": "Average of major ESG rating agency scores (MSCI, Sustainalytics, CDP, etc.) normalized to common scale",
        "Unit": "Score (0-100)",
        "Target": ">75 (top quartile)",
        "Instructions": "Collect ESG ratings from major agencies (MSCI, Sustainalytics, CDP, ISS, etc.), normalize to 0-100 scale, calculate average"
    },

    # Level 3: ESG Performance Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Reputation > ESG Performance > Environmental Performance",
        "Description": "Environmental performance including carbon emissions, energy efficiency, water usage, waste management, circular economy practices, and environmental targets achievement",
        "Business Drivers": "Environmental Stewardship",
        "Business Drivers Description": "Strong environmental performance reduces regulatory risk, meets customer expectations, attracts ESG investors, and contributes to climate solutions",
        "Performance Factors": "Strong Environmental Performance",
        "Performance Factors Description": "Strong: Science-based targets committed, >30% emissions reduction, >50% renewable energy, <5% waste to landfill, circular economy initiatives",
        "Risk Factors": "Weak Environmental Performance",
        "Risk Factors Description": "Weak: No emission targets, increasing emissions, <10% renewable energy, >50% waste to landfill, linear economy model",
        "Metric": "Environmental Performance Score",
        "Metric Description": "Composite score measuring carbon reduction progress, renewable energy adoption, waste reduction, water efficiency, and circular economy maturity",
        "Unit": "Score (0-100)",
        "Target": ">75 (strong performance)",
        "Instructions": "Track carbon emissions, renewable energy %, waste diversion rate, water efficiency, circular economy initiatives, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > ESG Performance > Social Impact & Responsibility",
        "Description": "Social performance including diversity & inclusion, labor practices, human rights, community engagement, product responsibility, and social impact measurement",
        "Business Drivers": "Social License",
        "Business Drivers Description": "Strong social performance maintains license to operate, attracts diverse talent, builds customer loyalty, and creates positive stakeholder relationships",
        "Performance Factors": "Strong Social Performance",
        "Performance Factors Description": "Strong: >40% diverse leadership, strong labor practices, human rights due diligence, active community engagement, positive social impact",
        "Risk Factors": "Weak Social Performance",
        "Risk Factors Description": "Weak: <20% diverse leadership, poor labor practices, human rights concerns, minimal community engagement, negative social impact",
        "Metric": "Social Performance Score",
        "Metric Description": "Composite score measuring diversity metrics, labor practice quality, human rights compliance, community investment, and social impact",
        "Unit": "Score (0-100)",
        "Target": ">75 (strong performance)",
        "Instructions": "Track diversity metrics, assess labor practices, review human rights processes, measure community investment, evaluate social impact"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > ESG Performance > Governance Quality",
        "Description": "Corporate governance quality including board composition, independence, diversity, oversight effectiveness, ethics programs, and anti-corruption measures",
        "Business Drivers": "Governance Excellence",
        "Business Drivers Description": "Strong governance reduces risk, builds investor confidence, prevents crises, enables long-term value creation, and demonstrates accountability",
        "Performance Factors": "Excellent Governance",
        "Performance Factors Description": "Excellent: >80% independent board, >30% diverse board, strong oversight, robust ethics program, no corruption incidents",
        "Risk Factors": "Weak Governance",
        "Risk Factors Description": "Weak: <60% independent board, <10% diverse board, weak oversight, minimal ethics program, corruption incidents",
        "Metric": "Governance Quality Score",
        "Metric Description": "Assessment of board composition, independence, diversity, oversight effectiveness, ethics program quality, and anti-corruption controls",
        "Unit": "Score (0-100)",
        "Target": ">85 (excellent governance)",
        "Instructions": "Evaluate board composition metrics, assess oversight effectiveness, review ethics program, check anti-corruption controls, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Reputation > ESG Performance > ESG Integration & Accountability",
        "Description": "Integration of ESG into strategy, operations, and incentives including ESG strategy clarity, operational integration, executive accountability, and progress transparency",
        "Business Drivers": "ESG Maturity",
        "Business Drivers Description": "ESG integration demonstrates commitment, drives performance improvement, creates accountability, and builds stakeholder confidence",
        "Performance Factors": "Fully Integrated",
        "Performance Factors Description": "Fully integrated: Clear ESG strategy, operational integration, ESG-linked executive pay (>20%), board oversight, transparent reporting",
        "Risk Factors": "Siloed ESG",
        "Risk Factors Description": "Siloed: Unclear ESG strategy, no operational integration, no ESG incentives, minimal board oversight, limited transparency",
        "Metric": "ESG Integration Maturity",
        "Metric Description": "Assessment of ESG strategy clarity, operational integration depth, executive incentive linkage, board oversight, and reporting transparency",
        "Unit": "Score (0-100)",
        "Target": ">80 (fully integrated)",
        "Instructions": "Evaluate ESG strategy quality, assess operational integration, review executive incentives, check board oversight, assess reporting"
    }
]
