"""
People Dimension Data - ENABLERS Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

people_data = [
    # LEVEL 1: PEOPLE DIMENSION
    {
        "Level": 1,
        "Hierarchy": "People",
        "Description": "The human capital, talent, capabilities, and workforce practices that enable organizational performance and competitive advantage",
        "Business Drivers": "Capability & Performance Delivery",
        "Business Drivers Description": "People are the primary source of competitive advantage in knowledge economy. Strong talent management drives: execution capability, innovation, customer satisfaction, and sustained performance.",
        "Performance Factors": "Workforce Quality & Engagement",
        "Performance Factors Description": "High-performing people systems show: A-player density, strong engagement, effective performance management, competitive total rewards, career growth, healthy culture. Measured by talent quality, retention, productivity.",
        "Risk Factors": "Talent Shortages & Turnover",
        "Risk Factors Description": "People risks include: key talent loss, skills gaps, poor hiring, low engagement, succession failures, workforce burnout. Impacts: execution failure, knowledge loss, competitive disadvantage.",
        "Metric": "Overall People Health Score",
        "Metric Description": "Composite index of 6 element scores: Talent Acquisition + Performance Management + Compensation & Benefits + Career Development + Employee Wellbeing + Workforce Planning. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70 (healthy people systems)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Weight by strategic importance. Industry benchmark: >70 indicates strong people practices."
    },

    # LEVEL 2: TALENT ACQUISITION (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "People > Talent Acquisition",
        "Description": "The organization's ability to attract, assess, and hire high-quality talent aligned with role requirements and cultural values",
        "Business Drivers": "Talent Quality & Capability",
        "Business Drivers Description": "Talent acquisition is the foundation of organizational capability. Strong hiring processes fill skills gaps, raise performance bar, bring fresh perspectives, and build competitive advantage.",
        "Performance Factors": "Effective Hiring",
        "Performance Factors Description": "Strong talent acquisition shows: A-player hires (top 10% of market), fast time-to-hire (<45 days), high offer acceptance (>80%), strong new hire performance, low early attrition.",
        "Risk Factors": "Poor Hiring & Talent Gaps",
        "Risk Factors Description": "Weak talent acquisition drives: B/C player hires, prolonged vacancies, capability gaps, poor culture fit, high early turnover (18-month failure), expensive mis-hires.",
        "Metric": "Talent Acquisition Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Hiring Quality + Time-to-Fill + Offer Acceptance Rate + New Hire Retention. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores. Track quarterly. Strong correlation with 12-month organizational performance."
    },

    # LEVEL 3: Talent Acquisition Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "People > Talent Acquisition > Hiring Quality",
        "Description": "The caliber of talent hired relative to role requirements and market benchmarks, measured by manager satisfaction and new hire performance",
        "Business Drivers": "Performance & Capability Building",
        "Business Drivers Description": "Hiring quality is #1 predictor of org performance. A-players deliver 2-5x productivity vs average, raise team performance, attract other A-players, and drive competitive advantage.",
        "Performance Factors": "A-Player Hiring Rate",
        "Performance Factors Description": "Strong hiring quality shows: >70% of hires rated 'exceeds expectations' in first year, high manager satisfaction (>4/5), measurable performance outcomes, skills match.",
        "Risk Factors": "Mis-Hires",
        "Risk Factors Description": "Poor hiring quality drives: 1-2 year underperformance (costly), team drag, customer impact, eventual termination (expensive), lowered bar for future hires.",
        "Metric": "New Hire Quality Score",
        "Metric Description": "% of new hires rated 'meets or exceeds expectations' in 12-month performance review. Strong indicator: >80%. Also survey hiring manager at 90 days: 'Would you hire again?'",
        "Unit": "Percentage (%)",
        "Target": ">80% meet/exceed expectations at 12 mo",
        "Instructions": "Track first-year performance ratings for all new hires. Calculate % rated 'meets' or 'exceeds' expectations. Supplement with 90-day hiring manager satisfaction survey."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Talent Acquisition > Time-to-Fill",
        "Description": "The average number of days from job requisition approval to offer acceptance, indicating hiring process efficiency and talent market competitiveness",
        "Business Drivers": "Speed to Capability & Opportunity Cost",
        "Business Drivers Description": "Fast time-to-fill minimizes: vacancy costs (lost productivity), competitive talent loss (to other offers), project delays, burnout of covering employees. Speed matters in talent war.",
        "Performance Factors": "Fast, Efficient Hiring",
        "Performance Factors Description": "Efficient hiring shows: <45 days average time-to-fill, streamlined process (2-3 rounds), fast decision-making, candidate experience focus, recruiting ops excellence.",
        "Risk Factors": "Prolonged Vacancies",
        "Risk Factors Description": "Slow hiring drives: top candidates lost to other offers, project delays, team burnout, poor candidate experience (brand damage), hiring desperation (lower bar).",
        "Metric": "Average Time-to-Fill",
        "Metric Description": "Average days from requisition approval to offer acceptance. Track by role level and function. Industry benchmark: 30-45 days average.",
        "Unit": "Days",
        "Target": "<45 days (avg), <30 for critical roles",
        "Instructions": "Measure from req approval date to offer acceptance date. Calculate rolling average. Segment by role level (IC, Manager, Senior) and function. Monthly tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Talent Acquisition > Offer Acceptance Rate",
        "Description": "The percentage of job offers accepted by candidates, reflecting employer brand strength, competitive positioning, and recruiting effectiveness",
        "Business Drivers": "Employer Brand & Competitiveness",
        "Business Drivers Description": "High offer acceptance indicates: strong employer brand, competitive compensation, effective candidate experience, good role match. Low acceptance = brand/comp problems or poor targeting.",
        "Performance Factors": "High Acceptance Rate",
        "Performance Factors Description": "Strong offer acceptance shows: >80% acceptance rate, competitive offers rarely declined, candidate enthusiasm, strong close process, minimal negotiation.",
        "Risk Factors": "High Offer Declines",
        "Risk Factors Description": "Low acceptance (<70%) indicates: weak employer brand, uncompetitive offers, poor candidate experience, wrong target candidates, lose talent war. Very expensive (wasted recruiting effort).",
        "Metric": "Offer Acceptance Rate",
        "Metric Description": "# of offers accepted / # of offers extended. Track by role level, function, and decline reasons. >80% is strong, <70% indicates problems.",
        "Unit": "Percentage (%)",
        "Target": ">80%",
        "Instructions": "Track all offers extended and outcomes (accepted/declined). Calculate acceptance rate monthly. Survey declined candidates for reasons. Segment by role and function."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Talent Acquisition > New Hire Retention",
        "Description": "The percentage of new hires who remain with the organization after 12 and 18 months, indicating hiring fit and onboarding effectiveness",
        "Business Drivers": "ROI on Hiring Investment",
        "Business Drivers Description": "New hire retention validates hiring quality and onboarding. Retention <18 months = failed investment (recruiting + training + opportunity cost). Strong retention = good fit.",
        "Performance Factors": "High New Hire Retention",
        "Performance Factors Description": "Strong retention shows: >90% at 12 months, >85% at 18 months, positive exit survey feedback, regrettable losses rare, good onboarding experience.",
        "Risk Factors": "Early Attrition",
        "Risk Factors Description": "Early turnover (<18 mo) indicates: poor culture fit, mis-sold role, bad manager match, onboarding failure, better opportunity found. Very expensive - total loss on investment.",
        "Metric": "New Hire 12-Month Retention Rate",
        "Metric Description": "% of new hires still employed 12 months after start date. Also track 18-month rate. Distinguish voluntary vs involuntary and regrettable vs non-regrettable.",
        "Unit": "Percentage (%)",
        "Target": ">90% at 12 mo, >85% at 18 mo",
        "Instructions": "Track cohort retention: of all employees hired in [period], what % remain 12 months later? Calculate quarterly by cohort. Investigate departures <18 months."
    },

    # LEVEL 2: PERFORMANCE MANAGEMENT (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "People > Performance Management",
        "Description": "The systems and practices for setting expectations, providing feedback, assessing performance, and enabling continuous improvement",
        "Business Drivers": "Execution & Accountability",
        "Business Drivers Description": "Effective performance management drives: clear accountability, rapid feedback loops, continuous improvement, A-player retention (via recognition), C-player improvement or exit.",
        "Performance Factors": "Effective Performance Systems",
        "Performance Factors Description": "Strong performance management shows: clear goals (OKRs), frequent feedback (weekly 1-on-1s), fair calibration, differentiated consequences, manager capability, employee trust in process.",
        "Risk Factors": "Poor Performance Management",
        "Risk Factors Description": "Weak performance systems drive: unclear expectations, feedback gaps, surprises at review, ratings inflation, low accountability, C-player retention, A-player frustration.",
        "Metric": "Performance Management Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Goal Clarity + Feedback Quality + Rating Differentiation + Manager Capability. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores from employee surveys and system data. Strong performance cultures score >75."
    },

    # LEVEL 3: Performance Management Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "People > Performance Management > Goal Clarity",
        "Description": "The extent to which employees have clear, measurable goals aligned with organizational objectives and understand priorities",
        "Business Drivers": "Alignment & Focus",
        "Business Drivers Description": "Clear goals drive: strategic alignment, prioritization, accountability, measurement, motivation. Without clear goals, effort diffuses and accountability evaporates.",
        "Performance Factors": "Clear, Measurable Goals",
        "Performance Factors Description": "Strong goal clarity shows: OKRs or similar framework, measurable objectives, organizational cascade, quarterly refresh, >90% employees can state their goals.",
        "Risk Factors": "Goal Ambiguity",
        "Risk Factors Description": "Unclear goals drive: misaligned effort, conflicting priorities, no accountability, inability to measure performance, employee frustration ('I don't know what success looks like').",
        "Metric": "Goal Clarity Score",
        "Metric Description": "Survey item: 'I have clear, measurable goals that are aligned with organizational priorities.' 5-point Likert scale. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">80% favorable",
        "Instructions": "Include in engagement or performance survey. Calculate % 'agree' or 'strongly agree.' Validate by spot-checking: can employees state their top 3 goals?"
    },
    {
        "Level": 3,
        "Hierarchy": "People > Performance Management > Feedback Quality",
        "Description": "The frequency, specificity, and helpfulness of performance feedback employees receive from managers and peers",
        "Business Drivers": "Development & Performance Improvement",
        "Business Drivers Description": "Quality feedback enables: rapid learning, course correction, skill development, confidence building, performance improvement. Feedback is the breakfast of champions.",
        "Performance Factors": "Frequent, Specific Feedback",
        "Performance Factors Description": "Strong feedback cultures show: weekly 1-on-1s, real-time feedback, specific and actionable, balanced (strengths + development), peer feedback, 360 reviews.",
        "Risk Factors": "Feedback Gaps",
        "Risk Factors Description": "Poor feedback drives: slow learning, repeated mistakes, performance surprises at review, low engagement, misaligned effort, talent loss (ambitious leave without feedback).",
        "Metric": "Feedback Quality Score",
        "Metric Description": "Survey items: 'I receive frequent, specific, helpful feedback on my performance' and 'My manager provides feedback that helps me improve.' 5-point Likert. % favorable.",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in manager effectiveness survey. Calculate % 4-5 responses. Validate by tracking: 1-on-1 frequency, 360 review completion rates."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Performance Management > Rating Differentiation",
        "Description": "The degree to which performance ratings accurately differentiate between high, solid, and low performers rather than inflating or compressing scores",
        "Business Drivers": "Meritocracy & Accountability",
        "Business Drivers Description": "Rating differentiation enables: rewarding top performers (retention), addressing low performers (accountability), calibrated decisions (promotions, comp), credible performance culture.",
        "Performance Factors": "Meaningful Differentiation",
        "Performance Factors Description": "Strong differentiation shows: normal-ish distribution (not all 'meets'), top 10-20% clearly identified, bottom 5-10% in development plans, calibration sessions, forced ranking or guidelines.",
        "Risk Factors": "Ratings Inflation",
        "Risk Factors Description": "Inflated ratings (everyone 'meets or exceeds') drive: undifferentiated rewards (A-players unhappy), C-players retained, credibility loss, inability to make tough calls.",
        "Metric": "Performance Rating Distribution",
        "Metric Description": "Distribution of performance ratings. Healthy: 10-20% exceeds, 60-70% meets, 10-20% below/needs improvement. Flag if >80% 'meets or exceeds' (likely inflation).",
        "Unit": "Percentage distribution",
        "Target": "10-20% exceeds, 60-70% meets, 10-20% below",
        "Instructions": "Calculate % of employees in each rating category. Compare to normal distribution. If >80% 'meets or exceeds,' likely ratings inflation. Investigate calibration."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Performance Management > Manager Capability",
        "Description": "The skill and effectiveness of managers in having performance conversations, providing feedback, and developing their teams",
        "Business Drivers": "Manager Effectiveness",
        "Business Drivers Description": "Manager capability is #1 driver of performance management effectiveness. Strong managers drive: team performance, talent development, engagement, retention. 'People leave managers, not companies.'",
        "Performance Factors": "Skilled Managers",
        "Performance Factors Description": "Effective managers show: regular 1-on-1s, candid feedback, development focus, differentiated management (adapt to individuals), performance coaching skills, conflict resolution.",
        "Risk Factors": "Poor Manager Skills",
        "Risk Factors Description": "Weak managers drive: low team engagement, talent attrition, poor performance, avoided difficult conversations, team dysfunction, employees leave for better managers.",
        "Metric": "Manager Effectiveness Score",
        "Metric Description": "Employee rating of manager effectiveness across: communication, feedback, development, recognition, goal clarity, support. 5-point Likert, % favorable.",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include manager effectiveness items in engagement survey. Calculate % favorable by manager. Flag managers <60% for coaching. Track improvement."
    },

    # LEVEL 2: COMPENSATION & BENEFITS (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "People > Compensation & Benefits",
        "Description": "The total rewards package including base pay, incentives, equity, benefits, and perks offered to attract, retain, and motivate employees",
        "Business Drivers": "Attraction, Retention & Motivation",
        "Business Drivers Description": "Competitive total rewards attract talent, retain top performers, motivate performance, and signal value. Under-market comp drives attrition and B-player attraction. Over-market comp wastes resources.",
        "Performance Factors": "Competitive Total Rewards",
        "Performance Factors Description": "Strong compensation shows: market 50th-75th percentile, pay equity achieved, variable pay tied to performance, comprehensive benefits, low comp-driven attrition.",
        "Risk Factors": "Uncompetitive or Inequitable Pay",
        "Risk Factors Description": "Poor compensation drives: talent loss (to higher payers), low offer acceptance, pay equity issues (legal/brand risk), motivation problems, inability to attract A-players.",
        "Metric": "Compensation & Benefits Index",
        "Metric Description": "Composite of 4 sub-elements: Market Competitiveness + Pay Equity + Variable Pay Effectiveness + Benefits Satisfaction. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining compensation data analysis and employee surveys. Update annually post-compensation cycle."
    },

    # LEVEL 3: Compensation & Benefits Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "People > Compensation & Benefits > Market Competitiveness",
        "Description": "How employee compensation compares to relevant market benchmarks for similar roles, skills, and locations",
        "Business Drivers": "Attraction & Retention",
        "Business Drivers Description": "Market-competitive pay attracts talent in tight markets, retains top performers, and ensures high offer acceptance. Under-market drives attrition and recruiting struggles.",
        "Performance Factors": "50th-75th Percentile Positioning",
        "Performance Factors Description": "Competitive positioning: 50th percentile for average performers, 75th for top performers, adjust by role criticality. Use reputable comp surveys (Radford, Mercer, Comptryx).",
        "Risk Factors": "Below-Market Compensation",
        "Risk Factors Description": "Sub-market pay (<40th percentile) drives: talent loss, low offer acceptance, difficulty hiring, B/C player attraction, retention of only non-marketable employees.",
        "Metric": "Compa-Ratio",
        "Metric Description": "Average employee pay / market median pay for role. 1.0 = at market, <0.9 = below market, >1.1 = above market. Calculate by role level and function.",
        "Unit": "Ratio",
        "Target": "0.95 - 1.05 (at market)",
        "Instructions": "Benchmark all roles to market data (use Radford, Mercer, or similar). Calculate actual pay / benchmark median. Flag roles <0.9 or >1.1 for adjustment. Update annually."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Compensation & Benefits > Pay Equity",
        "Description": "The fairness and equity of compensation across demographic groups, ensuring equal pay for equal work regardless of gender, race, or other factors",
        "Business Drivers": "Legal Compliance & Trust",
        "Business Drivers Description": "Pay equity ensures: legal compliance (Equal Pay Act), employee trust, employer brand protection, avoidance of costly litigation, diverse talent retention.",
        "Performance Factors": "Equitable Pay",
        "Performance Factors Description": "Strong pay equity shows: <5% unexplained pay gaps, regular equity audits, proactive adjustments, transparent pay practices, no discrimination claims.",
        "Risk Factors": "Pay Inequity",
        "Risk Factors Description": "Pay gaps drive: discrimination claims (expensive), brand damage, employee distrust, diverse talent attrition, regulatory risk (some jurisdictions require public reporting).",
        "Metric": "Pay Equity Gap",
        "Metric Description": "Regression-adjusted pay gap: actual pay vs predicted pay controlling for role, level, tenure, performance, location. Gap <5% is acceptable. >10% indicates inequity.",
        "Unit": "Percentage (%)",
        "Target": "<5% adjusted gap",
        "Instructions": "Run regression analysis: pay ~ role + level + tenure + performance + location + demographics. Calculate residual gap for protected groups. If >5%, conduct equity adjustments."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Compensation & Benefits > Variable Pay Effectiveness",
        "Description": "The degree to which variable compensation (bonuses, commissions, equity) is tied to performance and drives desired behaviors",
        "Business Drivers": "Performance Motivation & Alignment",
        "Business Drivers Description": "Effective variable pay: aligns employee incentives with company goals, rewards high performance, motivates discretionary effort, attracts performance-oriented talent.",
        "Performance Factors": "Performance-Linked Variable Pay",
        "Performance Factors Description": "Strong variable pay shows: clear metrics, significant upside (20-40% of total), performance differentiation (3x variance high/low), timely payout, trust in fairness.",
        "Risk Factors": "Ineffective or Disconnected Incentives",
        "Risk Factors Description": "Poor variable pay drives: misaligned behavior, entitlement (guaranteed bonuses), gamesmanship, complexity confusion, low motivation (too small or disconnected from performance).",
        "Metric": "Variable Pay as % of Total Comp",
        "Metric Description": "Average variable compensation (bonus + commission + equity value) as % of total compensation. Should vary by role (sales high, admin low).",
        "Unit": "Percentage (%)",
        "Target": "15-40% depending on role",
        "Instructions": "Calculate total variable comp (actual payouts) / total comp. Segment by role type: Exec (30-50%), Sales (40-60%), Professional (15-25%), Operations (10-15%). Annual tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Compensation & Benefits > Benefits Satisfaction",
        "Description": "Employee satisfaction with the benefits package including health insurance, retirement, paid time off, and other perks",
        "Business Drivers": "Retention & Total Rewards Value",
        "Business Drivers Description": "Benefits drive: talent attraction (especially experienced hires with families), retention, financial wellbeing, work-life balance, total rewards perception (base + benefits).",
        "Performance Factors": "Comprehensive, Valued Benefits",
        "Performance Factors Description": "Strong benefits show: competitive health coverage, employer retirement match (>3%), generous PTO (20+ days), flexibility, high employee satisfaction (>75%).",
        "Risk Factors": "Poor Benefits",
        "Risk Factors Description": "Weak benefits drive: talent loss (especially to large cos with better benefits), low offer acceptance, financial stress, poor work-life balance, reduced total rewards value.",
        "Metric": "Benefits Satisfaction Score",
        "Metric Description": "Survey item: 'I am satisfied with my total benefits package (health, retirement, PTO, perks).' 5-point Likert. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in compensation or total rewards survey (annually). Calculate % favorable. Also track utilization rates (unused PTO indicates potential problem)."
    },

    # LEVEL 2: CAREER DEVELOPMENT (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "People > Career Development",
        "Description": "Opportunities and support for employee growth, skill development, advancement, and career progression within the organization",
        "Business Drivers": "Engagement & Talent Retention",
        "Business Drivers Description": "Career development drives: engagement (top 3 factor), retention (especially high-potentials), capability building, internal mobility (reduces hiring need), bench strength for succession.",
        "Performance Factors": "Strong Development Culture",
        "Performance Factors Description": "Strong development shows: clear career paths, internal promotion rate >60%, learning investment >2% payroll, mentoring/coaching, development plans for all, high growth opportunity ratings.",
        "Risk Factors": "Development Gaps & Retention Loss",
        "Risk Factors Description": "Poor development drives: ambitious talent leaves (for growth elsewhere), skill stagnation, low internal mobility (hiring costs up), weak bench strength, engagement loss.",
        "Metric": "Career Development Index",
        "Metric Description": "Composite of 4 sub-elements: Growth Opportunity Perception + Internal Promotion Rate + Development Plan Coverage + Skills Development Investment. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining survey data (perception) and system data (promotions, plans, investment). Strong development cultures score >75."
    },

    # LEVEL 3: Career Development Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "People > Career Development > Growth Opportunity Perception",
        "Description": "Employee perception of career growth and advancement opportunities within the organization",
        "Business Drivers": "Ambition Retention",
        "Business Drivers Description": "Perceived growth opportunity is top 3 driver of engagement and #1 reason ambitious talent stays or leaves. Strong opportunity perception retains high-performers and attracts achievers.",
        "Performance Factors": "Strong Opportunity Perception",
        "Performance Factors Description": "High opportunity perception shows: >70% see growth path, visible promotions, career conversations common, development emphasized, examples of growth stories.",
        "Risk Factors": "Perceived Ceiling",
        "Risk Factors Description": "Low opportunity perception drives: high-potential attrition (leave for growth), ambition dampening, external hiring over internal promotion, talent stagnation.",
        "Metric": "Growth Opportunity Score",
        "Metric Description": "Survey item: 'I see good opportunities for career growth and advancement in this organization.' 5-point Likert scale. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">70% favorable",
        "Instructions": "Include in engagement survey. Calculate % favorable. Critical to segment: high-performers and high-potentials should score >80%. If not, investigate barriers."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Career Development > Internal Promotion Rate",
        "Description": "The percentage of role vacancies filled by internal candidates through promotion or lateral development moves",
        "Business Drivers": "Retention & Cost Efficiency",
        "Business Drivers Description": "Internal mobility: validates development (visible growth), retains talent (less external job seeking), reduces hiring costs, preserves institutional knowledge, faster time-to-productivity.",
        "Performance Factors": "High Internal Mobility",
        "Performance Factors Description": "Strong internal promotion: >60% of roles filled internally, visible career progression, lateral moves common (skill building), succession bench strength.",
        "Risk Factors": "Low Internal Mobility",
        "Risk Factors Description": "Low internal promotion (<40%) signals: limited opportunities, external hiring preference, development failure, retention risk (leave for promotion elsewhere), high hiring costs.",
        "Metric": "Internal Promotion Rate",
        "Metric Description": "% of role vacancies filled by internal candidates (promotion or lateral move). Benchmark: >60% is healthy. <40% indicates problem.",
        "Unit": "Percentage (%)",
        "Target": ">60% of vacancies filled internally",
        "Instructions": "Track all role fills: # internal / total fills. Count promotions and lateral developmental moves. Exclude backfills (same role). Calculate rolling 12-month rate."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Career Development > Development Plan Coverage",
        "Description": "The percentage of employees with documented, actively managed development plans aligned with career goals and business needs",
        "Business Drivers": "Systematic Development",
        "Business Drivers Description": "Development plans drive: focused learning, accountability for growth, manager-employee alignment, career readiness, systematic capability building vs ad-hoc.",
        "Performance Factors": "Universal Development Planning",
        "Performance Factors Description": "Strong development planning shows: 100% employees have plans, documented in system, quarterly reviews, mix of on-job/formal learning, manager accountability.",
        "Risk Factors": "No Development Plans",
        "Risk Factors Description": "Missing development plans signal: development not prioritized, ad-hoc learning (inefficient), no accountability, career frustration, managers unprepared for development conversations.",
        "Metric": "Development Plan Coverage Rate",
        "Metric Description": "% of employees with active, documented development plan in HR system. Target: 100% for high-performers/high-potentials, >80% for all.",
        "Unit": "Percentage (%)",
        "Target": "100% HiPo, >80% all employees",
        "Instructions": "Track development plan documentation in performance management system. Calculate % with active plan. Flag managers with low team coverage. Quarterly tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Career Development > Skills Development Investment",
        "Description": "Average hours and investment per employee in formal training, development programs, and skill-building activities",
        "Business Drivers": "Capability Building",
        "Business Drivers Description": "Skills investment builds: current capabilities (job performance), future capabilities (strategic readiness), employee engagement (growth signal), competitive advantage (learning org).",
        "Performance Factors": "Substantial Development Investment",
        "Performance Factors Description": "Strong skills investment shows: >40 hours/year per employee, mix of formal training and on-job development, role-specific and leadership programs, learning time protected.",
        "Risk Factors": "Underinvestment in Development",
        "Risk Factors Description": "Low development investment (<20 hrs/year) drives: skill obsolescence, competitive disadvantage, low engagement, external hiring necessity (vs build), talent loss.",
        "Metric": "Training Hours per Employee per Year",
        "Metric Description": "Total annual training hours delivered / average employee count. Include formal training, workshops, conferences, online learning. Benchmark: 40+ hours/year.",
        "Unit": "Hours per employee per year",
        "Target": ">40 hours/year",
        "Instructions": "Track all formal development activities: in-person training, e-learning, conferences, workshops. Sum total hours, divide by average headcount. Segment by role level."
    },

    # LEVEL 2: EMPLOYEE WELLBEING (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "People > Employee Wellbeing",
        "Description": "The physical, mental, emotional, and financial health of employees and the organizational practices that support work-life balance and overall wellness",
        "Business Drivers": "Productivity & Retention",
        "Business Drivers Description": "Employee wellbeing drives: sustained productivity (burnout reduces output 30-50%), lower healthcare costs, higher engagement, better retention, reduced absenteeism, safety.",
        "Performance Factors": "Strong Wellbeing Support",
        "Performance Factors Description": "Strong wellbeing shows: low burnout rates, comprehensive wellness programs, flexible work arrangements, manageable workload, mental health support, low absenteeism (<3%).",
        "Risk Factors": "Burnout & Health Issues",
        "Risk Factors Description": "Poor wellbeing drives: burnout epidemic (exhaustion, cynicism, inefficacy), turnover, absenteeism, presenteeism (at work but unproductive), healthcare cost spikes, safety incidents.",
        "Metric": "Employee Wellbeing Index",
        "Metric Description": "Composite of 4 sub-elements: Burnout Risk + Work-Life Balance + Wellbeing Program Engagement + Absenteeism Rate. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining survey data (burnout, balance) and system data (absenteeism). Strong wellbeing cultures score >75."
    },

    # LEVEL 3: Employee Wellbeing Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "People > Employee Wellbeing > Burnout Risk",
        "Description": "The level of chronic workplace stress manifesting as exhaustion, cynicism, and reduced professional efficacy (Maslach Burnout Inventory dimensions)",
        "Business Drivers": "Sustained Performance",
        "Business Drivers Description": "Preventing burnout sustains: long-term productivity (burned out employees 30-50% less productive), retention (burnout #1 predictor of turnover), quality, safety, mental health.",
        "Performance Factors": "Low Burnout Prevalence",
        "Performance Factors Description": "Healthy burnout levels: <20% employees at burnout risk, manageable workload, adequate resources, recovery time protected, sustainable pace culture.",
        "Risk Factors": "Burnout Epidemic",
        "Risk Factors Description": "High burnout (>30% at risk) drives: productivity collapse, quality issues, turnover wave, absenteeism, health claims, safety incidents, toxic culture, talent loss.",
        "Metric": "Burnout Risk Score",
        "Metric Description": "% of employees scoring high risk on validated burnout assessment (e.g., Maslach Burnout Inventory). Measure: exhaustion, cynicism, inefficacy. <20% at risk is target.",
        "Unit": "Percentage (% at risk)",
        "Target": "<20% at burnout risk",
        "Instructions": "Use validated burnout scale (MBI or similar). Survey annually or biannually. Calculate % scoring high on exhaustion AND (cynicism OR inefficacy). Flag teams >30%."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Employee Wellbeing > Work-Life Balance",
        "Description": "Employee perception of balance between work demands and personal life, including flexibility, workload manageability, and time for recovery",
        "Business Drivers": "Retention & Sustained Performance",
        "Business Drivers Description": "Work-life balance drives: retention (especially working parents), sustained performance (vs sprint-crash), attraction (top consideration for candidates), health, wellbeing.",
        "Performance Factors": "Strong Balance Perception",
        "Performance Factors Description": "Strong work-life balance shows: >70% favorable ratings, flexible work arrangements, reasonable hours (not 60+ week norms), vacation encouraged/used, asynchronous work enabled.",
        "Risk Factors": "Work-Life Conflict",
        "Risk Factors Description": "Poor balance drives: burnout, turnover (especially caregivers), health issues, resentment, reduced engagement, difficulty attracting talent (work-life top 3 consideration).",
        "Metric": "Work-Life Balance Score",
        "Metric Description": "Survey item: 'I am able to maintain a healthy balance between my work and personal life.' 5-point Likert scale. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">70% favorable",
        "Instructions": "Include in engagement or wellbeing survey. Calculate % favorable. Segment by role, level, function. Validate with utilization data (unused PTO indicates problem)."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Employee Wellbeing > Wellbeing Program Engagement",
        "Description": "Employee participation in and satisfaction with organizational wellbeing programs including fitness, mental health, financial wellness, and EAP services",
        "Business Drivers": "Preventive Health",
        "Business Drivers Description": "Wellbeing program engagement drives: preventive health (reduces long-term costs), stress management, financial wellbeing, culture signal (care about people), early issue detection.",
        "Performance Factors": "High Program Utilization",
        "Performance Factors Description": "Strong wellbeing programs show: >40% participation, diverse offerings (physical, mental, financial wellness), accessible (on-site, virtual), destigmatized (leadership participates).",
        "Risk Factors": "Low Engagement or Unavailability",
        "Risk Factors Description": "Unused wellbeing programs signal: lack of awareness, stigma (especially mental health), poor program design, access barriers, culture doesn't support use (too busy).",
        "Metric": "Wellbeing Program Participation Rate",
        "Metric Description": "% of employees who participated in at least one wellbeing program activity in past 12 months. Include: fitness, EAP, financial wellness, mental health, workshops.",
        "Unit": "Percentage (%)",
        "Target": ">40% participation",
        "Instructions": "Track participation across all wellbeing programs: fitness center, EAP usage, wellness workshops, financial counseling, meditation apps, etc. Calculate % with any participation."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Employee Wellbeing > Absenteeism Rate",
        "Description": "The percentage of scheduled workdays lost to unplanned absences, indicating health issues, engagement problems, or work avoidance",
        "Business Drivers": "Productivity & Cost",
        "Business Drivers Description": "Low absenteeism sustains: team productivity (no disruption), project timelines, costs (temp coverage, overtime), morale (absent colleagues burden team).",
        "Performance Factors": "Low Absenteeism",
        "Performance Factors Description": "Healthy absenteeism: <3% unplanned absence rate, consistent patterns (not Monday/Friday spikes), short durations (not chronic), declining trend.",
        "Risk Factors": "High or Rising Absenteeism",
        "Risk Factors Description": "High absenteeism (>5%) signals: health issues (physical/mental), low engagement (avoidance), burnout, workplace safety issues, toxic culture. Very costly.",
        "Metric": "Unplanned Absenteeism Rate",
        "Metric Description": "Unplanned absence days / total scheduled workdays. Exclude planned PTO, holidays. Industry avg: 2-3%. >5% indicates problem.",
        "Unit": "Percentage (%)",
        "Target": "<3%",
        "Instructions": "Track unplanned absences separately from planned PTO. Calculate: unplanned absence days / (employees × workdays). Monitor trends and patterns (day-of-week, seasonal)."
    },

    # LEVEL 2: WORKFORCE PLANNING (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "People > Workforce Planning",
        "Description": "Strategic planning for future workforce needs including succession, skills forecasting, capacity planning, and organizational design",
        "Business Drivers": "Strategic Readiness & Risk Mitigation",
        "Business Drivers Description": "Workforce planning ensures: capabilities align with strategy, key roles covered (succession), scalability (hiring ahead of demand), risk mitigation (key person dependencies identified).",
        "Performance Factors": "Proactive Workforce Planning",
        "Performance Factors Description": "Strong workforce planning shows: 3-year workforce plans, succession coverage >80% for critical roles, skills gap analysis, capacity modeling, org design aligned to strategy.",
        "Risk Factors": "Reactive Staffing & Succession Gaps",
        "Risk Factors Description": "Weak workforce planning drives: scrambled hiring (behind demand), succession failures (key role vacancies), skills gaps prevent strategy execution, key person risks.",
        "Metric": "Workforce Planning Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Succession Coverage + Skills Gap Analysis + Capacity Planning + Organizational Design Alignment. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores. Combine system data (succession coverage, skills assessments) with planning process maturity assessment. Update annually."
    },

    # LEVEL 3: Workforce Planning Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "People > Workforce Planning > Succession Coverage",
        "Description": "The percentage of critical roles with identified, ready-now or ready-soon successors who can step into the role with minimal disruption",
        "Business Drivers": "Continuity & Risk Mitigation",
        "Business Drivers Description": "Succession planning mitigates: key person risk (sudden departure), business continuity, institutional knowledge loss, scrambled external hiring, team disruption.",
        "Performance Factors": "Strong Succession Bench",
        "Performance Factors Description": "Strong succession shows: >80% critical roles covered (2+ successors), readiness assessments current, development plans for successors, emergency succession plans.",
        "Risk Factors": "Succession Gaps",
        "Risk Factors Description": "Poor succession coverage (<50%) drives: key role vacancy risks, prolonged vacancies, emergency external hires, knowledge loss, business disruption, board/investor concern.",
        "Metric": "Succession Coverage Rate",
        "Metric Description": "% of critical roles with at least one identified successor rated 'ready now' or 'ready in 1-2 years.' Critical roles = VP+, revenue-critical, specialized expertise.",
        "Unit": "Percentage (%)",
        "Target": ">80% of critical roles covered",
        "Instructions": "Identify critical roles (typically VP+, critical functions). For each, identify successors with readiness ratings. Calculate % with at least 1 ready-now/soon successor. Update biannually."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Workforce Planning > Skills Gap Analysis",
        "Description": "The systematic identification of differences between current workforce skills and capabilities required for future strategy execution",
        "Business Drivers": "Strategic Capability",
        "Business Drivers Description": "Skills gap analysis enables: proactive capability building (training, hiring), strategic readiness, investment prioritization, build-vs-buy decisions, competitive advantage.",
        "Performance Factors": "Current Skills Gap Assessment",
        "Performance Factors Description": "Strong skills planning shows: formal gap analysis completed, priority skills identified, build/buy/partner strategies defined, investments aligned, gap closure tracked.",
        "Risk Factors": "Unknown Skills Gaps",
        "Risk Factors Description": "No skills gap analysis risks: strategy execution failures ('we don't have the skills'), reactive scrambling, missed opportunities, competitive disadvantage, failed transformations.",
        "Metric": "Skills Gap Analysis Currency",
        "Metric Description": "Recency of formal skills gap analysis aligned to strategic plan. Best practice: annual refresh. Score: <12 months = 100, 12-24 months = 70, >24 months = 40, never = 0.",
        "Unit": "Score (0-100)",
        "Target": ">90 (current <12 months)",
        "Instructions": "Track date of last comprehensive skills gap analysis. Must align to strategic plan and cover: current state skills inventory, future state requirements, gap analysis, action plan."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Workforce Planning > Capacity Planning",
        "Description": "Forecasting future headcount needs by function and timing to enable proactive hiring and avoid capacity constraints or overstaffing",
        "Business Drivers": "Scalability & Cost Management",
        "Business Drivers Description": "Capacity planning enables: proactive hiring (ahead of demand), cost management (avoid overhiring), scalability (growth not constrained by people), team workload management.",
        "Performance Factors": "Proactive Capacity Planning",
        "Performance Factors Description": "Strong capacity planning shows: 12-month rolling headcount forecasts by function, scenario planning (growth targets), hiring lead times factored, attrition assumed, approval gates.",
        "Risk Factors": "Reactive Staffing",
        "Risk Factors Description": "No capacity planning drives: hiring lags demand (growth constrained), team overload (burnout), or overhiring (cash burn), scrambled recruiting, poor hiring quality.",
        "Metric": "Capacity Planning Lead Time",
        "Metric Description": "# of months of forward headcount planning. Best practice: 12-month rolling forecast updated quarterly. Score based on forward visibility: 12+ mo = excellent, 6-12 = good, 3-6 = fair, <3 = poor.",
        "Unit": "Months of forward planning",
        "Target": ">12 months rolling forecast",
        "Instructions": "Assess headcount planning process. Do you have documented forecasts >12 months forward? Updated quarterly? By function? Scenario planning? Score maturity 0-100."
    },
    {
        "Level": 3,
        "Hierarchy": "People > Workforce Planning > Organizational Design Alignment",
        "Description": "The degree to which organizational structure, roles, and reporting relationships align with strategy and enable efficient execution",
        "Business Drivers": "Execution Efficiency",
        "Business Drivers Description": "Org design alignment enables: clear accountability, efficient decision-making, minimal handoffs, customer-centric structure, strategy execution, scalability.",
        "Performance Factors": "Strategy-Aligned Structure",
        "Performance Factors Description": "Strong org design shows: structure follows strategy (not vice versa), clear accountability, appropriate spans of control (5-10), minimal layers (<6 CEO to IC), regular redesign.",
        "Risk Factors": "Misaligned or Outdated Structure",
        "Risk Factors Description": "Poor org design drives: slow decisions, unclear accountability, siloed execution, customer friction, strategy-structure misfit (structure constrains strategy).",
        "Metric": "Organizational Design Alignment Score",
        "Metric Description": "Leadership assessment: 'Our organizational structure enables efficient execution of our strategy.' 5-point Likert. Also track: span of control avg, layers from CEO to IC.",
        "Unit": "Score (1-5)",
        "Target": ">4.0 (aligned structure)",
        "Instructions": "Survey senior leaders on org design effectiveness. Also calculate avg span of control (direct reports per manager) and organizational layers. Benchmark: 5-10 span, <6 layers."
    }
]
