"""
Strategic Goals Dimension Data
Expert Senior Business Analyst - 20+ years experience

This dimension measures the achievement of long-term strategic objectives,
tracking progress on multi-year initiatives, competitive positioning,
market leadership goals, capability development, and strategic partnerships.
"""

strategic_goals_data = [
    # Level 1: Dimension
    {
        "Level": 1,
        "Hierarchy": "Strategic Goals",
        "Description": "Achievement of long-term strategic objectives including vision realization, competitive positioning, market leadership, capability development, and strategic partnerships",
        "Business Drivers": "Strategy Execution",
        "Business Drivers Description": "Successful strategy execution requires clear vision, disciplined resource allocation, competitive differentiation, market positioning, capability investment, and partnership leverage to achieve sustainable competitive advantage",
        "Performance Factors": "Strong Strategic Progress",
        "Performance Factors Description": "Organizations demonstrating strong strategic progress show >80% strategic initiative on-track rate, improving competitive position, growing market share, accelerating capability development, and value-accretive partnerships",
        "Risk Factors": "Strategic Drift",
        "Risk Factors Description": "Strategic drift manifests as <50% initiatives on track, deteriorating competitive position, market share loss, capability gaps widening vs competitors, and partnership value erosion",
        "Metric": "Strategic Goals Achievement Index",
        "Metric Description": "Composite index combining vision achievement, initiative success rate, competitive position strength, market leadership indicators, capability maturity, and partnership value",
        "Unit": "Index score (0-100)",
        "Target": ">75 (strong strategic execution)",
        "Instructions": "Calculate weighted average across 6 strategic goal elements with equal weighting (16.67% each), normalized to 0-100 scale"
    },

    # Level 2: Vision Achievement (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Strategic Goals > Vision Achievement",
        "Description": "Progress toward achieving the organization's 3-5 year strategic vision including vision clarity, stakeholder alignment, milestone achievement, and vision realization",
        "Business Drivers": "Vision Clarity",
        "Business Drivers Description": "Clear, compelling vision provides direction for strategy execution, aligns stakeholder efforts, and enables measurement of long-term progress",
        "Performance Factors": "Vision On Track",
        "Performance Factors Description": "Vision on track: >80% milestones achieved, strong stakeholder alignment (>75%), clear progress metrics, and trajectory toward full realization",
        "Risk Factors": "Vision At Risk",
        "Risk Factors Description": "Vision at risk: <60% milestones achieved, weak stakeholder alignment (<50%), unclear metrics, or trajectory suggesting vision unattainable",
        "Metric": "Vision Achievement Score",
        "Metric Description": "Composite score combining milestone achievement rate, stakeholder alignment, metric clarity, and trajectory assessment",
        "Unit": "Score (0-100)",
        "Target": ">75 (vision on track)",
        "Instructions": "Assess across 4 sub-elements (vision clarity, alignment, milestones, realization), calculate weighted average"
    },

    # Level 3: Vision Achievement Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Vision Achievement > Vision Statement Clarity",
        "Description": "The clarity, specificity, and measurability of the organization's strategic vision statement, including time horizon definition and success criteria articulation",
        "Business Drivers": "Strategic Direction",
        "Business Drivers Description": "Clear vision statement provides unambiguous direction, enables consistent decision-making, and allows objective progress measurement",
        "Performance Factors": "High Clarity",
        "Performance Factors Description": "High clarity: specific outcomes defined, measurable success criteria, clear 3-5 year horizon, compelling narrative, widely understood",
        "Risk Factors": "Low Clarity",
        "Risk Factors Description": "Low clarity: vague aspirations, no measurable criteria, undefined timeframe, inconsistent interpretations, limited awareness",
        "Metric": "Vision Clarity Assessment",
        "Metric Description": "Qualitative assessment of vision statement specificity, measurability, time-boundedness, and stakeholder comprehension",
        "Unit": "Rating (1-5 scale)",
        "Target": "4-5 (high clarity)",
        "Instructions": "Evaluate vision statement against SMART criteria, survey stakeholders on comprehension and alignment"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Vision Achievement > Stakeholder Alignment",
        "Description": "The degree to which key stakeholders (board, leadership, employees, investors, partners) understand, support, and are actively working toward the strategic vision",
        "Business Drivers": "Unified Direction",
        "Business Drivers Description": "Stakeholder alignment ensures coordinated action, reduces conflicting priorities, and maximizes probability of vision achievement",
        "Performance Factors": "Strong Alignment",
        "Performance Factors Description": "Strong alignment: >75% stakeholder awareness, >70% active support, consistent resource allocation, aligned incentives, minimal conflicting initiatives",
        "Risk Factors": "Poor Alignment",
        "Risk Factors Description": "Poor alignment: <50% awareness, <40% support, competing priorities, misaligned incentives, siloed efforts undermining vision",
        "Metric": "Stakeholder Alignment Index",
        "Metric Description": "Percentage of key stakeholders demonstrating awareness, understanding, support, and aligned action toward strategic vision",
        "Unit": "Percentage (%)",
        "Target": ">75% (strong alignment)",
        "Instructions": "Survey key stakeholder groups, assess resource allocation alignment, review incentive structures, measure action consistency"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Vision Achievement > Strategic Milestone Achievement",
        "Description": "The achievement rate of defined multi-year milestones that collectively realize the strategic vision, tracking both on-time delivery and quality of outcomes",
        "Business Drivers": "Disciplined Execution",
        "Business Drivers Description": "Milestone achievement demonstrates execution capability, maintains momentum, builds confidence, and provides early warning of trajectory issues",
        "Performance Factors": "Milestones On Track",
        "Performance Factors Description": "Milestones on track: >80% achieved on time with quality, clear ownership, adequate resourcing, effective risk management",
        "Risk Factors": "Milestone Delays",
        "Risk Factors Description": "Milestone delays: <60% on time, quality compromises, unclear ownership, under-resourcing, unmanaged risks threatening vision timeline",
        "Metric": "Strategic Milestone On-Time Achievement Rate",
        "Metric Description": "Percentage of planned strategic milestones achieved on schedule with acceptable quality over trailing 12 months",
        "Unit": "Percentage (%)",
        "Target": ">80% (strong execution)",
        "Instructions": "Track major strategic milestones from strategic plan, measure on-time completion with quality gates, trend over time"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Vision Achievement > Vision Realization Progress",
        "Description": "The overall progress toward full realization of the strategic vision, assessing current state vs desired end state across all vision dimensions",
        "Business Drivers": "Long-Term Value Creation",
        "Business Drivers Description": "Vision realization creates sustainable competitive advantage, transforms organizational capabilities, and delivers long-term stakeholder value",
        "Performance Factors": "Accelerating Progress",
        "Performance Factors Description": "Accelerating progress: 40-60% vision realized (mid-plan), ahead of linear trajectory, increasing momentum, reducing uncertainty",
        "Risk Factors": "Stalled Progress",
        "Risk Factors Description": "Stalled progress: <30% realized (mid-plan), behind trajectory, slowing momentum, increasing uncertainty about achievability",
        "Metric": "Vision Realization Percentage",
        "Metric Description": "Percentage of strategic vision achieved based on weighted assessment across all vision dimensions and success criteria",
        "Unit": "Percentage (% complete)",
        "Target": "On linear trajectory (e.g., 40% at 2 of 5 years)",
        "Instructions": "Assess each vision dimension against success criteria, calculate weighted completion percentage, compare to plan timeline"
    },

    # Level 2: Strategic Initiatives (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Strategic Goals > Strategic Initiatives",
        "Description": "Performance of the portfolio of major strategic initiatives including initiative success rate, resource effectiveness, interdependency management, and value realization",
        "Business Drivers": "Portfolio Execution",
        "Business Drivers Description": "Effective initiative portfolio management ensures optimal resource allocation, manages interdependencies, delivers expected value, and adapts to changing conditions",
        "Performance Factors": "Strong Portfolio Performance",
        "Performance Factors Description": "Strong performance: >70% initiatives successful (on time, budget, value), effective resource utilization, managed interdependencies, realized benefits",
        "Risk Factors": "Portfolio Underperformance",
        "Risk Factors Description": "Underperformance: <50% initiatives successful, resource constraints, unmanaged interdependencies, unrealized benefits, mounting technical debt",
        "Metric": "Strategic Initiative Success Rate",
        "Metric Description": "Percentage of strategic initiatives achieving planned outcomes on time, within budget, and delivering expected value",
        "Unit": "Percentage (%)",
        "Target": ">70% (strong execution)",
        "Instructions": "Track major strategic initiatives through completion, assess against time/budget/value criteria, calculate success rate"
    },

    # Level 3: Strategic Initiatives Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Initiatives > Initiative Portfolio Health",
        "Description": "The overall health of the strategic initiative portfolio including active initiative count, portfolio balance, resource allocation, and alignment to strategic priorities",
        "Business Drivers": "Strategic Focus",
        "Business Drivers Description": "Healthy portfolio maintains strategic focus, balances short and long-term value, allocates resources to highest priorities, and avoids over-commitment",
        "Performance Factors": "Healthy Portfolio",
        "Performance Factors Description": "Healthy portfolio: 5-10 active strategic initiatives, balanced across strategic pillars, 80% resources on top priorities, clear governance",
        "Risk Factors": "Unhealthy Portfolio",
        "Risk Factors Description": "Unhealthy portfolio: >15 initiatives (over-committed) or <3 (under-ambitious), imbalanced, <60% resources on priorities, weak governance",
        "Metric": "Portfolio Health Index",
        "Metric Description": "Composite index assessing initiative count, portfolio balance, resource alignment, governance effectiveness, and strategic contribution",
        "Unit": "Score (0-100)",
        "Target": ">70 (healthy portfolio)",
        "Instructions": "Assess portfolio size, balance across strategic pillars, resource allocation to priorities, governance maturity, strategic alignment"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Initiatives > Initiative Execution Excellence",
        "Description": "The quality of initiative execution including on-time delivery, budget adherence, quality of outcomes, stakeholder satisfaction, and lessons learned application",
        "Business Drivers": "Delivery Capability",
        "Business Drivers Description": "Execution excellence ensures initiatives deliver planned value on time and budget, building organizational confidence and execution capability",
        "Performance Factors": "Excellent Execution",
        "Performance Factors Description": "Excellent execution: >80% on time, >90% on budget, high quality outcomes, >85% stakeholder satisfaction, effective lessons learned",
        "Risk Factors": "Poor Execution",
        "Risk Factors Description": "Poor execution: <60% on time, significant budget overruns, quality issues, <60% stakeholder satisfaction, repeated mistakes",
        "Metric": "Initiative Execution Score",
        "Metric Description": "Composite score measuring schedule adherence, budget performance, outcome quality, stakeholder satisfaction, and continuous improvement",
        "Unit": "Score (0-100)",
        "Target": ">75 (excellent execution)",
        "Instructions": "Track each initiative against schedule/budget/quality metrics, survey stakeholders, assess lessons learned effectiveness"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Initiatives > Interdependency Management",
        "Description": "The effectiveness of managing dependencies and interdependencies between strategic initiatives, including sequencing, shared resources, and integration points",
        "Business Drivers": "Coordinated Execution",
        "Business Drivers Description": "Effective interdependency management prevents bottlenecks, optimizes shared resources, ensures proper sequencing, and maximizes synergies",
        "Performance Factors": "Well Managed",
        "Performance Factors Description": "Well managed: all interdependencies mapped, proactive coordination, optimized sequencing, integrated planning, minimal conflicts",
        "Risk Factors": "Poorly Managed",
        "Risk Factors Description": "Poorly managed: unknown interdependencies, reactive coordination, suboptimal sequencing, siloed planning, frequent resource conflicts",
        "Metric": "Interdependency Management Effectiveness",
        "Metric Description": "Assessment of interdependency identification, coordination mechanisms, sequencing optimization, and conflict resolution effectiveness",
        "Unit": "Rating (1-5 scale)",
        "Target": "4-5 (well managed)",
        "Instructions": "Map all initiative interdependencies, assess coordination effectiveness, measure conflict frequency and resolution time"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Initiatives > Value Realization",
        "Description": "The actual value delivered by strategic initiatives vs planned benefits, including financial returns, capability gains, competitive advantages, and strategic positioning improvements",
        "Business Drivers": "Return on Investment",
        "Business Drivers Description": "Value realization validates strategic investment decisions, demonstrates initiative impact, and informs future portfolio prioritization",
        "Performance Factors": "Strong Value Delivery",
        "Performance Factors Description": "Strong value: >80% planned benefits realized, measured financial returns exceeding hurdle rates, tangible capability improvements, competitive gains",
        "Risk Factors": "Weak Value Delivery",
        "Risk Factors Description": "Weak value: <60% benefits realized, returns below hurdle rates, limited capability improvement, no competitive advantage gains",
        "Metric": "Initiative Value Realization Rate",
        "Metric Description": "Percentage of planned initiative benefits actually realized and measured within expected timeframe post-implementation",
        "Unit": "Percentage (% of planned benefits)",
        "Target": ">80% (strong value delivery)",
        "Instructions": "Define measurable benefits for each initiative, track post-implementation, measure actual vs planned, calculate realization rate"
    },

    # Level 2: Competitive Position (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Strategic Goals > Competitive Position",
        "Description": "The organization's competitive standing including market position strength, differentiation effectiveness, competitive advantage sustainability, and win rates vs competitors",
        "Business Drivers": "Competitive Advantage",
        "Business Drivers Description": "Strong competitive position enables premium pricing, customer preference, market share growth, talent attraction, and superior financial returns",
        "Performance Factors": "Strengthening Position",
        "Performance Factors Description": "Strengthening position: improving win rates (>50%), clear differentiation, sustainable advantages, growing customer preference, competitor disadvantage",
        "Risk Factors": "Weakening Position",
        "Risk Factors Description": "Weakening position: declining win rates (<40%), commoditization, advantage erosion, losing customer preference, competitor advantage",
        "Metric": "Competitive Position Index",
        "Metric Description": "Composite index measuring market position, differentiation strength, advantage sustainability, and competitive win rates",
        "Unit": "Index score (0-100)",
        "Target": ">70 (strong position)",
        "Instructions": "Assess market position, win/loss analysis, differentiation factors, advantage sustainability, benchmark competitors"
    },

    # Level 3: Competitive Position Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Competitive Position > Market Position Strength",
        "Description": "The strength of the organization's position within its served markets including market share rank, competitive ranking, and position trend (strengthening/weakening)",
        "Business Drivers": "Market Power",
        "Business Drivers Description": "Strong market position provides pricing power, influences market direction, attracts best partners and talent, and creates barriers to entry",
        "Performance Factors": "Leading Position",
        "Performance Factors Description": "Leading position: Top 3 in key markets, #1 or #2 in core segments, strengthening trend, recognized market leader",
        "Risk Factors": "Weak Position",
        "Risk Factors Description": "Weak position: Outside top 5, declining rank, weakening trend, unrecognized in market, vulnerable to disruption",
        "Metric": "Market Position Rank",
        "Metric Description": "The organization's competitive ranking in key served markets by revenue, market share, or other relevant metrics",
        "Unit": "Rank (1, 2, 3, etc.)",
        "Target": "Top 3 in key markets",
        "Instructions": "Identify key served markets, research competitive rankings, track trend over time, assess position sustainability"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Competitive Position > Differentiation Effectiveness",
        "Description": "The clarity, strength, and defensibility of the organization's competitive differentiation including unique value proposition, brand positioning, and customer perception",
        "Business Drivers": "Value Uniqueness",
        "Business Drivers Description": "Effective differentiation enables premium pricing, reduces competitive intensity, builds customer loyalty, and creates sustainable advantage",
        "Performance Factors": "Strong Differentiation",
        "Performance Factors Description": "Strong differentiation: clear unique value, customer-recognized advantages, difficult to replicate, premium pricing supported, brand preference",
        "Risk Factors": "Commoditization",
        "Risk Factors Description": "Commoditization: unclear differentiation, no recognized advantages, easy to replicate, price-based competition, brand irrelevance",
        "Metric": "Differentiation Perception Score",
        "Metric Description": "Customer and market perception of the organization's differentiation strength and uniqueness vs competitors",
        "Unit": "Score (0-100)",
        "Target": ">70 (strong differentiation)",
        "Instructions": "Survey customers on differentiation perception, analyze competitive positioning, assess replication difficulty, measure price premium"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Competitive Position > Competitive Advantage Sustainability",
        "Description": "The durability and defensibility of competitive advantages including barriers to imitation, rate of advantage erosion, and new advantage development rate",
        "Business Drivers": "Long-Term Superiority",
        "Business Drivers Description": "Sustainable competitive advantages enable long-term superior returns, reduce vulnerability to competitive threats, and compound over time",
        "Performance Factors": "Sustainable Advantages",
        "Performance Factors Description": "Sustainable: high imitation barriers, slow erosion rate (<5%/year), continuous new advantage development, expanding moat",
        "Risk Factors": "Eroding Advantages",
        "Risk Factors Description": "Eroding: low barriers, rapid erosion (>15%/year), insufficient new advantage development, shrinking moat, competitive parity",
        "Metric": "Advantage Half-Life",
        "Metric Description": "The estimated time for competitive advantages to lose half their value through imitation, technology change, or market evolution",
        "Unit": "Years",
        "Target": ">5 years (sustainable)",
        "Instructions": "Identify key competitive advantages, assess imitation barriers, estimate erosion rate, calculate half-life, track new advantage pipeline"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Competitive Position > Win Rate vs Competitors",
        "Description": "The organization's success rate in competitive situations including win/loss/no-decision rates, key accounts won, and competitive displacement success",
        "Business Drivers": "Competitive Success",
        "Business Drivers Description": "High win rates validate competitive positioning, grow market share, build confidence, and demonstrate effective competitive strategy",
        "Performance Factors": "High Win Rate",
        "Performance Factors Description": "High win rate: >55% wins in competitive situations, increasing trend, particularly strong vs key competitors, winning key accounts",
        "Risk Factors": "Low Win Rate",
        "Risk Factors Description": "Low win rate: <40% wins, declining trend, losing to specific competitors repeatedly, losing key accounts, increasing no-decisions",
        "Metric": "Competitive Win Rate",
        "Metric Description": "Percentage of competitive sales situations resulting in wins (vs losses and no-decisions) over trailing 12 months",
        "Unit": "Percentage (%)",
        "Target": ">50% (competitive strength)",
        "Instructions": "Track all competitive situations, classify outcomes (win/loss/no-decision), analyze by competitor, identify win/loss factors"
    },

    # Level 2: Market Leadership (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Strategic Goals > Market Leadership",
        "Description": "The organization's position as a market leader including thought leadership, market influence, industry recognition, and leadership in innovation/standards",
        "Business Drivers": "Market Authority",
        "Business Drivers Description": "Market leadership creates customer confidence, influences market direction, attracts talent and partners, and enables premium pricing",
        "Performance Factors": "Recognized Leader",
        "Performance Factors Description": "Recognized leader: frequent industry recognition, sought-after thought leadership, market-shaping influence, innovation leadership, standard-setting",
        "Risk Factors": "Market Follower",
        "Risk Factors Description": "Market follower: limited recognition, reactive positioning, minimal market influence, innovation laggard, standard-taking",
        "Metric": "Market Leadership Index",
        "Metric Description": "Composite index measuring thought leadership, industry recognition, market influence, and innovation leadership",
        "Unit": "Index score (0-100)",
        "Target": ">70 (recognized leader)",
        "Instructions": "Assess across 4 dimensions (thought leadership, recognition, influence, innovation), calculate weighted average"
    },

    # Level 3: Market Leadership Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Market Leadership > Thought Leadership Position",
        "Description": "The organization's recognition as a thought leader including speaking engagements, publications, media presence, analyst relations, and industry advisory roles",
        "Business Drivers": "Intellectual Authority",
        "Business Drivers Description": "Thought leadership builds brand authority, influences buyer decisions, attracts talent, shapes market perception, and creates competitive separation",
        "Performance Factors": "Strong Thought Leadership",
        "Performance Factors Description": "Strong leadership: frequent tier-1 speaking (>10/year), regular publications, strong media presence, analyst recognition, advisory board roles",
        "Risk Factors": "Weak Thought Leadership",
        "Risk Factors Description": "Weak leadership: infrequent speaking (<5/year), limited publications, minimal media, unrecognized by analysts, no industry advisory roles",
        "Metric": "Thought Leadership Activity Score",
        "Metric Description": "Weighted score of speaking engagements, publications, media mentions, analyst recognition, and advisory roles",
        "Unit": "Score (0-100)",
        "Target": ">70 (strong leadership)",
        "Instructions": "Track speaking engagements (weighted by tier), publications, media mentions, analyst reports, advisory positions, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Market Leadership > Industry Recognition & Awards",
        "Description": "Industry recognition and awards received including analyst ratings (e.g., Gartner, Forrester), industry awards, customer choice awards, and workplace recognitions",
        "Business Drivers": "External Validation",
        "Business Drivers Description": "Industry recognition validates market position, builds customer confidence, attracts talent, supports premium pricing, and differentiates in competitive situations",
        "Performance Factors": "Highly Recognized",
        "Performance Factors Description": "Highly recognized: Leader/Strong Performer analyst ratings, multiple major awards, top customer choice ratings, best workplace recognition",
        "Risk Factors": "Limited Recognition",
        "Risk Factors Description": "Limited recognition: Niche/Challenger analyst ratings, few awards, below-average ratings, unrecognized as employer, invisibility in market",
        "Metric": "Recognition Index",
        "Metric Description": "Composite score of analyst positions (Gartner, Forrester, etc.), industry awards won, customer ratings, and workplace recognitions",
        "Unit": "Score (0-100)",
        "Target": ">70 (highly recognized)",
        "Instructions": "Track analyst positions, major award wins, customer choice rankings, employer awards, calculate weighted composite score"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Market Leadership > Market Influence Capability",
        "Description": "The organization's ability to influence market direction including standards participation, ecosystem influence, platform leadership, and market-shaping initiatives",
        "Business Drivers": "Market Shaping",
        "Business Drivers Description": "Market influence enables favorable standards, strong ecosystem, platform advantages, and ability to shape market evolution in organization's favor",
        "Performance Factors": "High Influence",
        "Performance Factors Description": "High influence: standards leadership roles, ecosystem orchestration, platform adoption, market-shaping initiatives, competitors following lead",
        "Risk Factors": "Low Influence",
        "Risk Factors Description": "Low influence: standards observer, weak ecosystem position, platform disadvantage, reactive market position, following competitor lead",
        "Metric": "Market Influence Assessment",
        "Metric Description": "Qualitative assessment of standards leadership, ecosystem position, platform strength, and market-shaping capability",
        "Unit": "Rating (1-5 scale)",
        "Target": "4-5 (high influence)",
        "Instructions": "Assess standards roles, ecosystem relationships, platform adoption rates, market-shaping initiative impact, competitor responses"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Market Leadership > Innovation Leadership",
        "Description": "Recognition as an innovation leader including first-to-market success, innovation awards, patent leadership, and customer perception as innovator",
        "Business Drivers": "Innovation Reputation",
        "Business Drivers Description": "Innovation leadership attracts customers, talent, and partners seeking cutting-edge solutions, enables premium pricing, and creates competitive separation",
        "Performance Factors": "Innovation Leader",
        "Performance Factors Description": "Innovation leader: frequent first-to-market, innovation awards, strong patent portfolio, >70% customers see as innovative, media coverage",
        "Risk Factors": "Innovation Laggard",
        "Risk Factors Description": "Innovation laggard: fast-follower or late, no innovation awards, weak IP, <40% see as innovative, seen as dated/conservative",
        "Metric": "Innovation Leadership Score",
        "Metric Description": "Composite score of first-to-market rate, innovation awards, patent strength, customer perception, and media innovation coverage",
        "Unit": "Score (0-100)",
        "Target": ">70 (innovation leader)",
        "Instructions": "Track first-to-market launches, innovation award wins, patent metrics, customer perception surveys, innovation media mentions"
    },

    # Level 2: Capability Development (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Strategic Goals > Capability Development",
        "Description": "Progress in developing strategic organizational capabilities including capability maturity, capability gaps vs strategy, investment effectiveness, and competitive capability benchmarking",
        "Business Drivers": "Strategic Enablement",
        "Business Drivers Description": "Strategic capability development enables strategy execution, creates competitive advantages, adapts to market change, and builds organizational resilience",
        "Performance Factors": "Accelerating Development",
        "Performance Factors Description": "Accelerating: >80% strategic capabilities improving, narrowing critical gaps, effective capability investment, closing competitor capability gap",
        "Risk Factors": "Stagnant Development",
        "Risk Factors Description": "Stagnant: <50% capabilities improving, widening strategic gaps, ineffective investment, growing competitor capability advantage",
        "Metric": "Strategic Capability Development Index",
        "Metric Description": "Composite index measuring capability maturity progress, gap closure, investment effectiveness, and competitive capability position",
        "Unit": "Index score (0-100)",
        "Target": ">75 (strong development)",
        "Instructions": "Assess capability maturity levels, track gap closure rate, measure investment ROI, benchmark competitor capabilities"
    },

    # Level 3: Capability Development Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Capability Development > Strategic Capability Maturity",
        "Description": "The maturity level of critical strategic capabilities required for strategy execution, measured against capability maturity models (e.g., Initial/Managed/Defined/Optimized)",
        "Business Drivers": "Execution Readiness",
        "Business Drivers Description": "Mature strategic capabilities enable reliable strategy execution, reduce execution risk, and create sustainable competitive advantages",
        "Performance Factors": "High Maturity",
        "Performance Factors Description": "High maturity: >75% strategic capabilities at Defined/Optimized levels, documented processes, consistent performance, continuous improvement",
        "Risk Factors": "Low Maturity",
        "Risk Factors Description": "Low maturity: >40% capabilities at Initial/Ad Hoc levels, undocumented processes, inconsistent performance, limited improvement",
        "Metric": "Average Strategic Capability Maturity Level",
        "Metric Description": "Average maturity level across all strategic capabilities using 5-level maturity model (1=Initial to 5=Optimizing)",
        "Unit": "Level (1-5)",
        "Target": ">3.5 (Defined to Optimized)",
        "Instructions": "Identify strategic capabilities from strategy, assess each using maturity model, calculate weighted average, track progress"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Capability Development > Capability Gaps vs Strategy",
        "Description": "The size and criticality of gaps between current capability levels and those required to execute strategy successfully, including gap closure timelines",
        "Business Drivers": "Risk Mitigation",
        "Business Drivers Description": "Closing critical capability gaps reduces strategy execution risk, accelerates progress, and prevents strategic failure",
        "Performance Factors": "Closing Gaps",
        "Performance Factors Description": "Closing gaps: all critical gaps identified, closure plans in place, >70% on track, no capability blockers to strategy execution",
        "Risk Factors": "Growing Gaps",
        "Risk Factors Description": "Growing gaps: unidentified critical gaps, no closure plans, <50% on track, capability gaps blocking strategy execution",
        "Metric": "Critical Capability Gap Count",
        "Metric Description": "Number of high-priority capability gaps between current state and strategic requirements, weighted by closure timeline",
        "Unit": "Count (with trend)",
        "Target": "Declining trend (gaps closing)",
        "Instructions": "Compare current capability maturity to strategic requirements, identify gaps, prioritize by impact, track gap closure progress"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Capability Development > Capability Investment Effectiveness",
        "Description": "The effectiveness of investments in capability development including ROI on capability programs, maturity improvement rate, and alignment to strategic priorities",
        "Business Drivers": "Resource Optimization",
        "Business Drivers Description": "Effective capability investment maximizes maturity improvement per dollar spent, accelerates strategic readiness, and optimizes resource allocation",
        "Performance Factors": "High Effectiveness",
        "Performance Factors Description": "High effectiveness: >5x capability investment ROI, >1 maturity level per year improvement, 80% investment on strategic priorities",
        "Risk Factors": "Low Effectiveness",
        "Risk Factors Description": "Low effectiveness: <2x ROI, <0.5 maturity level improvement, <60% investment on priorities, misdirected resources",
        "Metric": "Capability Investment ROI",
        "Metric Description": "Return on investment from capability development programs measured as value created per dollar invested",
        "Unit": "Ratio (X:1)",
        "Target": ">5:1 (high effectiveness)",
        "Instructions": "Calculate investment in capability programs, measure value delivered (cost savings, revenue, speed), calculate ROI ratio"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Capability Development > Competitive Capability Position",
        "Description": "The organization's capability levels benchmarked against key competitors, identifying capability advantages and disadvantages that impact competitive success",
        "Business Drivers": "Competitive Parity/Advantage",
        "Business Drivers Description": "Capability advantage vs competitors enables superior execution, better outcomes, and sustainable differentiation; parity prevents disadvantage",
        "Performance Factors": "Capability Advantage",
        "Performance Factors Description": "Capability advantage: lead competitors in >60% strategic capabilities, significant advantages in 2-3 critical areas, closing competitor advantages",
        "Risk Factors": "Capability Disadvantage",
        "Risk Factors Description": "Capability disadvantage: trail competitors in >40% strategic capabilities, significant gaps in critical areas, competitors widening advantages",
        "Metric": "Competitive Capability Index",
        "Metric Description": "Percentage of strategic capabilities where organization meets or exceeds competitor capability levels, weighted by strategic importance",
        "Unit": "Percentage (%)",
        "Target": ">70% (capability advantage)",
        "Instructions": "Benchmark each strategic capability vs key competitors, weight by importance, calculate advantage/disadvantage percentage"
    },

    # Level 2: Strategic Partnerships (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Strategic Goals > Strategic Partnerships",
        "Description": "The quality and value of strategic partnerships including partner portfolio health, partnership value creation, strategic alignment, and partnership innovation",
        "Business Drivers": "Ecosystem Leverage",
        "Business Drivers Description": "Strategic partnerships extend organizational capabilities, access new markets, accelerate innovation, share risks, and create competitive advantages",
        "Performance Factors": "Strong Partnership Value",
        "Performance Factors Description": "Strong value: 5-10 strategic partnerships, >80% high-value, strong alignment, active innovation collaboration, measurable value creation",
        "Risk Factors": "Weak Partnership Value",
        "Risk Factors Description": "Weak value: <3 strategic partnerships or >15 (over-committed), <50% high-value, misalignment, minimal innovation, limited measurable value",
        "Metric": "Strategic Partnership Value Index",
        "Metric Description": "Composite index measuring partnership portfolio health, value creation, strategic alignment, and innovation contribution",
        "Unit": "Index score (0-100)",
        "Target": ">75 (strong partnership value)",
        "Instructions": "Assess partnership portfolio, measure value created, evaluate alignment, track innovation outcomes, calculate composite index"
    },

    # Level 3: Strategic Partnerships Sub-elements
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Partnerships > Partnership Portfolio Health",
        "Description": "The overall health of the strategic partnership portfolio including number of partnerships, portfolio balance, partner quality, and governance effectiveness",
        "Business Drivers": "Partnership Management",
        "Business Drivers Description": "Healthy partnership portfolio balances strategic priorities, maintains manageable complexity, focuses on high-value relationships, and enables effective governance",
        "Performance Factors": "Healthy Portfolio",
        "Performance Factors Description": "Healthy: 5-10 strategic partnerships, balanced across strategic objectives, high-quality partners, clear governance, active portfolio management",
        "Risk Factors": "Unhealthy Portfolio",
        "Risk Factors Description": "Unhealthy: <3 partnerships (under-leveraged) or >15 (over-committed), imbalanced, low-quality partners, weak governance, passive management",
        "Metric": "Partnership Portfolio Health Score",
        "Metric Description": "Assessment of portfolio size, balance, partner quality, governance maturity, and active management effectiveness",
        "Unit": "Score (0-100)",
        "Target": ">75 (healthy portfolio)",
        "Instructions": "Count strategic partnerships, assess balance across objectives, evaluate partner quality, review governance, calculate composite"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Partnerships > Partnership Value Creation",
        "Description": "The tangible value created through strategic partnerships including revenue generation, cost savings, market access, capability gains, and innovation outcomes",
        "Business Drivers": "Partnership ROI",
        "Business Drivers Description": "Partnerships must create measurable value exceeding investment costs through revenue growth, efficiency gains, capability access, or innovation acceleration",
        "Performance Factors": "High Value Creation",
        "Performance Factors Description": "High value: >10x partnership ROI, significant revenue/savings, new market access, capability acceleration, breakthrough innovation",
        "Risk Factors": "Low Value Creation",
        "Risk Factors Description": "Low value: <3x ROI, limited revenue/savings, no market access, minimal capability impact, no innovation outcomes, high management overhead",
        "Metric": "Partnership Value ROI",
        "Metric Description": "Return on investment from strategic partnerships measured as value created divided by partnership investment and management costs",
        "Unit": "Ratio (X:1)",
        "Target": ">10:1 (high value)",
        "Instructions": "Calculate partnership investments and costs, measure value created (revenue, savings, capabilities, innovation), compute ROI"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Partnerships > Strategic Alignment & Commitment",
        "Description": "The alignment of partnerships to strategic objectives and mutual commitment levels including shared vision, aligned incentives, and executive engagement",
        "Business Drivers": "Partnership Success",
        "Business Drivers Description": "Strong alignment and mutual commitment enable ambitious objectives, sustained collaboration, effective problem-solving, and long-term value creation",
        "Performance Factors": "Strong Alignment",
        "Performance Factors Description": "Strong alignment: shared strategic vision, aligned KPIs and incentives, executive champions, long-term commitment, integrated planning",
        "Risk Factors": "Weak Alignment",
        "Risk Factors Description": "Weak alignment: divergent objectives, misaligned incentives, minimal executive engagement, transactional relationship, separate planning",
        "Metric": "Partnership Alignment Score",
        "Metric Description": "Assessment of strategic vision alignment, incentive alignment, executive engagement, commitment level, and planning integration",
        "Unit": "Score (0-100)",
        "Target": ">75 (strong alignment)",
        "Instructions": "Assess each partnership for vision alignment, review KPIs and incentives, measure executive engagement, evaluate commitment level"
    },
    {
        "Level": 3,
        "Hierarchy": "Strategic Goals > Strategic Partnerships > Partnership Innovation Contribution",
        "Description": "The contribution of strategic partnerships to innovation outcomes including co-innovation projects, time-to-market acceleration, innovation capability transfer, and breakthrough innovations",
        "Business Drivers": "Innovation Acceleration",
        "Business Drivers Description": "Partnership innovation leverages complementary capabilities, shares R&D costs and risks, accelerates time-to-market, and enables breakthrough innovations",
        "Performance Factors": "High Innovation Impact",
        "Performance Factors Description": "High impact: multiple co-innovation projects, >30% faster time-to-market, significant capability transfer, breakthrough innovations launched",
        "Risk Factors": "Low Innovation Impact",
        "Risk Factors Description": "Low impact: no co-innovation, no time-to-market benefit, minimal capability transfer, no breakthrough innovations, missed opportunities",
        "Metric": "Partnership Innovation Output",
        "Metric Description": "Number and value of innovations resulting from partnership collaboration, including co-developed products, capability transfers, and market breakthroughs",
        "Unit": "Count and value ($)",
        "Target": ">3 co-innovations per year with measurable value",
        "Instructions": "Track co-innovation projects, measure time-to-market impact, assess capability transfers, value breakthrough innovations"
    }
]
