"""
Third Parties Dimension Data - ENABLERS Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

third_parties_data = [
    # LEVEL 1: THIRD PARTIES DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Third Parties",
        "Description": "The ecosystem of suppliers, vendors, partners, and outsourced service providers that the organization depends on for operations, capabilities, and value delivery",
        "Business Drivers": "Extended Enterprise Performance",
        "Business Drivers Description": "Third parties provide: critical capabilities (outsourcing), cost efficiency (specialization), flexibility (variable capacity), innovation (partner ecosystem), market access, risk sharing.",
        "Performance Factors": "Healthy Partner Ecosystem",
        "Performance Factors Description": "Strong third-party management shows: strategic partnerships (not just vendors), proactive risk management, performance monitoring, collaborative relationships, innovation from ecosystem.",
        "Risk Factors": "Third-Party Failures & Dependencies",
        "Risk Factors Description": "Third-party risks include: supplier failures (business disruption), cyber breaches (supply chain attacks), quality issues, compliance violations, concentration risk, IP loss.",
        "Metric": "Overall Third-Party Health Score",
        "Metric Description": "Composite index of 6 element scores: Supplier Management + Partner Ecosystem + Outsourcing Relationships + Vendor Risk + Contract Management + Third-Party Performance. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70 (healthy third-party relationships)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Weight by strategic importance and risk exposure. Mature third-party management scores >75."
    },

    # LEVEL 2: SUPPLIER MANAGEMENT (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Third Parties > Supplier Management",
        "Description": "The processes and practices for selecting, onboarding, managing, and optimizing relationships with suppliers of goods and services",
        "Business Drivers": "Quality, Cost & Reliability",
        "Business Drivers Description": "Effective supplier management ensures: quality inputs (product/service quality depends on suppliers), cost optimization (negotiation, competition), reliable supply (business continuity).",
        "Performance Factors": "Strategic Supplier Management",
        "Performance Factors Description": "Strong supplier management shows: strategic sourcing process, supplier segmentation (critical/strategic/tactical), performance scorecards, supplier development programs, diverse supplier base.",
        "Risk Factors": "Supplier Issues & Disruptions",
        "Risk Factors Description": "Supplier management risks: quality problems (defects), supply disruptions (single source), price increases (weak negotiation), poor service, compliance violations (e.g., labor practices).",
        "Metric": "Supplier Management Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Supplier Selection Process + Supplier Diversification + Supplier Performance + Supplier Relationship Quality. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining process maturity, data on diversification and performance, and relationship survey results."
    },

    # LEVEL 3: Supplier Management Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Supplier Management > Supplier Selection Process",
        "Description": "The rigor and effectiveness of processes for evaluating, qualifying, and selecting new suppliers based on capabilities, quality, risk, and value",
        "Business Drivers": "Quality Assurance & Risk Prevention",
        "Business Drivers Description": "Rigorous supplier selection prevents: quality problems (vetted capabilities), compliance risks (due diligence), financial failures (assess stability), poor fit (wrong capabilities).",
        "Performance Factors": "Robust Selection Process",
        "Performance Factors Description": "Strong supplier selection shows: formal RFP/RFI process, multi-criteria evaluation (quality, cost, risk, capability), reference checks, financial assessment, trial periods.",
        "Risk Factors": "Weak Supplier Vetting",
        "Risk Factors Description": "Poor selection process risks: unqualified suppliers (quality issues), hidden risks (no due diligence), compliance violations, financial failures, relationship failures.",
        "Metric": "Supplier Selection Process Maturity",
        "Metric Description": "Maturity assessment (1-5): 1=Ad-hoc, 2=Informal, 3=Defined process, 4=Measured, 5=Optimized. Assess: criteria definition, evaluation rigor, due diligence, approval gates.",
        "Unit": "Level (1-5)",
        "Target": "Level 4 (Measured)",
        "Instructions": "Assess supplier selection process against maturity criteria. Score 1-5 on: documented criteria, competitive evaluation, due diligence, financial assessment, trial periods. Annual assessment."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Supplier Management > Supplier Diversification",
        "Description": "The degree to which the organization avoids over-reliance on single suppliers, maintaining alternative sources for critical goods and services",
        "Business Drivers": "Risk Mitigation & Negotiation Power",
        "Business Drivers Description": "Supplier diversification mitigates: single point of failure (supply disruption), price gouging (monopoly power), quality complacency, disaster impacts (geographic concentration).",
        "Performance Factors": "Diversified Supply Base",
        "Performance Factors Description": "Strong diversification shows: no single supplier >20% of category spend, dual sourcing for critical items, geographic diversity, regular market testing, multi-sourcing strategy.",
        "Risk Factors": "Supplier Concentration",
        "Risk Factors Description": "Over-concentration risks: supply disruption (single failure stops business), price vulnerability (no alternatives), quality issues (no competition), disaster impact.",
        "Metric": "Supplier Concentration Ratio",
        "Metric Description": "% of total supplier spend with top 1 supplier and top 3 suppliers. High concentration: Top 1 >30%, Top 3 >60%. Target: Top 1 <20%, Top 3 <50% for diversification.",
        "Unit": "Percentage (%)",
        "Target": "Top 1 <20%, Top 3 <50%",
        "Instructions": "Calculate total supplier spend. Identify top supplier and top 3 suppliers by spend. Calculate % of total. High concentration (>30% with top 1) indicates risk. Track annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Supplier Management > Supplier Performance",
        "Description": "The quality, timeliness, and reliability of supplier deliveries and services, measured against contractual commitments and service levels",
        "Business Drivers": "Operational Excellence",
        "Business Drivers Description": "Strong supplier performance ensures: quality inputs (defect-free), on-time delivery (production continuity), cost predictability, innovation contribution, competitive advantage.",
        "Performance Factors": "High Supplier Performance",
        "Performance Factors Description": "Strong performance shows: >95% on-time delivery, <2% defect rate, SLA compliance >98%, proactive communication, continuous improvement, innovation contributions.",
        "Risk Factors": "Poor Supplier Performance",
        "Risk Factors Description": "Weak supplier performance drives: production delays (late delivery), quality issues (defects), cost overruns, customer impact, competitive disadvantage.",
        "Metric": "Supplier Performance Score",
        "Metric Description": "Composite scorecard: on-time delivery % (weight 40%), quality/defect rate (30%), SLA compliance (20%), responsiveness (10%). Calculate weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">90",
        "Instructions": "Track supplier performance monthly: on-time delivery %, defect/return rate, SLA compliance %, issue resolution time. Calculate weighted composite score. Review quarterly with suppliers."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Supplier Management > Supplier Relationship Quality",
        "Description": "The strength and strategic nature of relationships with key suppliers, characterized by collaboration, trust, and mutual value creation",
        "Business Drivers": "Strategic Value Creation",
        "Business Drivers Description": "Strong supplier relationships enable: innovation collaboration, preferential treatment (priority in shortages), cost optimization (partnership not adversarial), flexibility, strategic alignment.",
        "Performance Factors": "Strategic Partnerships",
        "Performance Factors Description": "Strong relationships show: regular business reviews, joint innovation initiatives, transparent communication, trusted advisor status, win-win negotiations, long-term commitments.",
        "Risk Factors": "Adversarial Relationships",
        "Risk Factors Description": "Poor supplier relationships limit: innovation access, priority treatment, flexibility, cause quality issues (disengagement), drive supplier turnover (high switching costs).",
        "Metric": "Supplier Relationship Score",
        "Metric Description": "Survey key suppliers: relationship quality, communication, collaboration, trust, strategic alignment. 5-point Likert scale. Also track: avg supplier tenure, retention rate.",
        "Unit": "Score (1-5)",
        "Target": ">4.0 (strong partnership)",
        "Instructions": "Survey top 20% of suppliers annually: relationship quality, trust, communication, collaboration, strategic value. Calculate average score. Also measure supplier retention rate and tenure."
    },

    # LEVEL 2: PARTNER ECOSYSTEM (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Third Parties > Partner Ecosystem",
        "Description": "The network of strategic partners including technology partners, channel partners, alliance partners, and ecosystem collaborators who enhance capabilities and market reach",
        "Business Drivers": "Capability Extension & Market Access",
        "Business Drivers Description": "Partner ecosystem provides: complementary capabilities (fill gaps), market access (channel partners), innovation (co-development), credibility (brand association), scalability.",
        "Performance Factors": "Thriving Partner Network",
        "Performance Factors Description": "Strong partner ecosystem shows: diverse partner types, active collaboration, revenue contribution (channel sales), co-innovation initiatives, satisfied partners (NPS >40).",
        "Risk Factors": "Partner Conflicts & Dependence",
        "Risk Factors Description": "Partner risks: over-dependence (channel concentration), partner conflicts (channel conflict), competitive positioning (partner becomes competitor), IP risks, weak partners (drag on brand).",
        "Metric": "Partner Ecosystem Health Index",
        "Metric Description": "Composite of 4 sub-elements: Partner Portfolio Diversity + Partner-Sourced Revenue + Partner Satisfaction + Co-Innovation Activity. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining partner counts, revenue data, satisfaction surveys, and innovation metrics. Strong ecosystems score >75."
    },

    # LEVEL 3: Partner Ecosystem Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Partner Ecosystem > Partner Portfolio Diversity",
        "Description": "The breadth and balance of the partner ecosystem across different types of partners and roles in the value chain",
        "Business Drivers": "Capability Breadth & Risk Diversification",
        "Business Drivers Description": "Diverse partner portfolio provides: broad capabilities, market reach, risk diversification (not dependent on one type), flexibility, optionality.",
        "Performance Factors": "Balanced Partner Mix",
        "Performance Factors Description": "Diverse ecosystem shows: multiple partner types (technology, channel, alliance, referral), international partners, no over-concentration, emerging partners (innovation).",
        "Risk Factors": "Partner Concentration",
        "Risk Factors Description": "Concentrated partners risk: over-dependence (few critical partners), limited reach, single partner type (narrow capabilities), geographic concentration.",
        "Metric": "Partner Type Count",
        "Metric Description": "# of active partners by type: Technology/ISV (integrations), Channel/Reseller (distribution), Referral (lead generation), Strategic Alliance (co-innovation). Target: diverse mix.",
        "Unit": "Count by type",
        "Target": ">3 active partners per type",
        "Instructions": "Categorize all active partners by type. Count active partners (revenue or activity in past 12 months) per category. Balanced ecosystem has >3 partners across multiple types."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Partner Ecosystem > Partner-Sourced Revenue",
        "Description": "The percentage of total revenue generated through partner channels including reseller sales, referrals, and co-selling arrangements",
        "Business Drivers": "Scalable Distribution",
        "Business Drivers Description": "Partner-sourced revenue enables: scalable distribution (leverage partner sales), market expansion (partner local presence), capital efficiency (not hiring direct sales), faster growth.",
        "Performance Factors": "Meaningful Partner Contribution",
        "Performance Factors Description": "Strong partner revenue shows: 20-40% of revenue via partners (varies by model), growing trend, productive partners (not all small), co-selling success.",
        "Risk Factors": "Partner Revenue Dependence or Neglect",
        "Risk Factors Description": "Risks: over-dependence (>70% via partners = loss of control), under-utilization (<10% = wasted ecosystem), channel conflict (direct vs partner).",
        "Metric": "Partner-Sourced Revenue %",
        "Metric Description": "Revenue generated through partner channels (reseller, referral, co-sell) / total revenue. Benchmark varies by business model: 20-40% typical for B2B.",
        "Unit": "Percentage (% of revenue)",
        "Target": "20-40% depending on model",
        "Instructions": "Track revenue source: direct sales, partner resale, partner referral, co-sell. Calculate partner-sourced as % of total. Quarterly tracking. Benchmark to comparable companies."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Partner Ecosystem > Partner Satisfaction",
        "Description": "The satisfaction and engagement level of partners with the partnership program, measured by partner Net Promoter Score (NPS) and retention",
        "Business Drivers": "Partner Engagement & Advocacy",
        "Business Drivers Description": "Partner satisfaction drives: partner investment (marketing, sales), advocacy (referrals), retention (program stickiness), innovation collaboration, mindshare vs competitors.",
        "Performance Factors": "Satisfied, Engaged Partners",
        "Performance Factors Description": "Strong partner satisfaction shows: partner NPS >40, high retention (>90%), active participation (enablement, events), growing partner investment, referrals.",
        "Risk Factors": "Partner Dissatisfaction",
        "Risk Factors Description": "Low partner satisfaction causes: disengagement (low effort), attrition (switch to competitors), negative word-of-mouth, minimal investment, relationship breakdown.",
        "Metric": "Partner Net Promoter Score (NPS)",
        "Metric Description": "Partner NPS: 'How likely are you to recommend our partner program to another company?' (0-10 scale). NPS = % Promoters (9-10) - % Detractors (0-6).",
        "Unit": "Score (-100 to +100)",
        "Target": ">40 (good), >70 (excellent)",
        "Instructions": "Survey partners annually with NPS question. Calculate: % rating 9-10 minus % rating 0-6. Supplement with open-ended feedback. Track trend. Also measure partner retention rate."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Partner Ecosystem > Co-Innovation Activity",
        "Description": "The level of collaborative innovation and product development initiatives undertaken jointly with strategic partners",
        "Business Drivers": "Innovation Acceleration",
        "Business Drivers Description": "Partner co-innovation enables: faster innovation (shared R&D), complementary products (integrations), market validation (partner feedback), go-to-market (joint launches).",
        "Performance Factors": "Active Co-Innovation",
        "Performance Factors Description": "Strong co-innovation shows: joint product roadmaps, technical integrations, co-development projects, joint IP, shared innovation investment, co-marketing launches.",
        "Risk Factors": "Transactional Partner Relationships",
        "Risk Factors Description": "Purely transactional partnerships limit: innovation potential, strategic value, competitive differentiation, partner commitment, missed opportunities.",
        "Metric": "Active Co-Innovation Projects",
        "Metric Description": "# of active co-innovation initiatives with partners: technical integrations, joint products, co-development, API partnerships. Normalize by partner count.",
        "Unit": "Count",
        "Target": ">5 active projects",
        "Instructions": "Track all co-innovation projects with partners: integrations, co-development, joint roadmaps, technical partnerships. Count active projects (in-flight). Report quarterly."
    },

    # LEVEL 2: OUTSOURCING RELATIONSHIPS (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Third Parties > Outsourcing Relationships",
        "Description": "The management of outsourced business processes and functions including IT, customer service, manufacturing, logistics, and business process outsourcing (BPO)",
        "Business Drivers": "Cost Efficiency & Focus",
        "Business Drivers Description": "Outsourcing enables: cost reduction (labor arbitrage), focus on core (outsource non-differentiating), variable costs (scale capacity), expertise access, capital efficiency.",
        "Performance Factors": "Strategic Outsourcing",
        "Performance Factors Description": "Strong outsourcing shows: clear sourcing strategy (core vs non-core), strong governance, performance-based contracts, retained oversight capability, partnership approach.",
        "Risk Factors": "Outsourcing Failures",
        "Risk Factors Description": "Outsourcing risks: quality degradation (cost focus), capability loss (can't bring back in-house), hidden costs (management overhead), IP loss, cultural misalignment.",
        "Metric": "Outsourcing Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Outsourcing Strategy Clarity + Retained Capability + Outsourcing Performance + Total Cost of Outsourcing. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining strategy assessment, capability evaluation, performance data, and cost analysis. Mature outsourcing scores >80."
    },

    # LEVEL 3: Outsourcing Relationships Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Outsourcing Relationships > Outsourcing Strategy Clarity",
        "Description": "The clarity and rigor of decisions about what to outsource vs retain in-house, based on strategic criteria and core competency analysis",
        "Business Drivers": "Strategic Focus",
        "Business Drivers Description": "Clear outsourcing strategy ensures: focus on core competencies, appropriate risk management, capability retention where needed, cost-value optimization, avoiding regrets.",
        "Performance Factors": "Deliberate Outsourcing Decisions",
        "Performance Factors Description": "Strong outsourcing strategy shows: documented core vs non-core framework, strategic review of outsourcing decisions, retained capabilities defined, risk assessment.",
        "Risk Factors": "Outsourcing Wrong Activities",
        "Risk Factors Description": "Poor outsourcing decisions risk: loss of core capabilities, strategic inflexibility, competitive disadvantage, inability to bring back in-house, hidden dependencies.",
        "Metric": "Outsourcing Strategy Maturity",
        "Metric Description": "Maturity assessment (1-5): 1=Opportunistic, 2=Cost-driven only, 3=Strategic framework, 4=Aligned to core competencies, 5=Optimized. Assess decision criteria and governance.",
        "Unit": "Level (1-5)",
        "Target": "Level 4 (Strategic)",
        "Instructions": "Assess outsourcing decision-making against maturity criteria. Score: ad-hoc (1), cost-only (2), strategic framework (3), core-competency-driven (4), optimized (5). Annual review."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Outsourcing Relationships > Retained Capability",
        "Description": "The internal expertise and oversight capability retained to manage outsourcing relationships and prevent hollowing-out of critical knowledge",
        "Business Drivers": "Control & Knowledge Retention",
        "Business Drivers Description": "Retained capability ensures: effective vendor management, performance oversight, strategic direction, ability to change vendors, knowledge preservation, avoid total dependence.",
        "Performance Factors": "Strong Internal Oversight",
        "Performance Factors Description": "Strong retained capability shows: dedicated vendor management team, technical expertise retained, performance monitoring, strategic oversight, ability to switch vendors if needed.",
        "Risk Factors": "Capability Hollowing-Out",
        "Risk Factors Description": "Loss of retained capability risks: vendor dependence (can't switch), loss of oversight (can't manage), strategic drift, inability to innovate, knowledge loss.",
        "Metric": "Retained Capability Assessment",
        "Metric Description": "For each outsourced function, assess retained capability: 1=None (total dependence), 2=Minimal oversight, 3=Management capability, 4=Strategic direction, 5=Can re-insource. Avg score.",
        "Unit": "Score (1-5)",
        "Target": ">3.5 (management + strategic capability)",
        "Instructions": "List all outsourced functions. For each, assess retained capability level (1-5 scale). Calculate average. Score <3 indicates dangerous hollowing-out. Review annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Outsourcing Relationships > Outsourcing Performance",
        "Description": "The quality and effectiveness of outsourced services measured against SLAs, quality standards, and business outcomes",
        "Business Drivers": "Value Realization",
        "Business Drivers Description": "Strong outsourcing performance delivers: cost savings realized, quality maintained or improved, SLA compliance, business outcomes, strategic value beyond cost.",
        "Performance Factors": "High-Performing Outsourcing",
        "Performance Factors Description": "Strong outsourcing shows: SLA compliance >95%, quality metrics at or above baseline, customer/employee satisfaction maintained, continuous improvement, proactive issue management.",
        "Risk Factors": "Outsourcing Underperformance",
        "Risk Factors Description": "Poor outsourcing performance causes: cost savings not realized, quality degradation, customer/employee frustration, SLA breaches, hidden costs (management overhead).",
        "Metric": "Outsourcing SLA Compliance Rate",
        "Metric Description": "% of outsourcing SLA metrics met across all outsourced services. Weighted by business criticality. Track by vendor and service type. Target: >95% compliance.",
        "Unit": "Percentage (%)",
        "Target": ">95% SLA compliance",
        "Instructions": "Track SLA metrics for all outsourced services monthly. Calculate % meeting SLA by vendor and service type. Weight by business impact. Report composite score quarterly."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Outsourcing Relationships > Total Cost of Outsourcing",
        "Description": "The all-in cost of outsourcing including vendor fees, transition costs, retained management overhead, and hidden costs vs anticipated savings",
        "Business Drivers": "Cost-Value Optimization",
        "Business Drivers Description": "Understanding total cost ensures: realistic ROI (not just vendor fees), accountability for savings, hidden cost awareness (transition, management), value vs cost trade-offs.",
        "Performance Factors": "Cost Savings Realized",
        "Performance Factors Description": "Strong outsourcing economics show: total cost <internal baseline, savings targets met, hidden costs minimized, value beyond cost (quality, flexibility), positive ROI.",
        "Risk Factors": "Hidden Costs Exceed Savings",
        "Risk Factors Description": "Total cost overruns occur: transition costs underestimated, management overhead high, rework costs (quality issues), opportunity costs (strategic), 'savings' disappear.",
        "Metric": "Outsourcing Total Cost vs Baseline",
        "Metric Description": "Total annual outsourcing cost (vendor fees + transition + retained management + hidden costs) vs internal baseline. Express as % of baseline. Target: <80% for cost arbitrage outsourcing.",
        "Unit": "Percentage (% of baseline)",
        "Target": "<80% of internal baseline cost",
        "Instructions": "Calculate total outsourcing cost: vendor fees, transition costs, retained FTEs, management overhead, rework. Compare to pre-outsourcing baseline (or build-in-house estimate). Annual review."
    },

    # LEVEL 2: VENDOR RISK (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Third Parties > Vendor Risk",
        "Description": "The identification, assessment, monitoring, and mitigation of risks arising from reliance on third-party vendors including operational, financial, cyber, and compliance risks",
        "Business Drivers": "Risk Mitigation & Compliance",
        "Business Drivers Description": "Vendor risk management prevents: business disruption (vendor failure), cyber breaches (supply chain attacks), compliance violations (vendor non-compliance), reputational damage.",
        "Performance Factors": "Proactive Risk Management",
        "Performance Factors Description": "Strong vendor risk management shows: risk assessments for all vendors, continuous monitoring, tiered approach (criticality-based), incident response plans, regular audits.",
        "Risk Factors": "Vendor-Driven Incidents",
        "Risk Factors Description": "Vendor risks materialize as: data breaches (43% via third parties), business disruption (vendor outage), compliance violations, financial losses, reputational damage.",
        "Metric": "Vendor Risk Management Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Vendor Risk Assessment Coverage + Vendor Financial Stability + Vendor Cybersecurity + Vendor Compliance. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining risk assessment data, financial monitoring, security posture, and compliance verification. Mature programs score >85."
    },

    # LEVEL 3: Vendor Risk Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Vendor Risk > Vendor Risk Assessment Coverage",
        "Description": "The percentage of vendors that have undergone formal risk assessment including operational, financial, security, and compliance dimensions",
        "Business Drivers": "Risk Visibility",
        "Business Drivers Description": "Comprehensive risk assessment ensures: risks identified before materialization, informed decisions (accept, mitigate, terminate), prioritized attention (high-risk vendors), regulatory compliance.",
        "Performance Factors": "Complete Risk Assessment",
        "Performance Factors Description": "Strong risk assessment shows: 100% critical vendors assessed, tiered approach (risk-based), annual reassessment, standardized framework, documented findings and mitigation.",
        "Risk Factors": "Risk Assessment Gaps",
        "Risk Factors Description": "Incomplete assessments leave: blind spots (unknown risks), surprises when issues materialize, compliance violations (due diligence failures), inability to prioritize.",
        "Metric": "Vendor Risk Assessment Coverage Rate",
        "Metric Description": "% of active vendors with current risk assessment (<12 months old). Segment by tier: Critical (100% required), High (100%), Medium (80%), Low (50%).",
        "Unit": "Percentage (%)",
        "Target": "100% critical/high, 80% medium, 50% low",
        "Instructions": "Classify vendors by criticality (Critical, High, Medium, Low). Track risk assessment status and date. Calculate % with current assessment (<12 mo) by tier. Quarterly tracking."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Vendor Risk > Vendor Financial Stability",
        "Description": "The financial health and stability of critical vendors, monitored to identify risk of vendor failure or distress that could disrupt business",
        "Business Drivers": "Business Continuity",
        "Business Drivers Description": "Monitoring vendor financial health prevents: surprise failures (vendor bankruptcy), supply disruptions, transition costs (emergency replacement), contract breaches (vendor distress).",
        "Performance Factors": "Stable Vendor Base",
        "Performance Factors Description": "Strong financial stability shows: D&B ratings >70, credit ratings investment grade, financial statement reviews, early warning indicators monitored, backup vendors identified.",
        "Risk Factors": "Vendor Financial Distress",
        "Risk Factors Description": "Financially unstable vendors risk: sudden failure (business disruption), service degradation (cash constraints), price increases (desperation), contract breach.",
        "Metric": "Critical Vendor Financial Health Score",
        "Metric Description": "% of critical vendors with healthy financials (D&B rating >70, or positive cash flow + low debt, or credit rating investment grade). Monitor quarterly.",
        "Unit": "Percentage (%)",
        "Target": ">90% of critical vendors healthy",
        "Instructions": "Identify critical vendors (business disruption if fail). Obtain financial indicators: D&B rating, credit rating, or financial statements. Assess health. Calculate % healthy. Flag at-risk vendors."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Vendor Risk > Vendor Cybersecurity Posture",
        "Description": "The security practices and controls of vendors with access to organizational systems, data, or networks, assessing risk of supply chain cyber attacks",
        "Business Drivers": "Cyber Risk Prevention",
        "Business Drivers Description": "Vendor security assessment prevents: supply chain attacks (43% of breaches via third parties), data breaches (vendor access), malware introduction, compliance violations (data processor requirements).",
        "Performance Factors": "Verified Security Posture",
        "Performance Factors Description": "Strong vendor security shows: security assessments completed (SOC 2, ISO 27001, or questionnaires), continuous monitoring, privileged access managed, incident response tested.",
        "Risk Factors": "Vendor Security Weaknesses",
        "Risk Factors Description": "Weak vendor security risks: data breaches (Target breach = HVAC vendor), supply chain attacks (SolarWinds), malware introduction, compliance violations.",
        "Metric": "Vendor Security Assessment Completion Rate",
        "Metric Description": "% of vendors with system/data access who have completed security assessment (SOC 2 report, ISO 27001, or security questionnaire). Target: 100% for vendors with access.",
        "Unit": "Percentage (%)",
        "Target": "100% of vendors with access",
        "Instructions": "Identify all vendors with system access, data access, or network access. Track security assessment status: SOC 2, ISO 27001, questionnaire, or audit. Calculate % assessed. Quarterly review."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Vendor Risk > Vendor Compliance Verification",
        "Description": "The validation that vendors comply with relevant legal, regulatory, and contractual obligations including data protection, labor, environmental, and industry regulations",
        "Business Drivers": "Regulatory Compliance",
        "Business Drivers Description": "Vendor compliance verification ensures: regulatory compliance (GDPR data processor requirements), ethical sourcing (labor standards), environmental standards, contract compliance.",
        "Performance Factors": "Verified Compliance",
        "Performance Factors Description": "Strong vendor compliance shows: compliance attestations obtained, audits conducted, certifications verified (ISO, industry-specific), violations tracked, remediation required.",
        "Risk Factors": "Vendor Compliance Violations",
        "Risk Factors Description": "Vendor non-compliance causes: regulatory fines (data protection), reputational damage (labor violations), contract breaches, legal liability (contributory negligence).",
        "Metric": "Vendor Compliance Attestation Rate",
        "Metric Description": "% of vendors required to provide compliance attestations (GDPR, SOC 2, industry certifications) who have provided current documentation. Critical vendors: 100% required.",
        "Unit": "Percentage (%)",
        "Target": "100% critical vendors, >90% all",
        "Instructions": "Identify compliance requirements by vendor (GDPR for data processors, industry certs, etc.). Track attestation status. Calculate % with current compliance docs. Annual refresh."
    },

    # LEVEL 2: CONTRACT MANAGEMENT (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Third Parties > Contract Management",
        "Description": "The processes and systems for negotiating, executing, storing, monitoring, and renewing contracts with third parties ensuring terms are favorable and obligations are met",
        "Business Drivers": "Legal Protection & Value Optimization",
        "Business Drivers Description": "Effective contract management ensures: legal protection (risk allocation), favorable terms (pricing, SLAs), compliance (obligations met), value capture (discounts, credits), renewal optimization.",
        "Performance Factors": "Mature Contract Governance",
        "Performance Factors Description": "Strong contract management shows: centralized repository, automated alerts (renewals), SLA tracking, favorable terms negotiated, compliance monitoring, renewal optimization.",
        "Risk Factors": "Contract Leakage & Exposure",
        "Risk Factors Description": "Poor contract management causes: unfavorable terms (weak negotiation), auto-renewals missed (price increases), SLA breaches uncaught, compliance failures, value leakage.",
        "Metric": "Contract Management Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Contract Repository Completeness + Contract Terms Favorability + SLA Monitoring + Renewal Optimization. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining repository data, terms assessment, monitoring data, and renewal analysis. Mature contract management scores >85."
    },

    # LEVEL 3: Contract Management Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Contract Management > Contract Repository Completeness",
        "Description": "The percentage of third-party contracts properly stored in a centralized, searchable repository with key terms and metadata captured",
        "Business Drivers": "Visibility & Control",
        "Business Drivers Description": "Complete contract repository enables: visibility to obligations, renewal tracking (avoid auto-renew), compliance monitoring, audit readiness, negotiation leverage (know what you have).",
        "Performance Factors": "Centralized Contract Repository",
        "Performance Factors Description": "Strong repository shows: 100% contracts captured, centralized system, key terms extracted (renewal dates, SLAs, liability caps), searchable, automated alerts (renewals).",
        "Risk Factors": "Decentralized or Missing Contracts",
        "Risk Factors Description": "Poor repository management causes: missed renewals (auto-renew at higher prices), unknown obligations, audit failures, negotiation weakness (don't know current terms).",
        "Metric": "Contract Repository Coverage Rate",
        "Metric Description": "% of active third-party contracts stored in contract management system with key metadata captured (parties, dates, value, terms, renewal). Target: 100% for contracts >$25k/year.",
        "Unit": "Percentage (%)",
        "Target": "100% of material contracts (>$25k)",
        "Instructions": "Inventory all active third-party contracts. Track which are in contract management system with complete metadata. Calculate coverage %. Prioritize contracts >$25k annual value."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Contract Management > Contract Terms Favorability",
        "Description": "The degree to which contract terms are favorable to the organization including pricing, SLAs, liability limits, termination rights, and IP ownership",
        "Business Drivers": "Value & Risk Optimization",
        "Business Drivers Description": "Favorable contract terms deliver: cost savings (volume discounts, rate locks), risk protection (liability caps, indemnification), flexibility (termination rights), value (SLA credits).",
        "Performance Factors": "Favorable Terms Negotiated",
        "Performance Factors Description": "Strong contract terms show: competitive pricing, SLAs with teeth (credits), liability limits balanced, favorable payment terms, IP ownership clear, easy exit clauses.",
        "Risk Factors": "Unfavorable Terms",
        "Risk Factors Description": "Weak contract terms cause: overpayment (no discounts), unlimited liability exposure, vendor-favorable terms (auto-renew, lock-in), SLAs without consequences.",
        "Metric": "Contract Terms Quality Score",
        "Metric Description": "Assessment of contract terms across key dimensions: pricing (benchmarked), SLAs (measurable + credits), liability (capped), termination (reasonable notice), IP (clear ownership). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (favorable terms)",
        "Instructions": "Sample 20 major contracts. Score each on 5 dimensions (pricing, SLAs, liability, termination, IP) 0-20 points each. Calculate average score. Benchmark favorable terms. Annual review."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Contract Management > SLA Monitoring",
        "Description": "The systematic tracking and enforcement of service level agreements in contracts, including breach identification and credit/remedy pursuit",
        "Business Drivers": "Value Enforcement",
        "Business Drivers Description": "SLA monitoring ensures: commitments met (vendor accountability), value captured (SLA credits earned), issue escalation (breach = action), performance improvement (visibility drives improvement).",
        "Performance Factors": "Proactive SLA Management",
        "Performance Factors Description": "Strong SLA monitoring shows: automated tracking, breach alerts, credits pursued, vendor scorecards, escalation process, continuous improvement discussions.",
        "Risk Factors": "Unmonitored SLAs",
        "Risk Factors Description": "Lack of SLA monitoring causes: vendor underperformance (no accountability), unclaimed credits (value leakage), late breach discovery, weak vendor relations (no data).",
        "Metric": "SLA Monitoring Coverage Rate",
        "Metric Description": "% of contracts with SLAs that have active monitoring and tracking in place. Target: 100% for critical vendors. Also track: % SLA credits captured when earned.",
        "Unit": "Percentage (%)",
        "Target": "100% of SLAs monitored",
        "Instructions": "Identify all contracts with SLAs. Track which have active monitoring (manual or automated). Calculate % monitored. Also track SLA breach rate and credits captured. Quarterly review."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Contract Management > Renewal Optimization",
        "Description": "The proactive management of contract renewals to negotiate improved terms, avoid unfavorable auto-renewals, and optimize vendor portfolio",
        "Business Drivers": "Value Recapture",
        "Business Drivers Description": "Renewal optimization delivers: renegotiation opportunities (better pricing), auto-renew prevention (price increases), vendor consolidation, competitive leverage (consider alternatives).",
        "Performance Factors": "Strategic Renewal Process",
        "Performance Factors Description": "Strong renewal management shows: 90-day advance renewal review, competitive benchmarking, renegotiation (10-20% savings common), vendor consolidation, auto-renew prevention.",
        "Risk Factors": "Missed Renewal Opportunities",
        "Risk Factors Description": "Poor renewal management causes: auto-renew at unfavorable terms (price increases), missed renegotiation (no benchmarking), vendor sprawl (no consolidation).",
        "Metric": "Renewal Value Recapture Rate",
        "Metric Description": "% of contract renewals that achieve improved terms (lower cost, better SLAs, favorable terms) vs prior contract. Measure $ savings + term improvements. Target: >60% improved.",
        "Unit": "Percentage (% improved)",
        "Target": ">60% of renewals improved",
        "Instructions": "Track all contract renewals. Categorize outcome: improved terms, same terms, worse terms. Calculate % improved (cost savings or SLA/term improvements). Annual tracking."
    },

    # LEVEL 2: THIRD-PARTY PERFORMANCE (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Third Parties > Third-Party Performance",
        "Description": "The overall performance and value delivery of the third-party ecosystem measured across quality, reliability, innovation, and relationship dimensions",
        "Business Drivers": "Extended Enterprise Value",
        "Business Drivers Description": "Third-party performance determines: quality of delivered value (inputs/services), innovation contribution (ecosystem), reliability (business continuity), cost-value trade-off.",
        "Performance Factors": "High-Performing Ecosystem",
        "Performance Factors Description": "Strong third-party performance shows: >90% satisfaction, quality at or above baseline, innovation contributions, reliable delivery, proactive issue management, continuous improvement.",
        "Risk Factors": "Underperforming Third Parties",
        "Risk Factors Description": "Poor third-party performance causes: quality issues (defects), reliability problems (disruptions), innovation lag, cost without value, relationship breakdown.",
        "Metric": "Third-Party Performance Index",
        "Metric Description": "Composite of 4 sub-elements: Third-Party Quality + Third-Party Reliability + Third-Party Innovation Contribution + Third-Party Satisfaction. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">85",
        "Instructions": "Average 4 sub-element scores combining quality metrics, reliability data, innovation tracking, and satisfaction surveys. Top-performing ecosystems score >90."
    },

    # LEVEL 3: Third-Party Performance Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Third-Party Performance > Third-Party Quality",
        "Description": "The quality of goods and services delivered by third parties measured by defect rates, returns, rework, and quality standards compliance",
        "Business Drivers": "Quality Assurance",
        "Business Drivers Description": "Third-party quality determines: product/service quality (dependent on inputs), customer satisfaction, cost of quality (rework), brand reputation, competitive positioning.",
        "Performance Factors": "High Third-Party Quality",
        "Performance Factors Description": "Strong quality shows: <2% defect rate, minimal returns/rework, quality certifications (ISO 9001), continuous improvement, root cause analysis, proactive quality management.",
        "Risk Factors": "Third-Party Quality Issues",
        "Risk Factors Description": "Poor third-party quality causes: product defects (customer dissatisfaction), service failures, rework costs, delayed deliveries, brand damage, contract disputes.",
        "Metric": "Third-Party Defect Rate",
        "Metric Description": "% of goods/services from third parties requiring rework, returns, or rejection due to quality issues. Benchmark: <2% excellent, 2-5% acceptable, >5% problematic.",
        "Unit": "Percentage (%)",
        "Target": "<2% defect rate",
        "Instructions": "Track all third-party deliveries (goods, services). Record quality failures (defects, returns, rework). Calculate defect rate. Segment by vendor. Root cause analysis for high rates."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Third-Party Performance > Third-Party Reliability",
        "Description": "The consistency and dependability of third-party delivery measured by on-time delivery, availability, and fulfillment of commitments",
        "Business Drivers": "Business Continuity",
        "Business Drivers Description": "Third-party reliability ensures: business continuity (predictable supply), production scheduling (on-time delivery), customer commitments met, inventory optimization.",
        "Performance Factors": "Highly Reliable Third Parties",
        "Performance Factors Description": "Strong reliability shows: >95% on-time delivery, >99% availability (for services), consistent performance, proactive communication (delays), backup plans.",
        "Risk Factors": "Third-Party Unreliability",
        "Risk Factors Description": "Unreliable third parties cause: production delays (late delivery), customer commitments missed, excess inventory (buffer stock), emergency costs (expediting).",
        "Metric": "Third-Party On-Time Delivery Rate",
        "Metric Description": "% of third-party deliveries (goods, services, milestones) completed on or before committed date. Benchmark: >95% excellent, 90-95% acceptable, <90% problematic.",
        "Unit": "Percentage (%)",
        "Target": ">95% on-time",
        "Instructions": "Track all third-party delivery commitments (ship dates, service delivery dates, milestones). Record on-time vs late. Calculate on-time %. Segment by vendor and criticality."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Third-Party Performance > Third-Party Innovation Contribution",
        "Description": "The degree to which third parties proactively contribute ideas, innovations, and improvements beyond basic contractual requirements",
        "Business Drivers": "Innovation Acceleration",
        "Business Drivers Description": "Third-party innovation provides: new ideas (external perspective), technology access (partner innovations), cost reduction (process improvements), competitive advantage.",
        "Performance Factors": "Proactive Innovation Partners",
        "Performance Factors Description": "Innovative third parties demonstrate: proactive suggestions (improvement ideas), technology sharing (early access), joint innovation (co-development), continuous improvement mindset.",
        "Risk Factors": "Transactional-Only Relationships",
        "Risk Factors Description": "Lack of third-party innovation means: missed opportunities (no external ideas), competitive disadvantage, stagnation, transactional relationships only.",
        "Metric": "Third-Party Innovation Contribution Score",
        "Metric Description": "Annual count of innovation contributions from third parties: process improvements implemented, new technologies introduced, cost savings suggested, joint innovations. Normalize by vendor count.",
        "Unit": "Count per year",
        "Target": ">5 meaningful contributions/year",
        "Instructions": "Track innovation contributions from third parties: improvement suggestions, cost savings ideas, new technology introductions, joint innovations. Count those implemented. Annual reporting."
    },
    {
        "Level": 3,
        "Hierarchy": "Third Parties > Third-Party Performance > Third-Party Satisfaction",
        "Description": "The organization's satisfaction with third-party partners measured through satisfaction surveys and relationship health assessments",
        "Business Drivers": "Relationship Quality",
        "Business Drivers Description": "High third-party satisfaction indicates: value delivered, effective relationship, alignment, performance meeting expectations, successful partnership.",
        "Performance Factors": "High Satisfaction with Partners",
        "Performance Factors Description": "Strong third-party satisfaction shows: >85% satisfaction scores, high relationship NPS, willingness to expand engagement, recommend to others, renew/extend contracts.",
        "Risk Factors": "Third-Party Dissatisfaction",
        "Risk Factors Description": "Low satisfaction with third parties signals: performance issues, relationship problems, misalignment, likely to change vendors, value not delivered.",
        "Metric": "Third-Party Satisfaction Score",
        "Metric Description": "Internal stakeholder rating of third-party performance and relationship quality. Survey business owners quarterly: overall satisfaction, quality, reliability, value. 5-point Likert, % favorable.",
        "Unit": "Percentage (% favorable)",
        "Target": ">85% favorable",
        "Instructions": "Survey business owners of third-party relationships quarterly: satisfaction, quality, reliability, responsiveness, value. Calculate % favorable (4-5 on 5-point scale). Segment by vendor."
    }
]
