"""
Culture Dimension Data - ENABLERS Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

culture_data = [
    # LEVEL 1: CULTURE DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Culture",
        "Description": "The shared values, beliefs, behaviors, and norms that shape how work gets done and how people interact",
        "Business Drivers": "Employee Performance & Engagement",
        "Business Drivers Description": "Culture drives discretionary effort, innovation, collaboration, retention, and organizational resilience. Strong cultures attract talent, enable execution, and create competitive advantage.",
        "Performance Factors": "Cultural Strength & Alignment",
        "Performance Factors Description": "High-performing cultures exhibit: clear values lived consistently, high engagement and psychological safety, strong collaboration and learning orientation, diversity and inclusion. Measured by engagement scores, retention rates, cultural assessments.",
        "Risk Factors": "Cultural Dysfunction & Toxicity",
        "Risk Factors Description": "Toxic cultures drive: talent loss, poor execution, ethical failures, brand damage, legal exposure. Risk indicators: low engagement, high turnover, harassment claims, whistleblower reports, leadership-employee disconnect.",
        "Metric": "Overall Culture Health Score",
        "Metric Description": "Composite index of 6 element scores: Values Alignment + Engagement + Psychological Safety + Collaboration + Learning + D&I. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75 (healthy culture)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Industry benchmark: 65-75 typical, >75 excellent, <60 concerning."
    },

    # LEVEL 2: VALUES ALIGNMENT (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Culture > Values Alignment",
        "Description": "The degree to which organizational values are clearly defined, understood, and consistently lived in decisions and behaviors",
        "Business Drivers": "Decision Consistency & Trust",
        "Business Drivers Description": "Clear, lived values create consistency, build trust, guide decisions under uncertainty, and attract values-aligned talent and customers.",
        "Performance Factors": "Values Clarity & Consistency",
        "Performance Factors Description": "Strong values alignment shows: documented and communicated values, visible leadership modeling, values-based decision frameworks, recognition tied to values. Measured by values awareness, behavior consistency scores.",
        "Risk Factors": "Values-Behavior Gap",
        "Risk Factors Description": "Values-behavior gaps erode trust, drive cynicism, and enable ethical drift. Risks: leadership hypocrisy, selective enforcement, values ignored under pressure, new hires misaligned.",
        "Metric": "Values Alignment Index",
        "Metric Description": "Composite of 4 sub-element scores: Values Clarity + Behavior Consistency + Decision Integration + Recognition. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average the 4 Level 3 sub-element scores. Survey-based assessment of values awareness, observed behaviors, and recognition practices."
    },

    # LEVEL 3: Values Alignment Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Culture > Values Alignment > Values Clarity",
        "Description": "The extent to which organizational values are clearly articulated, understood by employees, and anchored in concrete behaviors",
        "Business Drivers": "Shared Understanding & Direction",
        "Business Drivers Description": "Clear values provide shared direction, guide hiring and promotion, inform strategy, and differentiate culture. They become 'how we do things here.'",
        "Performance Factors": "Values Documentation & Awareness",
        "Performance Factors Description": "Strong values clarity includes: 3-7 core values documented, behavioral anchors defined, regular communication, onboarding emphasis, tested understanding. High awareness scores (>80%).",
        "Risk Factors": "Values Ambiguity",
        "Risk Factors Description": "Unclear values lead to inconsistent decisions, misaligned hiring, cultural fragmentation, and inability to hold people accountable to cultural standards.",
        "Metric": "Employee Values Awareness Score",
        "Metric Description": "% of employees who can accurately state core values and describe behavioral examples. Measured via pulse surveys or onboarding quizzes.",
        "Unit": "Percentage (%)",
        "Target": ">80% accurate recall",
        "Instructions": "Survey employees: 'Name our core values and give an example of each in action.' Score accuracy. Test annually + at onboarding."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Values Alignment > Values-Behavior Consistency",
        "Description": "The degree to which employee and leadership behaviors consistently reflect stated organizational values",
        "Business Drivers": "Credibility & Trust",
        "Business Drivers Description": "Consistent values-behavior builds credibility with employees, customers, and stakeholders. Enables accountability and creates authentic culture.",
        "Performance Factors": "Observed Behavioral Consistency",
        "Performance Factors Description": "High consistency shows: leaders visibly model values, values guide hiring/firing, behaviors match stated values, hypocrisy is rare. Measured by 360 reviews, culture surveys.",
        "Risk Factors": "Say-Do Gap",
        "Risk Factors Description": "Values-behavior gaps breed cynicism, erode engagement, drive turnover of values-aligned talent, and attract values-agnostic opportunists. Indicates leaders 'don't walk the talk.'",
        "Metric": "Values-Behavior Consistency Score",
        "Metric Description": "Employee rating of 'Leaders and colleagues consistently demonstrate our values in their behavior.' 5-point Likert scale, averaged.",
        "Unit": "Score (1-5)",
        "Target": ">4.0 (agree/strongly agree)",
        "Instructions": "Include in employee engagement or culture survey. Ask: 'Leaders consistently model our values' and 'Colleagues' behaviors align with our values.' Average responses."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Values Alignment > Values-Decision Integration",
        "Description": "The extent to which organizational values explicitly inform and guide strategic and operational decisions",
        "Business Drivers": "Strategic Alignment & Prioritization",
        "Business Drivers Description": "Values-integrated decisions ensure strategic consistency, prioritize what matters, navigate trade-offs, and maintain cultural integrity during growth or crisis.",
        "Performance Factors": "Decision Framework Integration",
        "Performance Factors Description": "Strong integration shows: values in decision criteria, values-based trade-off resolution, strategy filtered through values lens, 'will this honor our values?' is standard question.",
        "Risk Factors": "Values Ignored Under Pressure",
        "Risk Factors Description": "Values ignored when inconvenient signal they're 'nice to have' not core. Results in expedient decisions that erode culture, trust, and long-term performance.",
        "Metric": "Values in Decision-Making Score",
        "Metric Description": "Manager rating: 'Our values explicitly guide major decisions and trade-offs.' 5-point Likert scale. Survey managers quarterly.",
        "Unit": "Score (1-5)",
        "Target": ">4.0",
        "Instructions": "Survey managers: 'When making significant decisions, our values are explicitly considered as decision criteria.' Aggregate responses. Track trend over time."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Values Alignment > Values Recognition & Reinforcement",
        "Description": "The degree to which values-consistent behaviors are visibly recognized, celebrated, and rewarded throughout the organization",
        "Business Drivers": "Behavioral Reinforcement",
        "Business Drivers Description": "What gets recognized gets repeated. Values-based recognition reinforces desired behaviors, motivates values-aligned actions, and signals cultural priorities.",
        "Performance Factors": "Recognition Frequency & Visibility",
        "Performance Factors Description": "Strong reinforcement includes: regular values-based recognition programs, peer-to-peer recognition tied to values, values criteria in performance reviews and promotions, storytelling of values examples.",
        "Risk Factors": "Results-Only Recognition",
        "Risk Factors Description": "Recognizing only results (not how achieved) enables bad behavior, rewards values violations if profitable, and signals values don't matter. Drives 'win at all costs' culture.",
        "Metric": "Values-Based Recognition Frequency",
        "Metric Description": "# of values-based recognition events per employee per year. Includes formal awards, spot bonuses, peer recognition, public acknowledgments tied explicitly to values.",
        "Unit": "Count per employee per year",
        "Target": ">4 per employee/year",
        "Instructions": "Track all recognition events (formal + informal) that cite specific values. Divide total by employee count. Quarterly tracking."
    },

    # LEVEL 2: EMPLOYEE ENGAGEMENT (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Culture > Employee Engagement",
        "Description": "The emotional commitment employees have to the organization and its goals, manifesting in discretionary effort and intent to stay",
        "Business Drivers": "Productivity & Retention",
        "Business Drivers Description": "Engaged employees deliver higher productivity, better customer service, more innovation, and longer tenure. Engagement drives performance and reduces costly turnover.",
        "Performance Factors": "High Engagement Scores",
        "Performance Factors Description": "High engagement shows: >70% engagement scores, low regrettable turnover, high discretionary effort, strong pride and advocacy. Correlates with performance outcomes.",
        "Risk Factors": "Disengagement & Turnover",
        "Risk Factors Description": "Disengaged employees deliver minimum effort, resist change, drive negativity, and leave. Costs: lost productivity (25-30% lower), customer impact, recruitment/training costs, knowledge loss.",
        "Metric": "Employee Engagement Index",
        "Metric Description": "Composite of 4 sub-elements: Engagement Score + Discretionary Effort + Intent to Stay + Pride. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Use validated engagement survey (e.g., Gallup Q12, Glint). Calculate index from 4 sub-element scores. Survey annually or biannually."
    },

    # LEVEL 3: Employee Engagement Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Culture > Employee Engagement > Overall Engagement Score",
        "Description": "The aggregate measure of employee emotional commitment and connection to the organization, measured via validated engagement surveys",
        "Business Drivers": "Organizational Performance",
        "Business Drivers Description": "Engagement is the #1 predictor of organizational performance. Engaged teams show 21% higher profitability, 41% lower absenteeism, 59% lower turnover (Gallup meta-analysis).",
        "Performance Factors": "Survey-Measured Engagement",
        "Performance Factors Description": "Use validated instrument (Gallup Q12, Glint, Culture Amp). Measures: clarity of expectations, resources, recognition, development, opinions count, mission connection, colleague quality.",
        "Risk Factors": "Low Engagement Scores",
        "Risk Factors Description": "Scores <50% indicate serious cultural issues: poor leadership, unclear direction, inadequate resources, lack of development, or misalignment. Drives performance and retention risks.",
        "Metric": "Overall Engagement Score",
        "Metric Description": "% of employees rating 'engaged' or 'highly engaged' on validated engagement survey. Standard definition: top 2 boxes on 5-point scale.",
        "Unit": "Percentage (%)",
        "Target": ">70% engaged",
        "Instructions": "Deploy validated engagement survey annually or biannually. Calculate % favorable responses (4-5 on 5-point scale). Benchmark vs industry."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Employee Engagement > Discretionary Effort",
        "Description": "The willingness of employees to go above and beyond minimum job requirements, voluntarily contributing extra effort",
        "Business Drivers": "Productivity & Innovation",
        "Business Drivers Description": "Discretionary effort is the difference between doing enough to not get fired vs doing enough to make a difference. Drives innovation, problem-solving, and competitive advantage.",
        "Performance Factors": "Voluntary Extra Effort",
        "Performance Factors Description": "High discretionary effort shows: employees volunteer for projects, help colleagues unsolicited, proactively improve processes, work late on critical issues by choice, suggest innovations.",
        "Risk Factors": "Minimum Effort Mentality",
        "Risk Factors Description": "'Quiet quitting' - employees do minimum to keep job, no extra effort, no innovation, no help to others. Often precedes voluntary turnover or performance issues.",
        "Metric": "Discretionary Effort Score",
        "Metric Description": "Survey item: 'I am willing to go above and beyond what is required in my job to help this organization succeed.' 5-point Likert, % favorable.",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in engagement survey. Calculate % responding 4-5 on 5-point scale ('agree' or 'strongly agree'). Track by department."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Employee Engagement > Intent to Stay",
        "Description": "The degree to which employees plan to remain with the organization over the next 12-24 months",
        "Business Drivers": "Retention & Stability",
        "Business Drivers Description": "Intent to stay predicts voluntary turnover (60-70% predictive accuracy). High intent reduces recruitment costs, preserves institutional knowledge, and enables long-term planning.",
        "Performance Factors": "High Retention Intent",
        "Performance Factors Description": "Strong retention intent shows: >80% plan to stay 2+ years, low passive job seeking, excitement about future, recommend employer to others.",
        "Risk Factors": "Flight Risk",
        "Risk Factors Description": "Low intent to stay indicates: upcoming turnover wave, high replacement costs (50-200% of salary), knowledge loss, team disruption, customer impact, competitive intelligence loss.",
        "Metric": "Intent to Stay Score",
        "Metric Description": "Survey item: 'I see myself still working here in two years.' 5-point Likert scale. % favorable responses (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">80% favorable",
        "Instructions": "Include in engagement survey. Calculate % 'agree' or 'strongly agree.' Compare to actual voluntary turnover as validation. Track high-performers separately."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Employee Engagement > Pride in Organization",
        "Description": "The extent to which employees feel proud to work for the organization and actively recommend it as a great place to work",
        "Business Drivers": "Brand Advocacy & Talent Attraction",
        "Business Drivers Description": "Employee pride drives positive word-of-mouth, social media advocacy, referrals, customer confidence, and talent attraction. Proud employees are best recruiters and brand ambassadors.",
        "Performance Factors": "Strong Pride & Advocacy",
        "Performance Factors Description": "High pride shows: employees proactively recommend employer, defend reputation, share positive stories, refer candidates, display company swag, engage on social media positively.",
        "Risk Factors": "Embarrassment or Shame",
        "Risk Factors Description": "Employees ashamed of employer become detractors: negative Glassdoor reviews, social media criticism, don't refer candidates, hide employer affiliation, damage brand and talent pipeline.",
        "Metric": "Employee Pride Score",
        "Metric Description": "Survey item: 'I am proud to work for this organization.' 5-point Likert scale. % favorable responses.",
        "Unit": "Percentage (% favorable)",
        "Target": ">80% favorable",
        "Instructions": "Include in engagement survey. Calculate % 'agree' or 'strongly agree.' Correlate with Glassdoor ratings and referral rates."
    },

    # LEVEL 2: PSYCHOLOGICAL SAFETY (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Culture > Psychological Safety",
        "Description": "The shared belief that the team environment is safe for interpersonal risk-taking, speaking up, admitting mistakes, and challenging ideas",
        "Business Drivers": "Innovation & Learning",
        "Business Drivers Description": "Psychological safety enables: speaking truth to power, admitting mistakes early, challenging bad ideas, sharing concerns, rapid learning. Critical for innovation, quality, and risk management.",
        "Performance Factors": "High Safety Climate",
        "Performance Factors Description": "High psychological safety shows: questions welcomed, mistakes discussed openly, dissent valued, no fear of embarrassment or retaliation, interpersonal trust strong. Google's #1 team effectiveness factor.",
        "Risk Factors": "Fear-Based Culture",
        "Risk Factors Description": "Low psychological safety drives: hiding mistakes (quality issues), silence about risks (disasters), conformity (groupthink), political behavior, covering tracks, blame culture.",
        "Metric": "Psychological Safety Index",
        "Metric Description": "Composite of 4 sub-elements: Speak-Up Culture + Failure Tolerance + Interpersonal Trust + Risk-Taking Encouragement. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Use Edmondson's 7-item psychological safety scale or equivalent. Survey teams quarterly. Average 4 sub-element scores."
    },

    # LEVEL 3: Psychological Safety Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Culture > Psychological Safety > Speak-Up Culture",
        "Description": "The degree to which employees feel safe raising concerns, challenging ideas, asking questions, and sharing bad news without fear of negative consequences",
        "Business Drivers": "Risk Visibility & Quality",
        "Business Drivers Description": "Speak-up cultures surface risks early, catch quality issues, challenge bad strategies, and prevent disasters. Silence kills - literally in healthcare and aviation, financially elsewhere.",
        "Performance Factors": "High Voice & Candor",
        "Performance Factors Description": "Strong speak-up culture shows: junior staff challenge seniors, bad news travels fast upward, 'stupid questions' welcomed, constructive dissent valued, whistleblower protections strong.",
        "Risk Factors": "Silence & Self-Censorship",
        "Risk Factors Description": "Cultures punishing candor drive: hidden risks, undiscovered errors, unchallenged bad ideas, preventable failures. Classic cause of disasters (Challenger, financial crisis, Boeing 737 MAX).",
        "Metric": "Speak-Up Culture Score",
        "Metric Description": "Survey item: 'I feel safe speaking up with concerns, questions, or ideas, even if they challenge the status quo.' 5-point Likert. % favorable.",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in safety/engagement survey. Calculate % 4-5 responses. Track by level (ensure IC speak-up as high as managers). Investigate low scores immediately."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Psychological Safety > Failure Tolerance",
        "Description": "The extent to which the culture treats failures and mistakes as learning opportunities rather than occasions for blame or punishment",
        "Business Drivers": "Innovation & Rapid Learning",
        "Business Drivers Description": "Failure tolerance enables: fast experimentation, early pivots, honest retrospectives, knowledge sharing from mistakes, risk-taking for innovation. 'Fail fast, learn faster.'",
        "Performance Factors": "Learning from Failure",
        "Performance Factors Description": "High failure tolerance shows: post-mortems blameless, experiments encouraged, 'intelligent failures' celebrated, mistakes admitted openly, focus on systems not individuals.",
        "Risk Factors": "Blame Culture",
        "Risk Factors Description": "Blame cultures drive: hiding failures (preventing learning), risk aversion, cover-ups, scapegoating, repeated mistakes, innovation paralysis. 'Play not to lose' mentality.",
        "Metric": "Failure Tolerance Score",
        "Metric Description": "Survey item: 'In this organization, mistakes are treated as opportunities to learn and improve rather than reasons for blame.' 5-point Likert.",
        "Unit": "Score (1-5)",
        "Target": ">4.0 (agree/strongly agree)",
        "Instructions": "Include in culture survey. Calculate average score. Validate by examining: Are post-mortems blameless? Do people openly admit mistakes?"
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Psychological Safety > Interpersonal Trust",
        "Description": "The level of trust employees have in each other's competence, reliability, and positive intentions toward one another",
        "Business Drivers": "Collaboration & Efficiency",
        "Business Drivers Description": "High trust enables: delegation without micromanagement, fast decisions without verification, conflict resolution without HR, collaboration without politics. 'Speed of trust' (Covey).",
        "Performance Factors": "Strong Trust Climate",
        "Performance Factors Description": "High trust shows: assume positive intent, give benefit of doubt, share information freely, help without being asked, admit vulnerabilities, keep commitments reliably.",
        "Risk Factors": "Distrust & Verification Culture",
        "Risk Factors Description": "Low trust drives: excessive verification, micromanagement, information hoarding, CYA behavior, slow decisions, escalations, formal processes replacing informal cooperation.",
        "Metric": "Interpersonal Trust Score",
        "Metric Description": "Survey item: 'I trust my colleagues to act with good intentions and follow through on their commitments.' 5-point Likert scale.",
        "Unit": "Score (1-5)",
        "Target": ">4.0",
        "Instructions": "Include in team effectiveness survey. Calculate average. Validate against behavioral indicators: delegation frequency, escalation rates, meeting follow-through."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Psychological Safety > Risk-Taking Encouragement",
        "Description": "The degree to which the culture actively encourages taking intelligent risks, trying new approaches, and stepping outside comfort zones",
        "Business Drivers": "Innovation & Agility",
        "Business Drivers Description": "Encouraged risk-taking drives: product innovation, process improvements, market expansion, talent growth. Organizations that don't risk intelligently are disrupted by those that do.",
        "Performance Factors": "Calculated Risk Encouragement",
        "Performance Factors Description": "Strong risk encouragement shows: innovation time allocated, experiments funded, 'try it' mentality, stretch assignments given, bold ideas rewarded even if fail, bias toward action.",
        "Risk Factors": "Risk Aversion & Paralysis",
        "Risk Factors Description": "Excessive risk aversion drives: analysis paralysis, missed opportunities, slow market response, bureaucracy, talent frustration, death by incrementalism. Slow death in fast markets.",
        "Metric": "Risk-Taking Encouragement Score",
        "Metric Description": "Survey item: 'My manager encourages me to take calculated risks and try new approaches, even if they might fail.' 5-point Likert.",
        "Unit": "Score (1-5)",
        "Target": ">3.8",
        "Instructions": "Include in manager effectiveness survey. Calculate average. Validate by tracking: experiment count, innovation pipeline, '20% time' usage."
    },

    # LEVEL 2: COLLABORATION (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Culture > Collaboration",
        "Description": "The effectiveness of teamwork and cooperation across teams, functions, and organizational boundaries to achieve shared goals",
        "Business Drivers": "Execution & Problem-Solving",
        "Business Drivers Description": "Strong collaboration enables: faster problem-solving, better decisions (diverse perspectives), smoother execution, customer-centric solutions, reduced duplication, shared learning.",
        "Performance Factors": "Effective Teamwork",
        "Performance Factors Description": "High collaboration shows: easy cross-functional work, shared goals trump silos, effective virtual teamwork, rapid coordination, constructive conflict resolution, 'we' not 'us vs them.'",
        "Risk Factors": "Silos & Internal Competition",
        "Risk Factors Description": "Poor collaboration drives: duplicated efforts, conflicting priorities, customer pain (handoffs fail), slow execution, territorial behavior, knowledge hoarding, internal competition over cooperation.",
        "Metric": "Collaboration Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Cross-Functional Cooperation + Information Sharing + Meeting Effectiveness + Conflict Resolution. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores from collaboration or team effectiveness survey. Administer quarterly."
    },

    # LEVEL 3: Collaboration Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Culture > Collaboration > Cross-Functional Cooperation",
        "Description": "The ease and effectiveness of working across departmental and functional boundaries to achieve shared organizational objectives",
        "Business Drivers": "Organizational Agility",
        "Business Drivers Description": "Cross-functional cooperation enables: rapid response to market changes, customer-centric solutions, innovation from diverse perspectives, efficient resource allocation, breaking silos.",
        "Performance Factors": "Seamless Cross-Team Work",
        "Performance Factors Description": "Strong cross-functional work shows: easy team formation, shared metrics, transparent planning, quick handoffs, mutual support, customer needs trump functional priorities.",
        "Risk Factors": "Functional Silos",
        "Risk Factors Description": "Silos drive: duplicated work, conflicting priorities, customer frustration (internal friction visible), slow execution, sub-optimization, 'not my job' mentality, empire building.",
        "Metric": "Cross-Functional Cooperation Score",
        "Metric Description": "Survey item: 'It is easy to work with people from other departments to get things done.' 5-point Likert scale. % favorable.",
        "Unit": "Percentage (% favorable)",
        "Target": ">70% favorable",
        "Instructions": "Include in collaboration survey. Calculate % 4-5 responses. Validate by examining cross-functional project success rates and cycle times."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Collaboration > Information Sharing",
        "Description": "The degree to which knowledge, data, and information flow freely across teams and levels, enabling informed decision-making",
        "Business Drivers": "Decision Quality & Speed",
        "Business Drivers Description": "Free information flow enables: fast, informed decisions; reduced errors; shared learning; coordination; transparency. Information hoarding is organizational poison.",
        "Performance Factors": "Open Information Flow",
        "Performance Factors Description": "Strong information sharing shows: default to transparency, proactive communication, accessible documentation, open meetings, knowledge bases maintained, teach/learn culture.",
        "Risk Factors": "Information Hoarding",
        "Risk Factors Description": "Information silos drive: duplicated discovery, preventable errors, slow decisions, politics ('information is power'), inability to learn from others' experience, talent frustration.",
        "Metric": "Information Sharing Score",
        "Metric Description": "Survey item: 'People in this organization share information and knowledge freely across teams.' 5-point Likert scale.",
        "Unit": "Score (1-5)",
        "Target": ">4.0",
        "Instructions": "Include in collaboration survey. Calculate average score. Validate by examining: intranet usage, documentation quality, meeting openness."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Collaboration > Meeting Effectiveness",
        "Description": "The efficiency and productivity of meetings as collaboration tools, with clear purposes, engaged participants, and actionable outcomes",
        "Business Drivers": "Time Efficiency & Execution",
        "Business Drivers Description": "Effective meetings drive decisions, alignment, and action. Ineffective meetings waste 15-50% of organizational time (manager time especially) and drain energy.",
        "Performance Factors": "Productive Meetings",
        "Performance Factors Description": "Effective meetings have: clear purpose/agenda, right attendees only, engaged participation, decisions made, actions assigned with owners/dates, minutes distributed, follow-through tracked.",
        "Risk Factors": "Meeting Overload & Waste",
        "Risk Factors Description": "Poor meetings drain: time (15-50% of org time), energy (2+ ineffective meetings = disengagement), productivity, decision speed. 'This could have been an email.'",
        "Metric": "Meeting Effectiveness Score",
        "Metric Description": "Survey item: 'The meetings I attend are well-run, productive, and result in clear decisions and action items.' 5-point Likert.",
        "Unit": "Score (1-5)",
        "Target": ">3.5",
        "Instructions": "Include in collaboration or efficiency survey. Calculate average. Validate by tracking: meeting hours/week, % with agendas, % with follow-up actions."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Collaboration > Conflict Resolution",
        "Description": "The organization's capability to surface, discuss, and resolve conflicts constructively without damaging relationships or requiring escalation",
        "Business Drivers": "Team Effectiveness & Retention",
        "Business Drivers Description": "Healthy conflict resolution enables: better decisions (diverse views integrated), stronger relationships (trust through adversity), innovation (creative tension), faster execution (issues resolved).",
        "Performance Factors": "Constructive Conflict Culture",
        "Performance Factors Description": "Strong conflict resolution shows: issues surfaced early, direct peer resolution, focus on interests not positions, relationship preserved, third party rarely needed, conflict seen as healthy.",
        "Risk Factors": "Conflict Avoidance or Escalation",
        "Risk Factors Description": "Poor conflict management drives: festering resentments, passive-aggressive behavior, HR escalations, team dysfunction, talent loss, slow decisions (unresolved disagreement).",
        "Metric": "Conflict Resolution Score",
        "Metric Description": "Survey item: 'When conflicts arise, they are addressed constructively and resolved in a way that strengthens working relationships.' 5-point Likert.",
        "Unit": "Score (1-5)",
        "Target": ">3.8",
        "Instructions": "Include in team effectiveness survey. Calculate average. Validate by tracking: HR complaints, mediation requests, voluntary turnover after conflicts."
    },

    # LEVEL 2: LEARNING CULTURE (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Culture > Learning Culture",
        "Description": "The organizational commitment to continuous learning, knowledge sharing, skill development, and growth mindset across all levels",
        "Business Drivers": "Adaptability & Innovation",
        "Business Drivers Description": "Learning cultures adapt faster to change, innovate more, attract ambitious talent, and build capabilities proactively. 'Learning faster than competition' is sustainable advantage.",
        "Performance Factors": "Strong Learning Orientation",
        "Performance Factors Description": "Strong learning cultures show: high training investment (>2% payroll), growth mindset language, knowledge sharing rewarded, experiments encouraged, failure = learning, curiosity valued.",
        "Risk Factors": "Learning Stagnation",
        "Risk Factors Description": "Weak learning cultures risk: skill obsolescence, slow adaptation, innovation lag, talent loss (ambitious leave), disruption vulnerability, 'we've always done it this way' paralysis.",
        "Metric": "Learning Culture Index",
        "Metric Description": "Composite of 4 sub-elements: Learning Investment + Growth Mindset + Knowledge Sharing + Experimentation. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores. Combine quantitative metrics (training %, experiment count) with survey data (mindset, sharing)."
    },

    # LEVEL 3: Learning Culture Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Culture > Learning Culture > Learning Investment",
        "Description": "The financial and time resources the organization allocates to employee development, training, and continuous learning",
        "Business Drivers": "Capability Building",
        "Business Drivers Description": "Learning investment builds capabilities, improves performance, increases engagement, supports career growth, and enables strategic pivots. Skilled workforce is competitive advantage.",
        "Performance Factors": "Adequate Learning Resources",
        "Performance Factors Description": "Strong learning investment shows: >2% payroll on training, dedicated learning time (e.g., 20% time, conference budgets), tuition reimbursement, learning platforms, mentorship programs.",
        "Risk Factors": "Underinvestment in Development",
        "Risk Factors Description": "Low learning investment drives: skill gaps, performance plateaus, talent loss (leave for development), inability to execute strategy (capability gap), low engagement.",
        "Metric": "Learning Investment as % of Payroll",
        "Metric Description": "Total annual training/development spending divided by total annual payroll costs. Includes direct training costs, learning platforms, conference/education budgets, internal L&D staff.",
        "Unit": "Percentage (% of payroll)",
        "Target": ">2.0% (best practice)",
        "Instructions": "Sum all learning-related expenses (external training, platforms, conferences, tuition reimbursement, L&D salaries). Divide by total payroll. Calculate annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Learning Culture > Growth Mindset Prevalence",
        "Description": "The extent to which employees and leaders embrace a growth mindset - believing abilities can be developed through effort and learning",
        "Business Drivers": "Resilience & Performance",
        "Business Drivers Description": "Growth mindset (vs fixed mindset) drives: higher performance, greater resilience, more learning from feedback, better problem-solving, openness to challenge. Foundational to learning culture.",
        "Performance Factors": "Pervasive Growth Mindset",
        "Performance Factors Description": "Strong growth mindset shows: 'not yet' language (vs 'can't'), failures seen as learning, feedback sought, challenges embraced, effort praised over talent, continuous improvement focus.",
        "Risk Factors": "Fixed Mindset Culture",
        "Risk Factors Description": "Fixed mindset drives: fear of failure, defensiveness to feedback, avoiding challenges, talent worship ('natural' vs 'grinder'), perfectionism, learned helplessness.",
        "Metric": "Growth Mindset Score",
        "Metric Description": "Survey item: 'In this organization, we believe people can significantly improve their abilities and intelligence through effort and learning.' 5-point Likert.",
        "Unit": "Score (1-5)",
        "Target": ">4.0",
        "Instructions": "Include in culture survey. Use validated growth mindset items (Dweck framework). Calculate average. Validate by examining: language in reviews, response to setbacks."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Learning Culture > Knowledge Sharing Practices",
        "Description": "The systems, norms, and behaviors that facilitate the transfer and preservation of knowledge across the organization",
        "Business Drivers": "Organizational Learning",
        "Business Drivers Description": "Knowledge sharing scales individual learning to organizational learning, preserves institutional memory, accelerates onboarding, prevents repeated mistakes, and builds collective intelligence.",
        "Performance Factors": "Robust Knowledge Transfer",
        "Performance Factors Description": "Strong knowledge sharing shows: documentation expected, lessons learned captured, mentoring common, communities of practice, lunch-and-learns, wikis maintained, ask-the-expert channels.",
        "Risk Factors": "Knowledge Loss & Silos",
        "Risk Factors Description": "Poor knowledge sharing drives: re-inventing wheels, repeated mistakes, key person dependencies, slow onboarding, knowledge loss when people leave, silos of expertise.",
        "Metric": "Knowledge Sharing Frequency",
        "Metric Description": "Average # of knowledge-sharing events per employee per quarter. Includes: brown bags, mentoring sessions, documentation contributions, internal presentations, lessons learned posts.",
        "Unit": "Count per employee per quarter",
        "Target": ">2 per employee/quarter",
        "Instructions": "Track participation in: lunch-and-learns, mentoring, wiki edits, internal talks, retro documentation. Sum total, divide by employees, divide by quarters."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Learning Culture > Experimentation Encouragement",
        "Description": "The degree to which the culture supports running experiments, testing hypotheses, and learning through controlled trials",
        "Business Drivers": "Innovation & Evidence-Based Decisions",
        "Business Drivers Description": "Experimentation culture enables: rapid innovation (A/B tests), evidence-based decisions (vs opinions), learning from market (vs assumptions), failing cheap and fast.",
        "Performance Factors": "Active Experimentation",
        "Performance Factors Description": "Strong experimentation shows: A/B testing standard, pilot programs before scale, hypothesis-driven initiatives, experiment budgets allocated, learning valued over success, scientific method applied.",
        "Risk Factors": "Opinion-Based Decisions",
        "Risk Factors Description": "Lack of experimentation drives: HiPPO decisions (highest paid person's opinion), big bets without evidence, slow learning, binary win/loss (vs learn/learn), expensive failures.",
        "Metric": "Active Experiments Count",
        "Metric Description": "# of active experiments running at any time. Includes: A/B tests, pilots, MVPs, prototypes, controlled trials. Only count experiments with hypothesis and measurement plan.",
        "Unit": "Count",
        "Target": ">5 per 100 employees",
        "Instructions": "Track all experiments in experiment log/system. Count active experiments (not yet concluded). Normalize by employee count (experiments per 100 FTEs)."
    },

    # LEVEL 2: DIVERSITY & INCLUSION (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Culture > Diversity & Inclusion",
        "Description": "The demographic diversity of the workforce and the extent to which all employees feel valued, respected, and able to contribute fully",
        "Business Drivers": "Innovation & Market Reach",
        "Business Drivers Description": "Diverse, inclusive teams make better decisions (87% more likely), are more innovative (1.7x), better understand diverse customers, reduce groupthink, and attract broader talent pools.",
        "Performance Factors": "High Diversity & Inclusion",
        "Performance Factors Description": "Strong D&I shows: workforce reflects customer base and labor market, leadership diversity mirrors workforce, high inclusion scores (>70%), equitable advancement, diverse perspectives valued.",
        "Risk Factors": "Homogeneity & Exclusion",
        "Risk Factors Description": "Low D&I drives: groupthink, blind spots to customer needs, talent pool narrowing, discrimination claims, brand damage, innovation lag, market opportunity loss.",
        "Metric": "Diversity & Inclusion Index",
        "Metric Description": "Composite of 4 sub-elements: Workforce Diversity + Leadership Diversity + Inclusion Climate + Equitable Advancement. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores. Combine demographic metrics (diversity %) with inclusion survey data. Report annually with trend analysis."
    },

    # LEVEL 3: Diversity & Inclusion Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Culture > Diversity & Inclusion > Workforce Diversity",
        "Description": "The demographic composition of the workforce across dimensions of gender, race/ethnicity, age, disability, LGBTQ+, veteran status, etc.",
        "Business Drivers": "Talent Access & Market Understanding",
        "Business Drivers Description": "Workforce diversity expands talent pool, improves customer understanding, reduces blind spots, enables global expansion, and meets stakeholder expectations.",
        "Performance Factors": "Representative Workforce",
        "Performance Factors Description": "Strong workforce diversity shows: demographics approach customer base and labor market availability, improving trend, diversity across all departments (not just HR/Marketing).",
        "Risk Factors": "Homogeneous Workforce",
        "Risk Factors Description": "Low diversity drives: groupthink, narrow talent pool, customer blind spots, brand risks, difficulty attracting diverse talent (self-reinforcing), regulatory risks in some jurisdictions.",
        "Metric": "Workforce Diversity Score",
        "Metric Description": "Composite index: % women, % racial/ethnic minorities, % age diversity (not dominated by single generation), % with disabilities. Compare to labor market and customer base.",
        "Unit": "Index (0-100)",
        "Target": ">60 (benchmarked to labor market)",
        "Instructions": "Calculate diversity indices for each dimension (gender, race, age, disability). Weight by materiality to business. Compare to labor market and customer demographics. Update annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Diversity & Inclusion > Leadership Diversity",
        "Description": "The demographic diversity of leadership and decision-making roles, from senior management to board of directors",
        "Business Drivers": "Decision Quality & Credibility",
        "Business Drivers Description": "Leadership diversity improves decisions (research-proven), signals opportunity to diverse talent, builds stakeholder trust, reduces groupthink risk, and meets governance expectations.",
        "Performance Factors": "Diverse Leadership",
        "Performance Factors Description": "Strong leadership diversity shows: senior team reflects workforce diversity (or better), pipeline building for diverse talent, board diversity, equitable representation in key roles.",
        "Risk Factors": "Homogeneous Leadership",
        "Risk Factors Description": "Non-diverse leadership signals: glass ceiling, limits ambition of diverse talent, drives attrition, causes groupthink, damages brand, creates governance risk, invites activism.",
        "Metric": "Leadership Diversity Gap",
        "Metric Description": "Difference between workforce diversity and leadership diversity (VP+). E.g., if 40% women in workforce but 20% in leadership, gap = 20 percentage points. Target: gap <10 pp.",
        "Unit": "Percentage points",
        "Target": "<10 pp gap (leadership matches workforce)",
        "Instructions": "Calculate diversity % for overall workforce and separately for VP+ roles. Subtract leadership % from workforce %. Report gap for each diversity dimension. Update annually."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Diversity & Inclusion > Inclusion Climate",
        "Description": "The extent to which all employees feel respected, valued, heard, and able to be authentic and contribute fully regardless of background",
        "Business Drivers": "Engagement & Performance",
        "Business Drivers Description": "Inclusion drives engagement and performance of diverse talent. Without inclusion, diversity doesn't deliver benefits. Inclusive teams outperform homogeneous teams by 35% (McKinsey).",
        "Performance Factors": "Strong Inclusion",
        "Performance Factors Description": "High inclusion shows: >70% feel they can be authentic, diverse voices heard, microaggressions rare, DEI training effective, Employee Resource Groups active, psychological safety high.",
        "Risk Factors": "Exclusion & Tokenism",
        "Risk Factors Description": "Low inclusion drives: diverse talent attrition ('hire for diversity, lose for culture'), engagement gaps (diversity without inclusion = tokenism), discrimination claims, brand damage.",
        "Metric": "Inclusion Score",
        "Metric Description": "Survey items: 'I feel valued and respected', 'I can be my authentic self', 'Diverse perspectives are actively sought'. 5-point Likert, % favorable, analyzed by demographics.",
        "Unit": "Percentage (% favorable)",
        "Target": ">70% overall, <10 pp gap between groups",
        "Instructions": "Include inclusion items in engagement survey. Calculate % favorable overall and by demographic groups. Key metric: gap between majority and minority scores. <10 pp gap is target."
    },
    {
        "Level": 3,
        "Hierarchy": "Culture > Diversity & Inclusion > Equitable Advancement",
        "Description": "The fairness and equity of promotion, development, and advancement opportunities across all demographic groups",
        "Business Drivers": "Meritocracy & Retention",
        "Business Drivers Description": "Equitable advancement ensures best talent rises regardless of background, retains diverse talent (who leave if not advanced fairly), and maximizes organizational capability.",
        "Performance Factors": "Fair Advancement",
        "Performance Factors Description": "Equitable advancement shows: promotion rates similar across demographics (adjusted for tenure/performance), diverse high-potential pools, development opportunities equal, pay equity achieved.",
        "Risk Factors": "Advancement Inequity",
        "Risk Factors Description": "Inequitable advancement drives: diverse talent attrition, discrimination claims, reputation damage, loss of diverse perspectives at decision-making levels, regulatory risk.",
        "Metric": "Advancement Equity Ratio",
        "Metric Description": "Promotion rate of underrepresented groups divided by promotion rate of majority group. 1.0 = perfect equity. <0.8 or >1.2 indicates potential inequity. Adjust for tenure and performance.",
        "Unit": "Ratio",
        "Target": "0.8 - 1.2 (equity range)",
        "Instructions": "Calculate annual promotion rate by demographic group (promoted / eligible). Divide minority promotion rate by majority rate. Ratio <0.8 indicates underpromotion, >1.2 overpromotion. Investigate causes."
    }
]
