"""
Processes Dimension Data - EXECUTION Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

processes_data = [
    # LEVEL 1: PROCESSES DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Processes",
        "Description": "The design, documentation, performance, and continuous improvement of business processes that deliver customer and stakeholder value",
        "Business Drivers": "Operational Excellence",
        "Business Drivers Description": "Process excellence drives: operational efficiency, quality consistency, cost optimization, scalability, compliance, customer satisfaction, competitive advantage.",
        "Performance Factors": "Optimized, Reliable Processes",
        "Performance Factors Description": "High-performing processes show: documented, efficient flow, controlled variation, measured performance, continuous improvement, technology-enabled, customer-centric.",
        "Risk Factors": "Process Inefficiency & Breakdowns",
        "Risk Factors Description": "Process risks include: inefficiency (waste), quality issues (defects), delays (cycle time), high costs, customer dissatisfaction, compliance violations, breakdowns.",
        "Metric": "Overall Process Excellence Score",
        "Metric Description": "Composite index of 6 element scores: Process Design + Process Documentation + Process Performance + Process Control + Process Improvement + Process Technology. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75 (process excellence)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Process leaders score >85. Weight by business criticality."
    },

    # LEVEL 2: PROCESS DESIGN (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Processes > Process Design",
        "Description": "The methodology and quality of designing business processes to optimize flow, minimize waste, and deliver value efficiently",
        "Business Drivers": "Efficiency & Effectiveness",
        "Business Drivers Description": "Good process design ensures: efficient flow (minimize waste), effective outcomes (achieve objectives), customer value, scalability, adaptability, minimal defects.",
        "Performance Factors": "Lean, Customer-Centric Design",
        "Performance Factors Description": "Strong process design: customer-centric (start with customer need), lean principles (eliminate waste), clear ownership, optimized handoffs, scalable, technology-enabled.",
        "Risk Factors": "Poor Process Design",
        "Risk Factors Description": "Weak process design causes: inefficiency (waste, rework), quality issues, delays, high costs, poor customer experience, inability to scale.",
        "Metric": "Process Design Quality Index",
        "Metric Description": "Composite of 4 sub-elements: Customer-Centricity + Waste Elimination + Process Ownership + Scalability. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining customer focus assessment, waste analysis, ownership clarity, and scalability evaluation."
    },

    # LEVEL 3: Process Design Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Design > Customer-Centricity",
        "Description": "The degree to which processes are designed with customer needs and value delivery as the primary design criterion",
        "Business Drivers": "Customer Value",
        "Business Drivers Description": "Customer-centric design ensures: processes serve customer needs (not internal convenience), value-adding activities, customer perspective, competitive advantage.",
        "Performance Factors": "Outside-In Design",
        "Performance Factors Description": "Strong customer-centricity: start with customer need, value stream mapping, eliminate non-value-add (from customer perspective), customer feedback integrated.",
        "Risk Factors": "Inside-Out Design",
        "Risk Factors Description": "Inside-out design causes: processes optimized for internal convenience (not customer), unnecessary steps (from customer view), poor customer experience, competitive disadvantage.",
        "Metric": "Customer-Centric Design Score",
        "Metric Description": "Assessment of key processes: designed from customer perspective (Y/N), value stream mapped (Y/N), customer feedback integrated (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (customer-centric)",
        "Instructions": "Assess top 10-20 critical processes. For each: customer-centric design?, value stream mapping used?, customer feedback considered? Score each, average."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Design > Waste Elimination",
        "Description": "The systematic identification and elimination of waste in processes including waiting, defects, overprocessing, and unnecessary motion",
        "Business Drivers": "Cost Efficiency",
        "Business Drivers Description": "Waste elimination reduces: costs (labor, materials), cycle time (speed), defects (quality), working capital (inventory), improves efficiency, competitiveness.",
        "Performance Factors": "Lean Process Design",
        "Performance Factors Description": "Strong waste elimination: 7 wastes addressed (waiting, defects, motion, inventory, overproduction, overprocessing, transport), continuous flow, pull systems.",
        "Risk Factors": "Wasteful Processes",
        "Risk Factors Description": "Waste in processes causes: high costs (30-50% waste typical), long cycle times, quality issues, poor competitiveness, customer frustration.",
        "Metric": "Process Efficiency Ratio",
        "Metric Description": "Value-add time / total cycle time. Measures waste. Benchmark: <20% is typical (80% waste!), >50% is excellent. Lean target: maximize value-add %.",
        "Unit": "Percentage (%)",
        "Target": ">40% value-add time (60% waste eliminated)",
        "Instructions": "For key processes, time value-add activities vs total cycle time. Calculate value-add %. Low % = high waste. Lean transformation: 20% → 50%+."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Design > Process Ownership",
        "Description": "The clarity of process ownership with designated process owners accountable for end-to-end process performance and improvement",
        "Business Drivers": "Accountability",
        "Business Drivers Description": "Clear process ownership provides: end-to-end accountability, performance responsibility, improvement ownership, decision authority, cross-functional coordination.",
        "Performance Factors": "Clear Process Owners",
        "Performance Factors Description": "Strong ownership: every critical process has owner, owner accountable for performance, authority to improve, cross-functional view (not silo), ownership documented.",
        "Risk Factors": "Ownership Gaps",
        "Risk Factors Description": "No process ownership causes: accountability gaps, sub-optimization (silo view), no improvement ownership, performance blind spots, coordination failures.",
        "Metric": "Process Ownership Coverage",
        "Metric Description": "% of critical business processes with designated process owner (named, accountable, authority). Target: 100% of critical processes have owners.",
        "Unit": "Percentage (%)",
        "Target": "100% critical processes owned",
        "Instructions": "List all critical business processes (revenue-generating, customer-facing, regulatory). For each, identify process owner. Calculate % with designated owner. Target 100%."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Design > Scalability",
        "Description": "The ability of processes to handle increased volume without proportional increases in cost, complexity, or performance degradation",
        "Business Drivers": "Growth Enablement",
        "Business Drivers Description": "Scalable processes enable: growth without constraint, volume flexibility, cost efficiency at scale, competitive advantage, market expansion.",
        "Performance Factors": "Scalable Design",
        "Performance Factors Description": "Strong scalability: automation (not labor-intensive), standardized (repeatable), modular (add capacity), technology-enabled, marginal cost declines with volume.",
        "Risk Factors": "Non-Scalable Processes",
        "Risk Factors Description": "Non-scalable processes cause: growth constraints (capacity limits), high marginal costs (linear scaling), quality degradation at volume, competitive disadvantage.",
        "Metric": "Process Scalability Assessment",
        "Metric Description": "For key processes, assess scalability: automated?, standardized?, modular?, marginal cost profile? Score 0-100. Can processes handle 2-3x volume without redesign?",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly scalable)",
        "Instructions": "Assess critical processes on scalability dimensions: automation level, standardization, modularity, cost profile. Score each. Can handle 3x volume? Average to composite score."
    },

    # LEVEL 2: PROCESS DOCUMENTATION (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Processes > Process Documentation",
        "Description": "The completeness, currency, and accessibility of process documentation including process maps, procedures, work instructions, and standards",
        "Business Drivers": "Knowledge Management & Compliance",
        "Business Drivers Description": "Process documentation enables: knowledge preservation, training (onboarding), consistency (standard work), compliance (audit trail), improvement (analyze current state).",
        "Performance Factors": "Comprehensive, Current Documentation",
        "Performance Factors Description": "Strong documentation: all critical processes documented, current (<12 months old), accessible (repository), visual (process maps), detailed (work instructions).",
        "Risk Factors": "Documentation Gaps",
        "Risk Factors Description": "Poor documentation causes: knowledge loss (key person dependency), inconsistency (everyone does differently), training challenges, compliance violations, inability to improve.",
        "Metric": "Process Documentation Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Documentation Coverage + Documentation Currency + Documentation Accessibility + Documentation Quality. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining coverage data, currency tracking, accessibility assessment, and quality evaluation."
    },

    # LEVEL 3: Process Documentation Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Documentation > Documentation Coverage",
        "Description": "The percentage of critical business processes that have documented process maps, procedures, and work instructions",
        "Business Drivers": "Knowledge Capture",
        "Business Drivers Description": "Documentation coverage ensures: critical processes captured, knowledge preserved, no key person dependencies, compliance evidence, improvement baseline.",
        "Performance Factors": "Complete Documentation",
        "Performance Factors Description": "Strong coverage: 100% of critical processes documented (process maps + procedures), work instructions for complex steps, standards defined, exceptions documented.",
        "Risk Factors": "Undocumented Processes",
        "Risk Factors Description": "Documentation gaps cause: key person dependencies ('only Bob knows'), knowledge loss (when people leave), inconsistency, compliance risk, can't analyze for improvement.",
        "Metric": "Process Documentation Coverage Rate",
        "Metric Description": "% of critical processes with documented process maps and procedures. Critical processes = revenue-generating, customer-facing, regulatory. Target: 100%.",
        "Unit": "Percentage (%)",
        "Target": "100% critical processes documented",
        "Instructions": "List all critical business processes. For each, check: process map exists?, procedures documented?, work instructions for complex steps? Calculate % fully documented."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Documentation > Documentation Currency",
        "Description": "The recency and accuracy of process documentation reflecting current state versus outdated or inaccurate documentation",
        "Business Drivers": "Accuracy & Reliability",
        "Business Drivers Description": "Current documentation ensures: reflects reality (not outdated), reliable for training, audit compliance, improvement baseline accurate, no surprises (doc vs reality gap).",
        "Performance Factors": "Up-to-Date Documentation",
        "Performance Factors Description": "Strong currency: documentation updated <12 months, reflects current state, change management updates docs, review schedule, version control.",
        "Risk Factors": "Outdated Documentation",
        "Risk Factors Description": "Outdated docs cause: training on wrong process, compliance issues (audit finds doc-reality gap), false baseline (can't improve), loss of confidence in docs.",
        "Metric": "Documentation Currency Rate",
        "Metric Description": "% of process documentation updated within past 12 months. Regulatory processes may require more frequent updates. Target: >90% current (<12 mo).",
        "Unit": "Percentage (%)",
        "Target": ">90% updated <12 months",
        "Instructions": "Track last update date for all process documentation. Calculate % updated within 12 months. Red flag: >30% outdated. Implement review schedule."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Documentation > Documentation Accessibility",
        "Description": "The ease with which employees can find, access, and use process documentation when needed through centralized repositories and search",
        "Business Drivers": "Usability & Adoption",
        "Business Drivers Description": "Accessible documentation enables: self-service (find what you need), training (onboarding), consistent execution, reduced questions, compliance (everyone can access).",
        "Performance Factors": "Centralized, Searchable Repository",
        "Performance Factors Description": "Strong accessibility: centralized repository (not scattered), searchable, role-based access, mobile-friendly, integrated to workflow, usage analytics.",
        "Risk Factors": "Documentation Silos",
        "Risk Factors Description": "Poor accessibility causes: can't find docs (scattered locations), 'I didn't know that existed', inconsistent execution, repeated questions, underutilization.",
        "Metric": "Documentation Accessibility Score",
        "Metric Description": "Assessment: centralized repository (Y/N), searchable (Y/N), role-based access (Y/N), integrated to workflow (Y/N), usage tracked (Y/N). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly accessible)",
        "Instructions": "Assess documentation system: centralized?, searchable?, role-based?, workflow-integrated?, usage tracked? Score each dimension. Also survey users on ease of finding docs."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Documentation > Documentation Quality",
        "Description": "The clarity, completeness, and usability of process documentation measured by user satisfaction and effectiveness for training and execution",
        "Business Drivers": "Effectiveness",
        "Business Drivers Description": "High-quality documentation enables: effective training, consistent execution, rapid onboarding, reduced errors, user satisfaction, actual utilization.",
        "Performance Factors": "Clear, Complete, Visual",
        "Performance Factors Description": "Strong quality: clear language, complete (all steps), visual (process maps, flowcharts), examples, decision trees, templates, user-tested.",
        "Risk Factors": "Poor Quality Documentation",
        "Risk Factors Description": "Low-quality docs cause: confusion, incomplete guidance, unusable (no one uses), errors, training ineffective, preference for 'ask a person'.",
        "Metric": "Documentation Quality Score",
        "Metric Description": "User rating: 'Process documentation is clear, complete, and helpful for doing my job.' 5-point Likert scale. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Survey process users: documentation clarity, completeness, usefulness. Calculate % favorable (4-5 rating). <70% = quality issues. Test with new hires."
    },

    # LEVEL 2: PROCESS PERFORMANCE (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Processes > Process Performance",
        "Description": "The measurement and analysis of process performance including efficiency, quality, cycle time, and cost metrics",
        "Business Drivers": "Performance Visibility",
        "Business Drivers Description": "Process performance measurement enables: visibility to issues, data-driven improvement, accountability, benchmarking, continuous monitoring, early problem detection.",
        "Performance Factors": "Strong Performance Metrics",
        "Performance Factors Description": "Strong performance measurement: key metrics defined and tracked (cycle time, quality, cost), dashboards visible, trends analyzed, benchmarking, accountability.",
        "Risk Factors": "Performance Blind Spots",
        "Risk Factors Description": "No measurement causes: invisible problems, opinion-based improvement, no accountability, surprises, inability to demonstrate improvement, firefighting mode.",
        "Metric": "Process Performance Measurement Index",
        "Metric Description": "Composite of 4 sub-elements: Metric Definition + Performance Tracking + Trend Analysis + Benchmarking. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">80",
        "Instructions": "Average 4 sub-element scores combining metric coverage, tracking data, analysis practices, and benchmarking activity."
    },

    # LEVEL 3: Process Performance Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Performance > Metric Definition",
        "Description": "The completeness and appropriateness of process performance metrics covering efficiency, quality, speed, and cost dimensions",
        "Business Drivers": "Comprehensive Measurement",
        "Business Drivers Description": "Comprehensive metrics ensure: all performance dimensions covered (quality, speed, cost, efficiency), balanced (not just one dimension), actionable, aligned to objectives.",
        "Performance Factors": "Balanced Metrics",
        "Performance Factors Description": "Strong metrics: efficiency (resource utilization), quality (defect rates), speed (cycle time), cost (unit costs), balanced scorecard approach, leading + lagging.",
        "Risk Factors": "Metric Gaps or Imbalance",
        "Risk Factors Description": "Metric gaps cause: blind spots (unmeasured dimensions), sub-optimization (measure only cost, miss quality), inability to diagnose root causes.",
        "Metric": "Process Metric Coverage",
        "Metric Description": "% of critical processes with metrics covering 4 dimensions: efficiency, quality, cycle time, cost. Target: 100% of critical processes have balanced metrics.",
        "Unit": "Percentage (%)",
        "Target": "100% with balanced metrics",
        "Instructions": "List critical processes. For each, identify metrics across 4 dimensions: efficiency?, quality?, cycle time?, cost? Calculate % with balanced coverage (all 4 dimensions)."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Performance > Performance Tracking",
        "Description": "The frequency and reliability of collecting, recording, and reporting process performance data for monitoring and analysis",
        "Business Drivers": "Timely Visibility",
        "Business Drivers Description": "Regular tracking provides: timely visibility (early issue detection), trend analysis, performance accountability, data for improvement, dashboard reporting.",
        "Performance Factors": "Automated, Real-Time Tracking",
        "Performance Factors Description": "Strong tracking: automated data collection (not manual), frequent/real-time, reliable (accurate), dashboards available, exception alerts, accessible to owners.",
        "Risk Factors": "Tracking Gaps or Delays",
        "Risk Factors Description": "Poor tracking causes: late problem detection, manual effort (unsustainable), data gaps, unreliable, no dashboards, 'we don't know how we're doing'.",
        "Metric": "Automated Performance Tracking Rate",
        "Metric Description": "% of process metrics with automated data collection and reporting (vs manual). Automation enables real-time visibility. Target: >70% automated.",
        "Unit": "Percentage (%)",
        "Target": ">70% metrics automated",
        "Instructions": "Inventory all process metrics. Classify data collection: automated (systems) or manual. Calculate % automated. >70% enables real-time dashboards."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Performance > Trend Analysis",
        "Description": "The systematic analysis of performance trends over time to identify patterns, deterioration, improvement, and root causes",
        "Business Drivers": "Insight & Improvement",
        "Business Drivers Description": "Trend analysis enables: early deterioration detection, improvement validation, pattern identification, root cause analysis, proactive management.",
        "Performance Factors": "Regular Trend Analysis",
        "Performance Factors Description": "Strong analysis: trends reviewed monthly/quarterly, patterns identified, deterioration investigated, improvement validated, control charts used, statistical analysis.",
        "Risk Factors": "Point-in-Time Only",
        "Risk Factors Description": "No trend analysis causes: missed deterioration patterns, late problem detection, no validation that improvements worked, reactive (not proactive) management.",
        "Metric": "Performance Review Frequency",
        "Metric Description": "# of formal process performance reviews per year with documented trend analysis and actions. Best practice: monthly for critical processes.",
        "Unit": "Reviews per year",
        "Target": ">10 (monthly reviews)",
        "Instructions": "Track process performance review meetings for critical processes. Count annual frequency. Document: trends analyzed, actions identified. Monthly (12x/year) is best practice."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Performance > Benchmarking",
        "Description": "The comparison of process performance against industry benchmarks, best practices, and competitive standards to identify improvement opportunities",
        "Business Drivers": "Competitive Positioning",
        "Business Drivers Description": "Benchmarking provides: competitive context (how do we compare?), improvement targets (art of possible), best practice identification, reality check, ambition setting.",
        "Performance Factors": "Regular Benchmarking",
        "Performance Factors Description": "Strong benchmarking: regular external benchmarking (annual), industry benchmarks tracked, best practice identification, gap analysis, targets set from benchmarks.",
        "Risk Factors": "Internal Focus Only",
        "Risk Factors Description": "No benchmarking causes: internal frame of reference only, miss competitive gaps, set low targets (don't know what's possible), complacency.",
        "Metric": "Process Benchmarking Coverage",
        "Metric Description": "% of critical processes with external benchmarking conducted in past 24 months. Benchmarking identifies competitive gaps. Target: >60% benchmarked.",
        "Unit": "Percentage (%)",
        "Target": ">60% processes benchmarked",
        "Instructions": "List critical processes. For each, identify last external benchmarking: industry study, consultant benchmarking, peer comparison. Calculate % benchmarked <24 months."
    },

    # LEVEL 2: PROCESS CONTROL (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Processes > Process Control",
        "Description": "The mechanisms and practices for maintaining process stability, quality, and compliance including controls, checks, and variance management",
        "Business Drivers": "Quality & Compliance",
        "Business Drivers Description": "Process control ensures: consistent quality (reduce variation), compliance (requirements met), defect prevention, predictable outcomes, risk mitigation.",
        "Performance Factors": "Stable, Controlled Processes",
        "Performance Factors Description": "Strong process control: control points defined, checks performed, variation monitored, out-of-control addressed, compliance controls, preventive not detective.",
        "Risk Factors": "Out-of-Control Processes",
        "Risk Factors Description": "Weak control causes: high variation (unpredictable), quality issues (defects), compliance violations, surprises, reactive firefighting, customer dissatisfaction.",
        "Metric": "Process Control Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Control Point Coverage + Variation Management + Compliance Controls + Defect Prevention. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">85",
        "Instructions": "Average 4 sub-element scores combining control coverage, variation data, compliance assessments, and defect metrics."
    },

    # LEVEL 3: Process Control Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Control > Control Point Coverage",
        "Description": "The completeness of control points (checks, validations, approvals) at critical steps to prevent errors and ensure quality",
        "Business Drivers": "Error Prevention",
        "Business Drivers Description": "Control points prevent: errors propagating, defects reaching customers, rework, compliance violations, costly failures, downstream impacts.",
        "Performance Factors": "Comprehensive Control Points",
        "Performance Factors Description": "Strong control coverage: critical steps have controls, risk-based (high-risk = more control), automated where possible, preventive (not just detective).",
        "Risk Factors": "Control Gaps",
        "Risk Factors Description": "Control gaps allow: errors to propagate uncaught, defects reach customer, compliance violations, expensive failures, 'how did that get through?'.",
        "Metric": "Critical Step Control Coverage",
        "Metric Description": "% of critical process steps with defined control points (checks, validations, approvals). Critical steps = high-risk, quality-critical. Target: 100%.",
        "Unit": "Percentage (%)",
        "Target": "100% critical steps controlled",
        "Instructions": "For critical processes, identify critical steps (high-risk, quality-critical). For each, verify control point exists. Calculate % covered. Use FMEA to identify critical steps."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Control > Variation Management",
        "Description": "The monitoring and management of process variation to maintain stability and predictability using statistical process control techniques",
        "Business Drivers": "Predictability & Quality",
        "Business Drivers Description": "Variation management delivers: predictable outcomes (stable processes), consistent quality, reduced defects, root cause identification, continuous improvement focus.",
        "Performance Factors": "Controlled Variation",
        "Performance Factors Description": "Strong variation management: statistical process control (SPC) charts, common vs special cause distinction, processes in statistical control, variation reduction focus.",
        "Risk Factors": "Unmanaged Variation",
        "Risk Factors Description": "High variation causes: unpredictable outcomes, quality inconsistency, defects, customer dissatisfaction, inability to improve (noise obscures signal).",
        "Metric": "Process Stability Rate",
        "Metric Description": "% of critical processes in statistical control (control charts show process within control limits, no special cause variation). Target: >80% processes stable.",
        "Unit": "Percentage (%)",
        "Target": ">80% processes in control",
        "Instructions": "For critical processes, use control charts (SPC). Assess: within control limits?, no special cause variation? Calculate % in statistical control. Six Sigma target: >95%."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Control > Compliance Controls",
        "Description": "The controls ensuring processes comply with regulatory, legal, policy, and standard requirements with evidence for audits",
        "Business Drivers": "Regulatory Compliance",
        "Business Drivers Description": "Compliance controls prevent: regulatory violations (fines), legal liability, policy breaches, audit findings, business disruption, reputational damage.",
        "Performance Factors": "Strong Compliance Controls",
        "Performance Factors Description": "Strong compliance: controls mapped to requirements, automated where possible, documentation/evidence captured, regular testing, audit-ready.",
        "Risk Factors": "Compliance Gaps",
        "Risk Factors Description": "Compliance control gaps cause: violations (fines, penalties), audit findings, business disruption (orders to cease), legal liability, reputational damage.",
        "Metric": "Process Compliance Control Coverage",
        "Metric Description": "% of regulatory/policy requirements with documented process controls and evidence. Audit-ready means 100% coverage with evidence.",
        "Unit": "Percentage (%)",
        "Target": "100% requirements controlled",
        "Instructions": "Map regulatory and policy requirements to processes. For each requirement, verify: control exists?, evidence captured?, tested? Calculate % coverage. Audit-ready = 100%."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Control > Defect Prevention",
        "Description": "The proactive measures to prevent defects and errors including poka-yoke (error-proofing), design for quality, and root cause elimination",
        "Business Drivers": "Quality & Cost",
        "Business Drivers Description": "Defect prevention is cheapest quality approach: prevent vs detect vs fix. Saves: rework costs, customer dissatisfaction, warranty, reputation damage.",
        "Performance Factors": "Preventive Controls",
        "Performance Factors Description": "Strong prevention: poka-yoke (error-proofing) devices, design for manufacturability, root cause analysis/elimination, lessons learned applied.",
        "Risk Factors": "Detect-and-Fix Approach",
        "Risk Factors Description": "Detect-and-fix is expensive: rework costs, some defects reach customer, reactive mode, never eliminate root causes, high inspection costs.",
        "Metric": "First Pass Yield (FPY)",
        "Metric Description": "% of process outputs that pass all quality checks on first attempt without rework. Measures prevention effectiveness. Target: >95% first pass yield.",
        "Unit": "Percentage (%)",
        "Target": ">95% first pass yield",
        "Instructions": "Track all process outputs. Count those requiring rework or failing quality checks. Calculate % passing first time. <90% FPY = significant defect/rework issues."
    },

    # LEVEL 2: PROCESS IMPROVEMENT (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Processes > Process Improvement",
        "Description": "The systematic and continuous improvement of processes using methodologies like Lean, Six Sigma, Kaizen, and PDCA cycles",
        "Business Drivers": "Continuous Improvement",
        "Business Drivers Description": "Process improvement drives: cost reduction, quality improvement, cycle time reduction, capability building, competitive advantage, innovation.",
        "Performance Factors": "Active Improvement Culture",
        "Performance Factors Description": "Strong improvement culture: structured methodology (Lean, Six Sigma), improvement projects active, employee engagement (kaizen), measurable results, recognition.",
        "Risk Factors": "Improvement Stagnation",
        "Risk Factors Description": "No improvement causes: stagnation (no getting better), competitive decline, missed opportunities, employee disengagement, cost/quality deterioration over time.",
        "Metric": "Process Improvement Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Improvement Methodology + Project Pipeline + Employee Engagement + Results Achieved. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining methodology assessment, project data, engagement metrics, and results tracking."
    },

    # LEVEL 3: Process Improvement Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Improvement > Improvement Methodology",
        "Description": "The adoption and maturity of structured process improvement methodologies including Lean, Six Sigma, Kaizen, and PDCA",
        "Business Drivers": "Repeatable Success",
        "Business Drivers Description": "Structured methodology ensures: repeatable success (not random), trained practitioners, consistent approach, scalable improvement capability, knowledge capture.",
        "Performance Factors": "Mature Methodology",
        "Performance Factors Description": "Strong methodology: Lean/Six Sigma or equivalent adopted, certified practitioners (Green Belt, Black Belt), documented approach, tools/templates.",
        "Risk Factors": "Ad-Hoc Improvement",
        "Risk Factors Description": "No methodology causes: ad-hoc approaches, inconsistent results, inability to scale, untrained practitioners, repeated mistakes.",
        "Metric": "Process Improvement Methodology Maturity",
        "Metric Description": "Maturity level (1-5): 1=Ad-hoc, 2=Defined, 3=Managed, 4=Measured, 5=Optimized. Assess: methodology adopted, training, certification, results tracked.",
        "Unit": "Level (1-5)",
        "Target": "Level 4 (Measured)",
        "Instructions": "Assess improvement capability: methodology defined?, practitioners trained/certified?, consistently applied?, results measured?, continuous learning? Score 1-5 maturity."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Improvement > Project Pipeline",
        "Description": "The quantity and quality of active process improvement projects addressing priority opportunities for cost, quality, and cycle time improvement",
        "Business Drivers": "Improvement Capacity",
        "Business Drivers Description": "Active project pipeline ensures: continuous improvement (not one-off), priority opportunities addressed, momentum maintained, capability building, measurable results.",
        "Performance Factors": "Healthy Project Pipeline",
        "Performance Factors Description": "Strong pipeline: >5 active projects per 500 employees, prioritized by impact, resourced adequately, tracked to completion, success rate >70%.",
        "Risk Factors": "Empty Pipeline",
        "Risk Factors Description": "No improvement projects signals: stagnation, no improvement capacity, opportunities not identified, process improvement 'talked about not done'.",
        "Metric": "Active Improvement Projects per 500 Employees",
        "Metric Description": "# of active process improvement projects (Lean, Six Sigma, Kaizen) / 500 employees. Benchmark: 5+ per 500 = active improvement culture.",
        "Unit": "Count per 500 employees",
        "Target": ">5 per 500 employees",
        "Instructions": "Count all active process improvement projects (chartered, in-flight). Normalize by employee count (per 500 FTEs). >5 per 500 = healthy improvement culture."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Improvement > Employee Engagement in Improvement",
        "Description": "The breadth and depth of employee participation in process improvement activities including kaizen events, suggestion programs, and improvement teams",
        "Business Drivers": "Grassroots Improvement",
        "Business Drivers Description": "Employee engagement provides: frontline insights (they know the problems), ownership, motivation, distributed improvement (not centralized only), culture change.",
        "Performance Factors": "Broad Employee Involvement",
        "Performance Factors Description": "Strong engagement: >30% employees participate annually (kaizen, suggestions, teams), idea submission high, recognition programs, improvement celebrated.",
        "Risk Factors": "Top-Down Only Improvement",
        "Risk Factors Description": "No employee engagement limits: improvement ideas (miss frontline insights), ownership, culture change, sustainability, scalability.",
        "Metric": "Employee Improvement Participation Rate",
        "Metric Description": "% of employees who participated in improvement activities (kaizen events, improvement teams, suggestions) in past 12 months. Target: >30% participation.",
        "Unit": "Percentage (%)",
        "Target": ">30% employee participation",
        "Instructions": "Track participation in improvement activities: kaizen events, continuous improvement teams, suggestion program. Calculate % of employees who participated in past 12 months."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Improvement > Results Achieved",
        "Description": "The measurable results and benefits delivered from process improvement projects including cost savings, quality improvements, and cycle time reductions",
        "Business Drivers": "ROI & Credibility",
        "Business Drivers Description": "Measurable results deliver: ROI on improvement investment, credibility (improvement works), momentum, stakeholder support, competitive advantage.",
        "Performance Factors": "Significant Results",
        "Performance Factors Description": "Strong results: projects deliver 5-10x ROI, cost savings >1% of COGS, quality improvements measurable (defect reduction), cycle time reduction >20%.",
        "Risk Factors": "No Measurable Results",
        "Risk Factors Description": "Lack of results causes: improvement theater (activity but no impact), credibility loss, program defunding, 'it doesn't work', momentum loss.",
        "Metric": "Process Improvement ROI",
        "Metric Description": "Total annual benefits from process improvement projects / total investment (project costs + practitioner time). Benchmark: 5-10x ROI is typical for mature programs.",
        "Unit": "Ratio",
        "Target": ">5x ROI",
        "Instructions": "Track all improvement project benefits (cost savings, revenue, avoidance) and costs (project expenses, practitioner time). Calculate annual ROI. Mature programs: 5-10x."
    },

    # LEVEL 2: PROCESS TECHNOLOGY (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Processes > Process Technology",
        "Description": "The application of technology to automate, optimize, and enable business processes including workflow automation, RPA, and process mining",
        "Business Drivers": "Automation & Efficiency",
        "Business Drivers Description": "Process technology enables: automation (reduce manual work), efficiency (faster, cheaper), quality (eliminate human error), scalability, analytics (process mining).",
        "Performance Factors": "Technology-Enabled Processes",
        "Performance Factors Description": "Strong process technology: workflow automation, RPA where appropriate, process mining for insights, BPM platforms, API integration, end-to-end automation.",
        "Risk Factors": "Manual Processes",
        "Risk Factors Description": "Manual processes cause: inefficiency (slow, expensive), errors (human error), scalability limits, competitive disadvantage, employee frustration (boring work).",
        "Metric": "Process Technology Enablement Index",
        "Metric Description": "Composite of 4 sub-elements: Automation Coverage + RPA Adoption + Process Mining + Integration Level. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining automation metrics, RPA data, process mining adoption, and integration assessment."
    },

    # LEVEL 3: Process Technology Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Technology > Automation Coverage",
        "Description": "The percentage of process steps that are automated versus manual, focusing on automating repeatable, high-volume, or error-prone activities",
        "Business Drivers": "Efficiency & Quality",
        "Business Drivers Description": "Process automation delivers: cost reduction (less manual work), faster cycle times, quality improvement (eliminate errors), scalability, free people for higher-value work.",
        "Performance Factors": "High Automation",
        "Performance Factors Description": "Strong automation: >50% of process steps automated (vs manual), focus on high-volume/repeatable, workflow engines, straight-through processing.",
        "Risk Factors": "Manual-Intensive Processes",
        "Risk Factors Description": "Manual processes cause: high labor costs, slow cycle times, human errors, scalability limits, employee frustration (repetitive work).",
        "Metric": "Process Automation Rate",
        "Metric Description": "% of total process steps that are automated (vs manual). For key processes, map steps and classify as automated or manual. Target: >50% automated.",
        "Unit": "Percentage (%)",
        "Target": ">50% steps automated",
        "Instructions": "For key processes, map all steps. Classify each as automated (system/workflow) or manual (human). Calculate % automated. Industry leaders: 70-80% automation."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Technology > RPA Adoption",
        "Description": "The use of robotic process automation (RPA) to automate rule-based, repetitive tasks across applications without changing underlying systems",
        "Business Drivers": "Quick Automation Wins",
        "Business Drivers Description": "RPA provides: fast automation (weeks not months), no system changes needed, high ROI (payback <12 months), scalability, free people from repetitive tasks.",
        "Performance Factors": "Active RPA Program",
        "Performance Factors Description": "Strong RPA adoption: >10 bots in production, pipeline of automation opportunities, RPA COE (center of excellence), measurable ROI, scaling adoption.",
        "Risk Factors": "No RPA or RPA Theater",
        "Risk Factors Description": "Missing RPA opportunity = competitive disadvantage (competitors automate). RPA theater = pilots only, no scaling, no ROI.",
        "Metric": "Production RPA Bot Count",
        "Metric Description": "# of RPA bots deployed in production automating business processes. Benchmark: 0 = none, 5-10 = emerging, >20 = mature, >50 = advanced.",
        "Unit": "Count",
        "Target": ">10 production bots",
        "Instructions": "Count RPA bots in production (live, automating processes). Exclude pilots or development. Track: processes automated, hours saved, ROI. >10 bots = real program."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Technology > Process Mining",
        "Description": "The use of process mining tools to discover, analyze, and improve actual process flows using event logs and system data",
        "Business Drivers": "Process Intelligence",
        "Business Drivers Description": "Process mining reveals: actual process (not assumed), bottlenecks, variants, compliance gaps, improvement opportunities, data-driven insights.",
        "Performance Factors": "Active Process Mining",
        "Performance Factors Description": "Strong process mining: tools deployed, key processes analyzed, insights drive improvements, continuous monitoring, conformance checking (actual vs intended).",
        "Risk Factors": "No Process Intelligence",
        "Risk Factors Description": "Without process mining: rely on assumptions (not data), miss opportunities, can't identify bottlenecks systematically, manual analysis (expensive).",
        "Metric": "Process Mining Adoption",
        "Metric Description": "# of critical processes with active process mining analysis (discovery, conformance, enhancement). Benchmark: 0 = none, 3-5 = emerging, >10 = mature.",
        "Unit": "Count of processes",
        "Target": ">5 processes analyzed",
        "Instructions": "Count processes with process mining deployed: discovery (actual flow), conformance (actual vs model), performance (bottlenecks). >5 processes = meaningful adoption."
    },
    {
        "Level": 3,
        "Hierarchy": "Processes > Process Technology > Integration Level",
        "Description": "The degree to which process-supporting systems are integrated via APIs, workflows, and data sharing to enable end-to-end automation",
        "Business Drivers": "End-to-End Efficiency",
        "Business Drivers Description": "Integration eliminates: manual handoffs (data entry), delays (waiting), errors (transcription), duplication, enables straight-through processing.",
        "Performance Factors": "High Integration",
        "Performance Factors Description": "Strong integration: API-connected systems, workflow automation across systems, data sharing (no re-entry), end-to-end visibility, minimal manual handoffs.",
        "Risk Factors": "Siloed Systems",
        "Risk Factors Description": "Poor integration causes: manual handoffs (data re-entry), delays (waiting between systems), errors (transcription), duplication, slow cycle times.",
        "Metric": "Process Integration Score",
        "Metric Description": "Assessment of key processes: systems API-integrated?, workflow automation?, data shared?, manual handoffs eliminated? Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (highly integrated)",
        "Instructions": "For key processes, assess integration: systems connected?, APIs?, workflow automation?, data sharing?, straight-through processing? Score each dimension, average."
    }
]
