"""
Innovation Dimension Data - EXECUTION Domain
Expert Senior Business Analyst - 20+ years experience
31 rows: 1 dimension + 6 elements + 24 sub-elements
"""

innovation_data = [
    # LEVEL 1: INNOVATION DIMENSION
    {
        "Level": 1,
        "Hierarchy": "Innovation",
        "Description": "The organization's capability to generate, develop, and commercialize new ideas, products, services, processes, and business models",
        "Business Drivers": "Competitive Advantage & Growth",
        "Business Drivers Description": "Innovation drives: competitive differentiation, new revenue streams, market leadership, customer value creation, operational efficiency, strategic renewal, adaptation to disruption.",
        "Performance Factors": "Sustained Innovation Output",
        "Performance Factors Description": "High innovation performance shows: consistent new product/service launches, innovation revenue >20%, fast time-to-market, high success rates, innovation culture, portfolio approach.",
        "Risk Factors": "Innovation Failure & Stagnation",
        "Risk Factors Description": "Innovation risks: failed launches (wasted investment), slow market response (missed opportunities), disruption vulnerability (Kodak syndrome), commodity trap, talent loss (boring work).",
        "Metric": "Overall Innovation Health Score",
        "Metric Description": "Composite index of 6 element scores: Innovation Strategy + Idea Generation + Development Process + Portfolio Management + Launch Execution + Innovation Culture. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70 (healthy innovation capability)",
        "Instructions": "Calculate weighted average of 6 Level 2 element scores. Innovation leaders score >80. Weight by strategic importance to business model."
    },

    # LEVEL 2: INNOVATION STRATEGY (Element 1 of 6)
    {
        "Level": 2,
        "Hierarchy": "Innovation > Innovation Strategy",
        "Description": "The clarity and effectiveness of the innovation strategy including focus areas, ambition level, resource allocation, and strategic alignment",
        "Business Drivers": "Strategic Direction & Resource Allocation",
        "Business Drivers Description": "Clear innovation strategy ensures: focus (not random walk), appropriate ambition (incremental vs breakthrough), resource commitment, strategic alignment, measurable goals.",
        "Performance Factors": "Clear, Ambitious Strategy",
        "Performance Factors Description": "Strong innovation strategy shows: documented strategy, portfolio approach (70-20-10: core/adjacent/transformational), innovation budget >5% revenue, clear metrics, board oversight.",
        "Risk Factors": "Strategy Gaps",
        "Risk Factors Description": "Weak innovation strategy causes: random walk innovation (no focus), under-investment, incrementalism (no breakthrough), misalignment to strategy, innovation theater.",
        "Metric": "Innovation Strategy Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Strategy Clarity + Ambition Level + Resource Commitment + Strategic Alignment. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining strategy documentation, ambition assessment, resource data, and alignment evaluation."
    },

    # LEVEL 3: Innovation Strategy Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Strategy > Strategy Clarity",
        "Description": "The extent to which innovation strategy is clearly defined, documented, communicated, and understood across the organization",
        "Business Drivers": "Alignment & Focus",
        "Business Drivers Description": "Clear innovation strategy provides: direction for efforts, criteria for go/no-go decisions, resource allocation framework, accountability, ability to communicate to stakeholders.",
        "Performance Factors": "Documented, Communicated Strategy",
        "Performance Factors Description": "Strong strategy clarity shows: written innovation strategy, communicated organization-wide, focus areas defined, success metrics clear, regular strategy reviews.",
        "Risk Factors": "Strategy Ambiguity",
        "Risk Factors Description": "Unclear innovation strategy causes: diffused efforts, conflicting priorities, random walk, inability to say no, no accountability, stakeholder confusion.",
        "Metric": "Innovation Strategy Documentation Score",
        "Metric Description": "Assessment of innovation strategy maturity: 1=None, 2=Informal, 3=Documented, 4=Communicated, 5=Embedded. Score based on documentation, communication, and awareness.",
        "Unit": "Level (1-5)",
        "Target": "Level 4 (Documented + Communicated)",
        "Instructions": "Assess innovation strategy: Does written strategy exist? Communicated to org? Focus areas clear? Success metrics defined? Review meetings held? Score 1-5."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Strategy > Ambition Level",
        "Description": "The balance of innovation portfolio across incremental improvements (core), adjacent innovations, and transformational breakthroughs",
        "Business Drivers": "Growth & Transformation",
        "Business Drivers Description": "Appropriate ambition drives: sustained growth (core), expansion (adjacent), transformation (breakthrough). Too incremental = disruption risk. Too radical = execution risk.",
        "Performance Factors": "Balanced Portfolio (70-20-10)",
        "Performance Factors Description": "Optimal ambition: 70% core (incremental), 20% adjacent (new markets/products), 10% transformational (breakthrough). Adjust by industry dynamics and strategic needs.",
        "Risk Factors": "Ambition Mismatch",
        "Risk Factors Description": "Ambition risks: 100% incremental (disruption vulnerability), 100% breakthrough (execution failure, resource drain), no strategic fit (random innovation).",
        "Metric": "Innovation Portfolio Distribution",
        "Metric Description": "% of innovation investments by type: Core (incremental improvements), Adjacent (new markets/products), Transformational (breakthrough/disruptive). Target: ~70-20-10.",
        "Unit": "Percentage distribution",
        "Target": "~70% Core, ~20% Adjacent, ~10% Transformational",
        "Instructions": "Classify all active innovation projects by ambition type. Calculate investment % in each category. Benchmark 70-20-10 is typical; adjust for strategy and industry."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Strategy > Resource Commitment",
        "Description": "The level of financial, human, and time resources dedicated to innovation relative to revenue and strategic importance",
        "Business Drivers": "Innovation Capacity",
        "Business Drivers Description": "Resource commitment determines: innovation capacity (people, budget, time), credibility of commitment, ability to execute, competitive positioning (vs competitors' investment).",
        "Performance Factors": "Significant Investment",
        "Performance Factors Description": "Strong resource commitment shows: innovation budget 5-15% of revenue (varies by industry), dedicated innovation team, protected innovation time (20% time), C-suite oversight.",
        "Risk Factors": "Under-Investment",
        "Risk Factors Description": "Low innovation investment (<2% revenue) signals: incremental-only innovation, slow market response, competitive disadvantage, innovation theater (talk not action).",
        "Metric": "Innovation Investment as % of Revenue",
        "Metric Description": "Annual innovation spending (R&D, innovation team, projects, prototypes, experiments) / annual revenue. Benchmark: 2-5% (mature), 5-10% (growth), 10-20% (tech).",
        "Unit": "Percentage (% of revenue)",
        "Target": "5-15% depending on industry",
        "Instructions": "Calculate total innovation spending: R&D, innovation team salaries, project budgets, experiments, prototypes. Divide by annual revenue. Benchmark to industry."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Strategy > Strategic Alignment",
        "Description": "The degree to which innovation initiatives directly support and enable strategic objectives and business model evolution",
        "Business Drivers": "Strategic Impact",
        "Business Drivers Description": "Strategic alignment ensures: innovation serves strategy (not random), resource efficiency (focused efforts), measurable impact, stakeholder confidence, board support.",
        "Performance Factors": "Strategy-Aligned Innovation",
        "Performance Factors Description": "Strong alignment shows: innovation portfolio mapped to strategic objectives, innovation KPIs in strategic plan, quarterly strategy-innovation reviews, innovation = strategic priority.",
        "Risk Factors": "Innovation-Strategy Disconnect",
        "Risk Factors Description": "Misalignment causes: innovation doesn't move strategic needles, resource waste (interesting but irrelevant), lack of support, failed commercialization (no strategic home).",
        "Metric": "Innovation-Strategy Alignment Score",
        "Metric Description": "% of innovation projects with clear link to strategic objectives. Survey innovation and strategy leaders: alignment perception. Target: >80% of projects strategically aligned.",
        "Unit": "Percentage (%)",
        "Target": ">80% projects aligned to strategy",
        "Instructions": "Map innovation portfolio to strategic objectives. Calculate % with clear strategic link. Survey leaders on alignment perception. Score composite: project mapping + perception."
    },

    # LEVEL 2: IDEA GENERATION (Element 2 of 6)
    {
        "Level": 2,
        "Hierarchy": "Innovation > Idea Generation",
        "Description": "The processes and practices for sourcing, capturing, and screening innovative ideas from internal and external sources",
        "Business Drivers": "Innovation Pipeline",
        "Business Drivers Description": "Robust idea generation fills: innovation funnel (top), diverse perspectives (avoid groupthink), employee engagement (ideas valued), customer insights, competitive intelligence.",
        "Performance Factors": "Abundant, Diverse Ideas",
        "Performance Factors Description": "Strong idea generation shows: multiple idea sources (employees, customers, partners), high submission rates (>1 per employee/year), diverse ideas, open innovation programs.",
        "Risk Factors": "Idea Shortage",
        "Risk Factors Description": "Weak idea generation causes: empty pipeline, not-invented-here syndrome, missed market signals, employee disengagement, innovation starvation.",
        "Metric": "Idea Generation Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Idea Submission Rate + Source Diversity + Screening Process + Idea Quality. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">70",
        "Instructions": "Average 4 sub-element scores combining submission data, source diversity metrics, process assessment, and quality measures."
    },

    # LEVEL 3: Idea Generation Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Innovation > Idea Generation > Idea Submission Rate",
        "Description": "The frequency and quantity of innovation ideas submitted through formal and informal channels relative to employee base",
        "Business Drivers": "Pipeline Abundance",
        "Business Drivers Description": "High submission rates ensure: full funnel (can be selective), employee engagement (ideas encouraged), diverse perspectives, continuous flow of opportunities.",
        "Performance Factors": "High Submission Volumes",
        "Performance Factors Description": "Strong submission rates: >1 idea per employee per year, active idea management system, easy submission process, regular idea campaigns, visible leadership engagement.",
        "Risk Factors": "Low Idea Flow",
        "Risk Factors Description": "Low submission rates (<0.3 per employee) signal: disengagement, ideas not valued, difficult submission process, NIH culture, top-down only innovation.",
        "Metric": "Ideas Submitted per Employee per Year",
        "Metric Description": "Total innovation ideas submitted via all channels / average employee count. Benchmark: <0.5 = low, 0.5-1 = fair, >1 = strong, >2 = excellent.",
        "Unit": "Count per employee per year",
        "Target": ">1 idea per employee per year",
        "Instructions": "Track all idea submissions: innovation portal, suggestion box, hackathons, workshops, informal. Sum annual total, divide by average headcount."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Idea Generation > Source Diversity",
        "Description": "The breadth of idea sources tapped including employees, customers, partners, competitors, academia, and open innovation",
        "Business Drivers": "Perspective Diversity",
        "Business Drivers Description": "Diverse sources provide: broader perspectives, reduced groupthink, customer insights, technology access (partners), competitive intelligence, breakthrough ideas.",
        "Performance Factors": "Multiple Idea Channels",
        "Performance Factors Description": "Diverse idea sourcing: employee ideas, customer feedback, partner collaboration, open innovation challenges, trend scanning, academic partnerships, acquisitions.",
        "Risk Factors": "Single-Source Bias",
        "Risk Factors Description": "Limited sources cause: groupthink (internal-only), missed market signals, NIH syndrome, narrow perspectives, incremental-only thinking.",
        "Metric": "Active Idea Source Count",
        "Metric Description": "# of active idea sources contributing ideas in past 12 months: employees, customers, partners, open innovation, acquisitions, academia, competitors. Target: >4 sources active.",
        "Unit": "Count of active sources",
        "Target": ">4 active idea sources",
        "Instructions": "List idea source types. For each, identify if contributed ideas in past 12 months. Count active sources. Diverse innovation taps >4 sources."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Idea Generation > Screening Process",
        "Description": "The rigor and speed of processes for evaluating, filtering, and selecting ideas for further development based on strategic criteria",
        "Business Drivers": "Resource Efficiency",
        "Business Drivers Description": "Effective screening ensures: resource focus (best ideas), fast decisions (don't bottleneck), transparent criteria (trust in process), constructive feedback (encourage future submissions).",
        "Performance Factors": "Fast, Fair Screening",
        "Performance Factors Description": "Strong screening shows: clear evaluation criteria, cross-functional review, decision speed <30 days, feedback to submitters, stage-gate approach, transparent process.",
        "Risk Factors": "Screening Bottleneck or Bias",
        "Risk Factors Description": "Poor screening causes: bottlenecks (ideas die in queue), HiPPO bias (highest paid person's opinion), no feedback (discourages future submissions), risk aversion.",
        "Metric": "Idea Screening Cycle Time",
        "Metric Description": "Average days from idea submission to screening decision (advance/kill/defer). Fast, decisive screening: <30 days. Slow bottleneck: >90 days.",
        "Unit": "Days",
        "Target": "<30 days average screening time",
        "Instructions": "Track idea submission date and screening decision date. Calculate average cycle time. >90 days indicates bottleneck. Also track % screened (vs queue backlog)."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Idea Generation > Idea Quality",
        "Description": "The strategic value and feasibility of ideas generated, measured by conversion rate from ideas to funded projects",
        "Business Drivers": "Innovation ROI",
        "Business Drivers Description": "High-quality ideas increase: conversion efficiency (fewer ideas needed), resource productivity, success rates, strategic impact, stakeholder confidence.",
        "Performance Factors": "High Conversion Rate",
        "Performance Factors Description": "Quality idea generation: 5-15% conversion rate (ideas → funded projects), strategic fit, technical feasibility, market validation, economic viability.",
        "Risk Factors": "Low-Quality Ideas",
        "Risk Factors Description": "Poor idea quality causes: low conversion rates (<2%), wasted screening effort, innovation theater, disillusionment, resource drain on evaluation.",
        "Metric": "Idea-to-Project Conversion Rate",
        "Metric Description": "% of screened ideas that advance to funded development projects. Benchmark: 2-5% = typical, 5-10% = good, >10% = excellent (or too lenient screening).",
        "Unit": "Percentage (%)",
        "Target": "5-10% conversion rate",
        "Instructions": "Track ideas through funnel: submitted → screened → advanced to project → funded. Calculate % that reach funding. Too low (<2%) = quality issue. Too high (>15%) = screening too lenient."
    },

    # LEVEL 2: DEVELOPMENT PROCESS (Element 3 of 6)
    {
        "Level": 2,
        "Hierarchy": "Innovation > Development Process",
        "Description": "The methodologies, practices, and discipline for developing innovations from concept through validation to launch readiness",
        "Business Drivers": "Speed & Success Rate",
        "Business Drivers Description": "Effective development drives: fast time-to-market (beat competitors), high success rates (learn fast, kill fast), capital efficiency (fail cheap), quality at launch.",
        "Performance Factors": "Agile, Disciplined Development",
        "Performance Factors Description": "Strong development: stage-gate process, agile/lean methods, customer validation, MVP approach, fast failure, disciplined project management, cross-functional teams.",
        "Risk Factors": "Development Inefficiency",
        "Risk Factors Description": "Poor development causes: long cycle times (market window closes), high failure rates (late learning), big bets (expensive failures), quality issues at launch.",
        "Metric": "Development Process Effectiveness Index",
        "Metric Description": "Composite of 4 sub-elements: Time-to-Market + Development Success Rate + Customer Validation + Development Discipline. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining cycle time data, success metrics, validation practices, and process discipline assessments."
    },

    # LEVEL 3: Development Process Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Innovation > Development Process > Time-to-Market",
        "Description": "The speed of innovation development from project funding to market launch, measured by average development cycle time",
        "Business Drivers": "Competitive Advantage",
        "Business Drivers Description": "Fast time-to-market provides: first-mover advantage, rapid learning (more cycles), competitive positioning, revenue acceleration, reduced risk (shorter bets).",
        "Performance Factors": "Rapid Development Cycles",
        "Performance Factors Description": "Fast development: 3-9 months average (depends on complexity), agile/lean methods, MVP approach, parallel work streams, empowered teams, fast decision-making.",
        "Risk Factors": "Slow Development",
        "Risk Factors Description": "Slow cycles (>18 months) cause: missed market windows, competitive disadvantage, higher risk (long bets), fewer learning cycles, revenue delays.",
        "Metric": "Average Innovation Cycle Time",
        "Metric Description": "Average months from project funding to market launch. Benchmark varies by innovation type: Digital (3-6 mo), Product (9-18 mo), Service (6-12 mo), Process (6-9 mo).",
        "Unit": "Months",
        "Target": "<12 months average (varies by type)",
        "Instructions": "Track innovation projects: funding date → launch date. Calculate average cycle time. Segment by innovation type (digital, product, service). Compare to industry benchmarks."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Development Process > Development Success Rate",
        "Description": "The percentage of funded innovation projects that successfully launch to market versus those killed or abandoned during development",
        "Business Drivers": "Resource Efficiency",
        "Business Drivers Description": "Appropriate success rate balances: resource efficiency (not too many failures) with learning culture (fail fast on bad ideas). 60-80% success is healthy for portfolio approach.",
        "Performance Factors": "Balanced Success-Failure",
        "Performance Factors Description": "Healthy success rate: 60-80% of funded projects launch (depends on ambition). Too high (>90%) = not taking enough risk. Too low (<40%) = poor screening or development.",
        "Risk Factors": "Extreme Success or Failure Rates",
        "Risk Factors Description": "100% success = incrementalism, no risk-taking. <40% success = poor screening, weak development, random walk. Both indicate problems.",
        "Metric": "Innovation Launch Success Rate",
        "Metric Description": "% of funded innovation projects that successfully launch to market. Benchmark: 60-80% healthy (portfolio with some failures), <50% = poor development, >90% = too incremental.",
        "Unit": "Percentage (%)",
        "Target": "60-80% (balanced portfolio)",
        "Instructions": "Track all funded innovation projects to conclusion: launched, killed, or abandoned. Calculate % launched. Segment by ambition level (core vs transformational expect different rates)."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Development Process > Customer Validation",
        "Description": "The extent to which innovation development includes systematic customer feedback, testing, and validation before full launch",
        "Business Drivers": "Market Fit & Launch Success",
        "Business Drivers Description": "Customer validation prevents: build-it-they-won't-come failures, misaligned features, pricing errors, positioning mistakes. Increases launch success rates 2-3x.",
        "Performance Factors": "Rigorous Customer Testing",
        "Performance Factors Description": "Strong validation: customer discovery interviews, prototype testing, beta programs, minimum viable products (MVPs), iterative feedback, willingness-to-pay tests.",
        "Risk Factors": "Build Without Validation",
        "Risk Factors Description": "No customer validation causes: product-market fit failures (40% of failures), feature bloat (wrong features), pricing misses, expensive pivots post-launch.",
        "Metric": "Customer Validation Coverage",
        "Metric Description": "% of innovation projects that conduct customer validation before launch (interviews, testing, beta, MVP). Target: 100% for customer-facing innovations.",
        "Unit": "Percentage (%)",
        "Target": "100% for customer-facing innovations",
        "Instructions": "Track innovation projects. For each, document customer validation activities: discovery interviews, prototype testing, beta, MVP. Calculate % with validation. Require 100% for customer-facing."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Development Process > Development Discipline",
        "Description": "The rigor of project management, stage-gate governance, and milestone tracking throughout the innovation development process",
        "Business Drivers": "Predictability & Control",
        "Business Drivers Description": "Development discipline provides: predictable timelines, cost control, quality assurance, kill decision points (fail fast), visibility for leadership, resource optimization.",
        "Performance Factors": "Rigorous Process Adherence",
        "Performance Factors Description": "Strong discipline: stage-gate process followed, milestone tracking, go/no-go decisions, budget management, risk management, lessons learned captured.",
        "Risk Factors": "Process Chaos",
        "Risk Factors Description": "Weak discipline causes: timeline surprises, budget overruns, quality issues, no kill decisions (zombie projects), lack of visibility, inability to learn from failures.",
        "Metric": "Stage-Gate Compliance Rate",
        "Metric Description": "% of innovation projects that complete required stage-gate reviews with documented decisions. Strong discipline: >90% compliance. Ad-hoc: <60%.",
        "Unit": "Percentage (%)",
        "Target": ">90% stage-gate compliance",
        "Instructions": "Track innovation projects through stage-gate process. Document completion of required gate reviews. Calculate % with all gates completed. <70% indicates process breakdown."
    },

    # LEVEL 2: PORTFOLIO MANAGEMENT (Element 4 of 6)
    {
        "Level": 2,
        "Hierarchy": "Innovation > Portfolio Management",
        "Description": "The active management and optimization of the innovation portfolio including project selection, resource allocation, and portfolio balance",
        "Business Drivers": "Resource Optimization & Risk Balance",
        "Business Drivers Description": "Portfolio management optimizes: resource allocation (best opportunities), risk-return balance (portfolio approach), strategic alignment, capacity management, value maximization.",
        "Performance Factors": "Optimized Portfolio",
        "Performance Factors Description": "Strong portfolio management: regular portfolio reviews, balanced ambition levels, resource optimization, kill decisions made, portfolio metrics tracked, strategic alignment.",
        "Risk Factors": "Portfolio Imbalance",
        "Risk Factors Description": "Poor portfolio management causes: over-commitment (too many projects), imbalanced risk, misallocated resources, zombie projects, strategic drift.",
        "Metric": "Portfolio Management Maturity Index",
        "Metric Description": "Composite of 4 sub-elements: Portfolio Review Process + Portfolio Balance + Resource Allocation + Kill Discipline. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining process maturity, portfolio analysis, resource data, and decision discipline measures."
    },

    # LEVEL 3: Portfolio Management Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Innovation > Portfolio Management > Portfolio Review Process",
        "Description": "The frequency, rigor, and decision-making quality of regular innovation portfolio reviews at leadership level",
        "Business Drivers": "Active Management",
        "Business Drivers Description": "Regular portfolio reviews enable: course corrections, resource reallocation, kill decisions, strategic realignment, learning capture, stakeholder visibility.",
        "Performance Factors": "Quarterly Portfolio Reviews",
        "Performance Factors Description": "Strong review process: quarterly portfolio reviews, executive steering committee, decision authority, portfolio metrics dashboard, action items tracked.",
        "Risk Factors": "Passive Portfolio Management",
        "Risk Factors Description": "No reviews cause: zombie projects (no kill decisions), resource misallocations, strategic drift, slow response to changing conditions, lack of oversight.",
        "Metric": "Portfolio Review Frequency",
        "Metric Description": "# of formal innovation portfolio reviews per year at executive level with documented decisions. Benchmark: quarterly (4x/year) is best practice.",
        "Unit": "Reviews per year",
        "Target": ">4 (quarterly reviews)",
        "Instructions": "Track formal innovation portfolio review meetings: date, attendees (exec level?), decisions documented. Count annual frequency. Less than quarterly = passive management."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Portfolio Management > Portfolio Balance",
        "Description": "The distribution of innovation investments across different dimensions including ambition level, time horizon, risk level, and strategic themes",
        "Business Drivers": "Risk-Return Optimization",
        "Business Drivers Description": "Balanced portfolio manages: risk (mix of bets), return timing (short + long), strategic coverage (all themes), optionality (diverse bets), sustainable innovation.",
        "Performance Factors": "Strategic Balance",
        "Performance Factors Description": "Well-balanced portfolio: 70-20-10 ambition mix, time horizons balanced (short + long term), strategic themes covered, risk levels appropriate, not over-concentrated.",
        "Risk Factors": "Portfolio Concentration",
        "Risk Factors Description": "Imbalanced portfolio risks: over-concentration (single bet), all short-term (no breakthrough), all incremental (disruption vulnerability), strategic gaps.",
        "Metric": "Portfolio Balance Score",
        "Metric Description": "Assessment of portfolio balance across dimensions: ambition (70-20-10?), time horizon (mix?), strategic themes (covered?), risk (appropriate?). Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (well-balanced)",
        "Instructions": "Analyze innovation portfolio: ambition distribution, time to value, strategic theme coverage, risk levels. Score balance on each dimension. Weight by importance. Calculate composite."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Portfolio Management > Resource Allocation",
        "Description": "The effectiveness of allocating innovation resources (people, budget, time) to highest-value opportunities with clear prioritization",
        "Business Drivers": "Value Maximization",
        "Business Drivers Description": "Optimal resource allocation ensures: best opportunities funded, capacity matches commitments, strategic priorities reflected in resources, continuous optimization.",
        "Performance Factors": "Strategic Resource Deployment",
        "Performance Factors Description": "Strong allocation: prioritization process, resources aligned to strategy, capacity management (not over-committed), flexibility to reallocate, annual optimization.",
        "Risk Factors": "Resource Misallocation",
        "Risk Factors Description": "Poor allocation causes: under-resourced priorities, over-commitment (too many projects), peanut butter spread (equal to all), zombie projects drain resources.",
        "Metric": "Innovation Resource Utilization Rate",
        "Metric Description": "% of innovation resources (FTEs, budget) allocated to top-priority projects (top 25% by strategic value). Target: >70% to top priorities. <50% = poor prioritization.",
        "Unit": "Percentage (%)",
        "Target": ">70% resources to top priorities",
        "Instructions": "Rank all innovation projects by strategic value. Calculate resources (budget + FTEs) to top 25%. Divide by total innovation resources. Low % indicates poor prioritization."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Portfolio Management > Kill Discipline",
        "Description": "The willingness and ability to terminate underperforming innovation projects and reallocate resources rather than continuing zombie projects",
        "Business Drivers": "Resource Liberation",
        "Business Drivers Description": "Kill discipline frees: resources for better opportunities, team morale (finish vs endless projects), credibility of process, learning from failures, portfolio optimization.",
        "Performance Factors": "Active Kill Decisions",
        "Performance Factors Description": "Strong kill discipline: 20-40% of projects killed before launch (fail fast), clear kill criteria, leadership support for kills, blameless post-mortems, learning captured.",
        "Risk Factors": "Zombie Projects",
        "Risk Factors Description": "No kill decisions create: resource drains (zombie projects never die), missed opportunities (better projects not funded), demoralization, throw good money after bad.",
        "Metric": "Project Kill Rate",
        "Metric Description": "% of funded innovation projects killed before launch (fail-fast kills, not failures). Healthy: 20-40% killed. <10% = no discipline (zombies). >60% = poor screening.",
        "Unit": "Percentage (%)",
        "Target": "20-40% projects killed (fail fast)",
        "Instructions": "Track all funded innovation projects to outcome: launched, killed (deliberate), or failed. Calculate % deliberately killed before launch. Portfolio approach requires kill discipline."
    },

    # LEVEL 2: LAUNCH EXECUTION (Element 5 of 6)
    {
        "Level": 2,
        "Hierarchy": "Innovation > Launch Execution",
        "Description": "The planning, coordination, and execution of innovation launches including go-to-market, operations readiness, and early adoption",
        "Business Drivers": "Value Capture",
        "Business Drivers Description": "Launch execution determines: value capture (revenue), adoption rates, market positioning, competitive response, return on innovation investment.",
        "Performance Factors": "Successful Launches",
        "Performance Factors Description": "Strong launch execution: comprehensive launch planning, cross-functional coordination, operations readiness, effective go-to-market, adoption tracking, high success rates.",
        "Risk Factors": "Launch Failures",
        "Risk Factors Description": "Poor launch execution causes: adoption failures (launched but not adopted), operations problems, market positioning issues, revenue shortfalls, wasted development investment.",
        "Metric": "Launch Execution Success Index",
        "Metric Description": "Composite of 4 sub-elements: Launch Readiness + Go-to-Market Effectiveness + Adoption Rate + Revenue Achievement. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining readiness assessments, GTM metrics, adoption data, and revenue performance."
    },

    # LEVEL 3: Launch Execution Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Innovation > Launch Execution > Launch Readiness",
        "Description": "The completeness and quality of preparation across all functions (operations, sales, marketing, support, legal) prior to innovation launch",
        "Business Drivers": "Launch Quality",
        "Business Drivers Description": "Launch readiness prevents: operations failures (can't deliver), sales confusion (don't know how to sell), support issues (unprepared), legal blocks, quality problems.",
        "Performance Factors": "Comprehensive Readiness",
        "Performance Factors Description": "Strong readiness: launch checklist complete, cross-functional sign-off, operations ready, sales trained, marketing prepared, support equipped, quality validated.",
        "Risk Factors": "Unready Launch",
        "Risk Factors Description": "Launching unready causes: operations failures, sales ineffectiveness, support overwhelm, quality issues, rapid fixes (fire drills), poor first impressions.",
        "Metric": "Launch Readiness Checklist Completion",
        "Metric Description": "% of launch readiness checklist items completed before launch across functions: product, operations, sales, marketing, support, legal. Target: 100% for go-live.",
        "Unit": "Percentage (%)",
        "Target": "100% checklist complete before launch",
        "Instructions": "Create comprehensive launch readiness checklist (20-30 items across functions). Track completion for each launch. Calculate % complete at go-live. <90% = not ready."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Launch Execution > Go-to-Market Effectiveness",
        "Description": "The quality and impact of go-to-market activities including positioning, messaging, channel enablement, and marketing campaigns",
        "Business Drivers": "Market Awareness & Demand",
        "Business Drivers Description": "Effective GTM drives: market awareness, demand generation, sales enablement, channel activation, competitive positioning, adoption acceleration.",
        "Performance Factors": "Strong GTM Execution",
        "Performance Factors Description": "Strong GTM: clear positioning, compelling messaging, channel-ready, campaign execution, PR/media, customer education, sales tools, competitive differentiation.",
        "Risk Factors": "GTM Failure",
        "Risk Factors Description": "Weak GTM causes: low awareness (invisible launch), confused positioning, sales ineffectiveness, missed revenue targets, competitor exploitation of vacuum.",
        "Metric": "Launch Marketing Effectiveness Score",
        "Metric Description": "Assessment of GTM execution: positioning clarity, message resonance, campaign reach, channel readiness, sales enablement. Survey internal teams + measure awareness. Score 0-100.",
        "Unit": "Score (0-100)",
        "Target": ">80 (effective GTM)",
        "Instructions": "Assess GTM for each launch: positioning documented?, messaging tested?, campaigns executed?, channels enabled?, sales trained? Survey teams. Measure awareness lift. Score composite."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Launch Execution > Adoption Rate",
        "Description": "The speed and extent of customer adoption post-launch measured by uptake metrics, trial rates, conversion rates, and active usage",
        "Business Drivers": "Value Realization",
        "Business Drivers Description": "Strong adoption validates: market fit (customers want it), effective GTM (they know about it), value delivery (they use it), revenue realization (payback on investment).",
        "Performance Factors": "Rapid, Broad Adoption",
        "Performance Factors Description": "Strong adoption: rapid uptake (fast to target penetration), high trial rates, strong conversion (trial to paid), active usage, customer satisfaction, low churn.",
        "Risk Factors": "Adoption Failure",
        "Risk Factors Description": "Low adoption signals: product-market fit issues, weak GTM, value perception gap, pricing problems, quality issues. Indicates launch failure regardless of development success.",
        "Metric": "90-Day Post-Launch Adoption Rate",
        "Metric Description": "% of target customer segment that adopted (purchased, activated) innovation within 90 days of launch. Varies by innovation type and market. Track monthly cohorts.",
        "Unit": "Percentage (%)",
        "Target": ">10% of target segment at 90 days",
        "Instructions": "Define target customer segment. Track adoption (purchase, activation) post-launch. Calculate % of segment adopted at 30, 60, 90 days. Compare to target adoption curve."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Launch Execution > Revenue Achievement",
        "Description": "The degree to which innovation launches meet revenue projections and business case targets in first 12 months post-launch",
        "Business Drivers": "ROI Validation",
        "Business Drivers Description": "Revenue achievement validates: business case (ROI realized), market sizing (TAM accurate), pricing (willingness to pay), GTM effectiveness, innovation investment payback.",
        "Performance Factors": "Revenue Targets Met",
        "Performance Factors Description": "Strong revenue performance: meets or exceeds first-year targets, on trajectory for 3-year case, payback period <2 years, contribution margin positive by year 1.",
        "Risk Factors": "Revenue Shortfalls",
        "Risk Factors Description": "Missing revenue targets signals: overestimated TAM, pricing misses, adoption failures, competitive response, business case failures. Indicates launch or development problems.",
        "Metric": "Launch Revenue Achievement Rate",
        "Metric Description": "Actual first-year revenue / projected first-year revenue (from business case). Benchmark: 70-130% is typical range. <70% = significant miss. >130% = conservative forecast.",
        "Unit": "Percentage (% of target)",
        "Target": "80-120% of revenue target",
        "Instructions": "Track innovation launch revenue monthly. Compare to business case projections. Calculate 12-month actual vs target. Investigate >20% variances for lessons learned."
    },

    # LEVEL 2: INNOVATION CULTURE (Element 6 of 6)
    {
        "Level": 2,
        "Hierarchy": "Innovation > Innovation Culture",
        "Description": "The organizational culture, mindset, and behaviors that support and enable innovation including risk-taking, experimentation, and learning from failure",
        "Business Drivers": "Sustained Innovation Capability",
        "Business Drivers Description": "Innovation culture enables: sustained innovation (not one-time), employee engagement (ideas valued), risk-taking (breakthroughs), learning from failure, competitive advantage.",
        "Performance Factors": "Strong Innovation Mindset",
        "Performance Factors Description": "Strong innovation culture: experimentation encouraged, failure tolerated, ideas valued, innovation time allocated (20% time), innovation heroes, celebration of learning.",
        "Risk Factors": "Innovation-Hostile Culture",
        "Risk Factors Description": "Weak innovation culture: risk aversion, failure punished, ideas not valued, no time for innovation, incrementalism only, talented innovators leave.",
        "Metric": "Innovation Culture Health Index",
        "Metric Description": "Composite of 4 sub-elements: Risk-Taking Tolerance + Innovation Time Allocation + Idea Valuation + Learning from Failure. Weighted average.",
        "Unit": "Score (0-100)",
        "Target": ">75",
        "Instructions": "Average 4 sub-element scores combining survey data (culture perceptions) and behavioral data (time allocation, failure handling)."
    },

    # LEVEL 3: Innovation Culture Sub-elements (4 sub-elements)
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Culture > Risk-Taking Tolerance",
        "Description": "The degree to which the culture encourages intelligent risk-taking and experimentation rather than punishing failures",
        "Business Drivers": "Breakthrough Innovation",
        "Business Drivers Description": "Risk-taking tolerance enables: breakthrough innovation (not incremental only), experimentation, bold ideas, competitive advantage, talent attraction (innovators want to innovate).",
        "Performance Factors": "Safe to Experiment",
        "Performance Factors Description": "Strong risk tolerance: intelligent failures celebrated, experimentation encouraged, career safety (taking risks doesn't harm career), leadership role models risk-taking.",
        "Risk Factors": "Risk Aversion",
        "Risk Factors Description": "Risk-averse culture causes: incrementalism only (no breakthroughs), CYA behavior, analysis paralysis, innovation theater, talented innovators leave for risk-tolerant companies.",
        "Metric": "Risk-Taking Culture Score",
        "Metric Description": "Survey item: 'In this organization, it is safe to take intelligent risks and try new approaches even if they might fail.' 5-point Likert. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">75% favorable",
        "Instructions": "Include in innovation or culture survey. Calculate % responding 4-5 (agree/strongly agree). Segment by level (ICs vs managers). Innovation culture requires >70% favorable."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Culture > Innovation Time Allocation",
        "Description": "The extent to which employees are given protected time and permission to work on innovation projects beyond their day-to-day responsibilities",
        "Business Drivers": "Innovation Capacity",
        "Business Drivers Description": "Innovation time provides: capacity for innovation (not only off-hours), employee engagement (work on ideas), experimentation, signal that innovation is priority.",
        "Performance Factors": "Dedicated Innovation Time",
        "Performance Factors Description": "Strong time allocation: 20% time or equivalent, innovation sprints/hackathons, innovation sabbaticals, time protected (not first to cut), leadership support.",
        "Risk Factors": "No Innovation Time",
        "Risk Factors Description": "No dedicated time signals: innovation talk not action, employees must innovate on their own time (nights/weekends), burnout, only incremental innovation (no time for big ideas).",
        "Metric": "Innovation Time Utilization Rate",
        "Metric Description": "% of employees who utilized innovation time (20% time, hackathons, innovation projects) in past 12 months. Benchmark: >30% utilization indicates healthy culture.",
        "Unit": "Percentage (%)",
        "Target": ">30% employees used innovation time",
        "Instructions": "Track innovation time usage: 20% time projects, hackathon participation, innovation sprints. Calculate % of employees who participated in past 12 months."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Culture > Idea Valuation",
        "Description": "The degree to which employee ideas are actively sought, seriously considered, and contributors recognized and rewarded",
        "Business Drivers": "Employee Engagement & Ideas",
        "Business Drivers Description": "Valuing ideas drives: high submission rates (ideas encouraged), employee engagement (voice valued), diverse perspectives, innovation pipeline, retention of creative talent.",
        "Performance Factors": "Ideas Valued & Recognized",
        "Performance Factors Description": "Strong idea valuation: ideas actively solicited, serious consideration, transparent evaluation, feedback provided, recognition for contributors, rewards for adopted ideas.",
        "Risk Factors": "Ideas Not Valued",
        "Risk Factors Description": "Devaluing ideas causes: low submission rates, employee disengagement, loss of diverse perspectives, NIH syndrome (not invented here), creative talent attrition.",
        "Metric": "Idea Valuation Score",
        "Metric Description": "Survey item: 'My ideas for innovation and improvement are actively sought and seriously considered.' 5-point Likert scale. % favorable (4-5).",
        "Unit": "Percentage (% favorable)",
        "Target": ">70% favorable",
        "Instructions": "Include in employee engagement or innovation survey. Calculate % responding 4-5. <60% signals ideas not valued. Also track: recognition events, idea adoption rate."
    },
    {
        "Level": 3,
        "Hierarchy": "Innovation > Innovation Culture > Learning from Failure",
        "Description": "The organizational practices for conducting post-mortems, capturing lessons, and applying learnings from innovation failures",
        "Business Drivers": "Continuous Improvement",
        "Business Drivers Description": "Learning from failure enables: avoid repeated mistakes, build institutional knowledge, rapid iteration, innovation performance improvement, psychological safety.",
        "Performance Factors": "Systematic Learning",
        "Performance Factors Description": "Strong failure learning: blameless post-mortems conducted, lessons captured, knowledge shared, patterns identified, processes improved, failure tolerated (in bounds).",
        "Risk Factors": "Repeated Failures",
        "Risk Factors Description": "Not learning from failure causes: repeated mistakes, no improvement, blame culture, covering up failures (can't learn), wasted investment (same mistakes).",
        "Metric": "Post-Mortem Completion Rate",
        "Metric Description": "% of failed or killed innovation projects that conducted post-mortem to capture lessons learned. Target: 100% of significant failures/kills (>$50k invested).",
        "Unit": "Percentage (%)",
        "Target": "100% of significant failures",
        "Instructions": "Track all failed/killed innovation projects. Document post-mortem completion for each. Calculate % with post-mortem. Require 100% for projects >$50k investment."
    }
]
